import type { Product } from "@/types";

// ═══════════════════════════════════════════════════════════════
// Products scraped from pbac.pl — LG (7) and Toshiba (6)
// Source: WooCommerce Store API + variant price lookups
// Scraped: 2026-03-17
// ═══════════════════════════════════════════════════════════════

export const lgToshibaProducts: Product[] = [
  // ═══════════════════════════════════════════════
  // LG (7 products)
  // ═══════════════════════════════════════════════
  {
    slug: "lg-artcool-gallery",
    name: "LG Artcool Gallery",
    brand: "lg",
    category: "scienny",
    tagline: "Designerski klimatyzator z ramką na zdjęcia i dzieła sztuki",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG Artcool Gallery to wyjątkowy klimatyzator ścienny, który łączy funkcjonalność z designem. Wyposażony w czarną ramkę umożliwiającą personalizację za pomocą zdjęć lub dzieł sztuki, idealnie wkomponowuje się w nowoczesne wnętrza. Sprężarka Dual Inverter z 10-letnią gwarancją zapewnia cichą i energooszczędną pracę, a ekologiczny czynnik R32 minimalizuje wpływ na środowisko.",
    descriptionLong: [
      "LG Artcool Gallery to wyjątkowy klimatyzator ścienny, który łączy funkcjonalność z designem. Wyposażony w czarną ramkę umożliwiającą personalizację za pomocą zdjęć lub dzieł sztuki, idealnie wkomponowuje się w nowoczesne wnętrza.",
      "Sprężarka Dual Inverter z 10-letnią gwarancją zapewnia cichą i energooszczędną pracę. Klasa energetyczna A++ w chłodzeniu i A+ w grzaniu przekłada się na realne oszczędności.",
      "Ekologiczny czynnik R32 minimalizuje wpływ na środowisko. Wbudowany moduł Wi-Fi i aplikacja mobilna LG ThinQ umożliwiają zdalne sterowanie urządzeniem.",
    ],
    highlight: "Ramka na zdjęcia",
    features: [
      "Designerska ramka na zdjęcia i grafiki",
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Ekologiczny czynnik R32",
      "Klasa energetyczna A++/A+",
      "Cicha praca od 27 dB",
      "Sterowanie Wi-Fi przez aplikację LG ThinQ",
      "4-kierunkowy nawiew",
      "Tryb grzania i chłodzenia",
      "Automatyczne czyszczenie",
      "Timer 24-godzinny",
    ],
    advantages: [
      { title: "Design Gallery", desc: "Personalizacja frontu zdjęciami lub grafikami w eleganckiej ramce", icon: "paint-board" },
      { title: "Dual Inverter", desc: "Sprężarka z 10-letnią gwarancją, cicha i energooszczędna", icon: "energy" },
      { title: "Wi-Fi", desc: "Zdalne sterowanie przez aplikację LG ThinQ", icon: "wifi-full-signal" },
      { title: "Ekologia", desc: "Czynnik R32 o niskim potencjale tworzenia efektu cieplarnianego", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 27 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (LG ThinQ)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata / 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Artcool Gallery 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "27 dB", phase: "230V", price: 8028, area: "20–30 m²" },
      { name: "Artcool Gallery 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "30 dB", phase: "230V", price: 9139, area: "30–40 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 3,5 kW",
    warranty: "3 lata gwarancji / 10 lat sprężarka",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-gallery-klimatyzator-scienny-lg-artcool-gallery-1616955270.png",
    imageAlt: "Klimatyzator ścienny LG Artcool Gallery",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-gallery-8047.jpg", alt: "LG Artcool Gallery — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-gallery-8049.jpg", alt: "LG Artcool Gallery — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-gallery-16106.jpg", alt: "LG Artcool Gallery — aranżacja wnętrza" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-gallery-8046.jpg", alt: "LG Artcool Gallery — szczegóły" },
    ],
  },
  {
    slug: "lg-artcool-beige",
    name: "LG Artcool Beige",
    brand: "lg",
    category: "scienny",
    tagline: "Elegancki beżowy klimatyzator z jonizatorem Plasmaster i lampą UVnano",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG Artcool Beige to klimatyzator ścienny w eleganckiej beżowej kolorystyce, łączący zaawansowane technologie z wyjątkowym designem. Wyposażony w filtr antyalergiczny, jonizator Plasmaster Ionizer++ i lampę UVnano zapewnia czyste i zdrowe powietrze. Sprężarka Dual Inverter gwarantuje energooszczędną i cichą pracę od 19 dB.",
    descriptionLong: [
      "LG Artcool Beige to klimatyzator ścienny w eleganckiej beżowej kolorystyce, łączący zaawansowane technologie z wyjątkowym designem.",
      "Wyposażony w filtr antyalergiczny, jonizator Plasmaster Ionizer++ oraz lampę UVnano zapewniającą dezynfekcję powietrza i eliminację bakterii.",
      "Sprężarka Dual Inverter z 10-letnią gwarancją gwarantuje energooszczędną i cichą pracę od 19 dB. Sterowanie przez aplikację LG ThinQ umożliwia pełną kontrolę z dowolnego miejsca.",
    ],
    highlight: "Plasmaster Ionizer++",
    features: [
      "Elegancka beżowa obudowa",
      "Jonizator Plasmaster Ionizer++",
      "Lampa UVnano do dezynfekcji",
      "Filtr antyalergiczny",
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Ekologiczny czynnik R32",
      "Klasa energetyczna A++/A+",
      "Cicha praca od 19 dB",
      "Sterowanie Wi-Fi przez LG ThinQ",
      "4-kierunkowy nawiew",
      "Automatyczne czyszczenie",
      "Tryb grzania i chłodzenia",
    ],
    advantages: [
      { title: "Plasmaster Ionizer++", desc: "Zaawansowany jonizator neutralizujący alergeny i bakterie", icon: "shield-02" },
      { title: "UVnano", desc: "Lampa UV eliminująca mikroorganizmy z nawiewanego powietrza", icon: "sun-03" },
      { title: "Beżowy design", desc: "Elegancka kolorystyka pasująca do ciepłych wnętrz", icon: "paint-board" },
      { title: "Dual Inverter", desc: "Energooszczędna sprężarka z 10-letnią gwarancją", icon: "energy" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (LG ThinQ)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata / 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Artcool Beige 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 7026, area: "20–30 m²" },
      { name: "Artcool Beige 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 7374, area: "30–40 m²" },
      { name: "Artcool Beige 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 8543, area: "40–60 m²" },
      { name: "Artcool Beige 6,6 kW", power: "6,6 kW", energyClass: "A++/A+", noise: "32 dB", phase: "230V", price: 9865, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji / 10 lat sprężarka",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-lg-artcool-beige-1683721922.png",
    imageAlt: "Klimatyzator ścienny LG Artcool Beige",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-17457.jpg", alt: "LG Artcool Beige — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-17458.jpg", alt: "LG Artcool Beige — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-17459.jpg", alt: "LG Artcool Beige — szczegóły" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-17460.jpg", alt: "LG Artcool Beige — aranżacja" },
    ],
  },
  {
    slug: "lg-artcool-mirror",
    name: "LG Artcool Mirror",
    brand: "lg",
    category: "scienny",
    tagline: "Lustrzane wykończenie i zaawansowana technologia Dual Inverter",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG Artcool Mirror to klimatyzator ścienny z eleganckim, lustrzanym czarnym wykończeniem, który stanowi ozdobę każdego wnętrza. Wyposażony w sprężarkę Dual Inverter, czynnik R32 i wbudowany moduł Wi-Fi, zapewnia cichą pracę od 19 dB i wysoką efektywność energetyczną klasy A++/A+.",
    descriptionLong: [
      "LG Artcool Mirror to klimatyzator ścienny z eleganckim, lustrzanym czarnym wykończeniem, który stanowi ozdobę każdego wnętrza.",
      "Sprężarka Dual Inverter z 10-letnią gwarancją zapewnia cichą pracę od 19 dB i wysoką efektywność energetyczną A++ w chłodzeniu i A+ w grzaniu.",
      "Ekologiczny czynnik R32, wbudowany moduł Wi-Fi i sterowanie przez aplikację LG ThinQ umożliwiają komfortowe i oszczędne użytkowanie.",
    ],
    highlight: "Lustrzane wykończenie",
    features: [
      "Lustrzane czarne wykończenie frontu",
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Ekologiczny czynnik R32",
      "Klasa energetyczna A++/A+",
      "Cicha praca od 19 dB",
      "Sterowanie Wi-Fi przez LG ThinQ",
      "4-kierunkowy nawiew",
      "Automatyczne czyszczenie",
      "Tryb grzania i chłodzenia",
      "Złote lamele wymiennika Gold Fin",
    ],
    advantages: [
      { title: "Mirror Design", desc: "Lustrzane czarne wykończenie — elegancki akcent we wnętrzu", icon: "paint-board" },
      { title: "Dual Inverter", desc: "Sprężarka z 10-letnią gwarancją, cicha i energooszczędna", icon: "energy" },
      { title: "Wi-Fi", desc: "Zdalne sterowanie przez aplikację LG ThinQ", icon: "wifi-full-signal" },
      { title: "Gold Fin", desc: "Złota powłoka lamel chroniąca wymiennik przed korozją", icon: "shield-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (LG ThinQ)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata / 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Artcool Mirror 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 6789, area: "20–30 m²" },
      { name: "Artcool Mirror 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 7120, area: "30–40 m²" },
      { name: "Artcool Mirror 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 8229, area: "40–60 m²" },
      { name: "Artcool Mirror 6,6 kW", power: "6,6 kW", energyClass: "A++/A+", noise: "32 dB", phase: "230V", price: 9491, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji / 10 lat sprężarka",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-kopia-klimatyzator-lg-artcool-mirror-1616955286.png",
    imageAlt: "Klimatyzator ścienny LG Artcool Mirror",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-kopia-16100.jpg", alt: "LG Artcool Mirror — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-kopia-16091.jpg", alt: "LG Artcool Mirror — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-kopia-16093.jpg", alt: "LG Artcool Mirror — lustrzany front" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-artcool-beige-kopia-16094.jpg", alt: "LG Artcool Mirror — aranżacja" },
    ],
  },
  {
    slug: "lg-dualcool",
    name: "LG Dualcool",
    brand: "lg",
    category: "scienny",
    tagline: "Zaawansowany system oczyszczania powietrza z technologią Dual Inverter",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG DualCool to jeden z najnowszych klimatyzatorów ściennych koreańskiego lidera technologicznego. Wyróżnia się zaawansowanym systemem oczyszczania powietrza, który skutecznie wykrywa i neutralizuje zanieczyszczenia. Obieg chłodniczy wykorzystuje wydajny i ekologiczny czynnik R32. Producent gwarantuje trwałość i jakość poprzez 10-letnią ochronę sprężarki.",
    descriptionLong: [
      "LG DualCool to jeden z najnowszych klimatyzatorów ściennych koreańskiego lidera technologicznego. Wyróżnia się zaawansowanym systemem oczyszczania powietrza, który skutecznie wykrywa i neutralizuje zanieczyszczenia.",
      "Obieg chłodniczy wykorzystuje wydajny i ekologiczny czynnik R32. Producent gwarantuje trwałość i jakość poprzez 10-letnią ochronę sprężarki.",
      "Smukła biała obudowa pięknie komponuje się z różnorodnymi wnętrzami. Dzięki technologii sprężarki Dual Inverter osiąga znakomitą efektywność energetyczną: A++ w chłodzeniu i A+ w grzaniu.",
    ],
    highlight: "Oczyszczanie powietrza",
    features: [
      "Zaawansowany system oczyszczania powietrza",
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Ekologiczny czynnik R32",
      "Klasa energetyczna A++/A+",
      "Cicha praca od 21 dB",
      "Sterowanie Wi-Fi przez LG ThinQ",
      "Smukła biała obudowa",
      "Automatyczne czyszczenie",
      "Tryb grzania i chłodzenia",
      "Złote lamele wymiennika Gold Fin",
    ],
    advantages: [
      { title: "Oczyszczanie", desc: "Zaawansowany system wykrywania i neutralizacji zanieczyszczeń", icon: "shield-02" },
      { title: "Dual Inverter", desc: "Sprężarka z 10-letnią gwarancją — cicha i energooszczędna", icon: "energy" },
      { title: "Wi-Fi", desc: "Sterowanie przez aplikację mobilną LG ThinQ", icon: "wifi-full-signal" },
      { title: "Ekologia", desc: "Czynnik R32 o niskim potencjale tworzenia efektu cieplarnianego", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 21 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (LG ThinQ)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata / 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "DualCool 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "21 dB", phase: "230V", price: 6169, area: "20–30 m²" },
      { name: "DualCool 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 6517, area: "30–40 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 3,5 kW",
    warranty: "3 lata gwarancji / 10 lat sprężarka",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-dualcool-klimatyzator-scienny-lg-dualcool-1616955292.png",
    imageAlt: "Klimatyzator ścienny LG DualCool",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-dualcool-8204.jpg", alt: "LG DualCool — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-dualcool-8205.jpg", alt: "LG DualCool — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-dualcool-8206.jpg", alt: "LG DualCool — szczegóły" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-lg-dualcool-8207.jpg", alt: "LG DualCool — aranżacja" },
    ],
  },
  {
    slug: "lg-deluxe",
    name: "LG Deluxe",
    brand: "lg",
    category: "scienny",
    tagline: "Kompaktowa konstrukcja, najwyższa efektywność A++/A++ i cicha praca od 19 dB",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "Klimatyzator ścienny LG Deluxe łączy kompaktową konstrukcję, znakomitą efektywność energetyczną i cichą pracę. W eleganckiej białej obudowie pięknie komponuje się z różnorodnymi wnętrzami. Dzięki zaawansowanej sprężarce Dual Inverter i ekologicznemu czynnikowi R32 osiąga klasę energetyczną A++ zarówno w chłodzeniu, jak i grzaniu.",
    descriptionLong: [
      "Klimatyzator ścienny LG Deluxe łączy kompaktową konstrukcję, znakomitą efektywność energetyczną i cichą pracę. W eleganckiej białej obudowie pięknie komponuje się z różnorodnymi wnętrzami.",
      "Dzięki zaawansowanej sprężarce Dual Inverter i ekologicznemu czynnikowi R32 osiąga klasę energetyczną A++ zarówno w chłodzeniu, jak i grzaniu — to ekonomiczne i przyjazne środowisku rozwiązanie.",
      "Poziom hałasu od 19 dB zapewnia komfort nawet w sypialni. Powłoka Gold Fin na lamelach wymiennika zwiększa trwałość. Moduł Wi-Fi i aplikacja mobilna umożliwiają zdalne zarządzanie.",
    ],
    highlight: "A++/A++ Dual Inverter",
    features: [
      "Klasa energetyczna A++/A++ (chłodzenie i grzanie)",
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Ekologiczny czynnik R32",
      "Cicha praca od 19 dB",
      "Powłoka Gold Fin na wymienniku",
      "Sterowanie Wi-Fi przez LG ThinQ",
      "Kompaktowa biała obudowa",
      "Automatyczne czyszczenie",
      "4-kierunkowy nawiew",
      "Tryb grzania i chłodzenia",
    ],
    advantages: [
      { title: "A++/A++", desc: "Najwyższa efektywność energetyczna w obu trybach pracy", icon: "tick-02" },
      { title: "19 dB", desc: "Wyjątkowo cicha praca — komfort nawet w sypialni", icon: "volume-low" },
      { title: "Gold Fin", desc: "Złota powłoka lamel chroniąca wymiennik przed korozją", icon: "shield-02" },
      { title: "Wi-Fi", desc: "Zdalne sterowanie przez aplikację LG ThinQ", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (LG ThinQ)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata / 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Deluxe 2,5 kW", power: "2,5 kW", energyClass: "A++/A++", noise: "19 dB", phase: "230V", price: 5949, area: "20–30 m²" },
      { name: "Deluxe 3,5 kW", power: "3,5 kW", energyClass: "A++/A++", noise: "22 dB", phase: "230V", price: 6110, area: "30–40 m²" },
      { name: "Deluxe 5,0 kW", power: "5,0 kW", energyClass: "A++/A++", noise: "28 dB", phase: "230V", price: 7465, area: "40–60 m²" },
      { name: "Deluxe 6,6 kW", power: "6,6 kW", energyClass: "A++/A++", noise: "32 dB", phase: "230V", price: 8744, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji / 10 lat sprężarka",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-deluxe-lg-deluxe-1645079386.png",
    imageAlt: "Klimatyzator ścienny LG Deluxe",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-deluxe-16062.jpg", alt: "LG Deluxe — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-deluxe-16055.jpg", alt: "LG Deluxe — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-deluxe-16049.jpg", alt: "LG Deluxe — szczegóły" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-deluxe-16058.jpg", alt: "LG Deluxe — aranżacja" },
    ],
  },
  {
    slug: "lg-standard-2",
    name: "LG Standard 2",
    brand: "lg",
    category: "scienny",
    tagline: "Nowa jakość klimatyzacji ściennej z Dual Inverter i cichą pracą od 19 dB",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG Standard 2 wprowadza nową jakość w klimatyzacji ściennej, łącząc zaawansowaną technologię z łatwością obsługi. Wyposażony w innowacyjną sprężarkę Dual Inverter zapewnia wysoką efektywność energetyczną i cichą pracę, minimalizując wpływ na środowisko dzięki ekologicznemu czynnikowi R32. System automatycznego czyszczenia dba o higienę urządzenia.",
    descriptionLong: [
      "LG Standard 2 wprowadza nową jakość w klimatyzacji ściennej, łącząc zaawansowaną technologię z łatwością obsługi. Wyposażony w innowacyjną sprężarkę Dual Inverter zapewnia wysoką efektywność energetyczną i cichą pracę.",
      "Ekologiczny czynnik R32 minimalizuje wpływ na środowisko. System automatycznego czyszczenia dba o higienę urządzenia. Wyjątkowo cicha praca od 19 dB — zarówno jednostka wewnętrzna, jak i zewnętrzna cechują się niskim poziomem hałasu.",
      "Certyfikacja energetyczna A++ w chłodzeniu i A+ w grzaniu świadczy o wyjątkowej efektywności. Dodatkową zaletą jest intuicyjne sterowanie za pomocą wbudowanego modułu Wi-Fi i dedykowanej bezpłatnej aplikacji mobilnej LG.",
    ],
    highlight: "Cicha praca 19 dB",
    features: [
      "Sprężarka Dual Inverter",
      "Ekologiczny czynnik R32",
      "Klasa energetyczna A++/A+",
      "Cicha praca od 19 dB",
      "System automatycznego czyszczenia",
      "Sterowanie Wi-Fi przez LG ThinQ",
      "Kompaktowa biała obudowa",
      "4-kierunkowy nawiew",
      "Tryb grzania i chłodzenia",
      "Timer 24-godzinny",
    ],
    advantages: [
      { title: "19 dB", desc: "Wyjątkowo cicha praca — komfort nawet w sypialni", icon: "volume-low" },
      { title: "Dual Inverter", desc: "Energooszczędna sprężarka zapewniająca stabilną temperaturę", icon: "energy" },
      { title: "Wi-Fi", desc: "Zdalne sterowanie przez aplikację LG ThinQ", icon: "wifi-full-signal" },
      { title: "Autodiagnostyka", desc: "System automatycznego czyszczenia i monitorowania", icon: "shield-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (LG ThinQ)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata / 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Standard 2 — 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 4820, area: "20–30 m²" },
      { name: "Standard 2 — 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 4981, area: "30–40 m²" },
      { name: "Standard 2 — 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 6439, area: "40–60 m²" },
      { name: "Standard 2 — 6,6 kW", power: "6,6 kW", energyClass: "A++/A+", noise: "32 dB", phase: "230V", price: 7438, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji / 10 lat sprężarka",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-lg-standard-plus-1646913754.png",
    imageAlt: "Klimatyzator ścienny LG Standard 2",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-15951.jpg", alt: "LG Standard 2 — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-15945.jpg", alt: "LG Standard 2 — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-15946.jpg", alt: "LG Standard 2 — szczegóły" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-15947.jpg", alt: "LG Standard 2 — aranżacja" },
    ],
  },
  {
    slug: "lg-standard-plus",
    name: "LG Standard Plus",
    brand: "lg",
    category: "scienny",
    tagline: "Ekologiczny R32, Dual Inverter i 10-letnia gwarancja sprężarki",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG Standard Plus wyposażony w ekologiczny czynnik R32 i innowacyjną sprężarkę Dual Inverter osiąga wyjątkową efektywność energetyczną na poziomie A++ w chłodzeniu i A+ w grzaniu. Urządzenie pracuje nadzwyczaj cicho, od 19 dB. Korzysta z 3-letniej pełnej gwarancji i 10-letniej ochrony sprężarki.",
    descriptionLong: [
      "LG Standard Plus wyposażony w ekologiczny czynnik R32 i innowacyjną sprężarkę Dual Inverter osiąga wyjątkową efektywność energetyczną na poziomie A++ w chłodzeniu i A+ w grzaniu.",
      "Urządzenie pracuje nadzwyczaj cicho, od 19 dB. Korzysta z 3-letniej pełnej gwarancji i 10-letniej ochrony sprężarki, zapewniając niezawodność.",
      "Wyposażony w 4-kierunkowy nawiew, który rozprowadza klimatyzowane powietrze po całym pomieszczeniu, oraz filtry utrzymujące niski poziom zanieczyszczeń. Rozwiązania te umożliwiają skuteczną regulację klimatu przy jednoczesnym podnoszeniu standardu życia i komfortu.",
    ],
    highlight: "10 lat gwarancji sprężarki",
    features: [
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Ekologiczny czynnik R32",
      "Klasa energetyczna A++/A+",
      "Cicha praca od 19 dB",
      "4-kierunkowy nawiew",
      "Filtry antysmogowe",
      "Sterowanie Wi-Fi przez LG ThinQ",
      "Automatyczne czyszczenie",
      "Tryb grzania i chłodzenia",
      "Timer 24-godzinny",
    ],
    advantages: [
      { title: "10 lat gwarancji", desc: "Wydłużona ochrona sprężarki Dual Inverter", icon: "shield-02" },
      { title: "19 dB", desc: "Cicha praca zapewniająca komfort w każdym pomieszczeniu", icon: "volume-low" },
      { title: "A++/A+", desc: "Wysoka efektywność energetyczna w chłodzeniu i grzaniu", icon: "tick-02" },
      { title: "Wi-Fi", desc: "Sterowanie przez aplikację mobilną LG ThinQ", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (LG ThinQ)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata / 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Standard Plus 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 5253, area: "20–30 m²" },
      { name: "Standard Plus 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 5406, area: "30–40 m²" },
      { name: "Standard Plus 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 7050, area: "40–60 m²" },
      { name: "Standard Plus 6,6 kW", power: "6,6 kW", energyClass: "A++/A+", noise: "32 dB", phase: "230V", price: 8278, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji / 10 lat sprężarka",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-lg-standard-plus-1646913754.png",
    imageAlt: "Klimatyzator ścienny LG Standard Plus",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-15945.jpg", alt: "LG Standard Plus — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-15946.jpg", alt: "LG Standard Plus — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-15947.jpg", alt: "LG Standard Plus — szczegóły" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-plus-15948.jpg", alt: "LG Standard Plus — aranżacja" },
    ],
  },

  // ═══════════════════════════════════════════════
  // Toshiba (6 products)
  // ═══════════════════════════════════════════════
  {
    slug: "toshiba-seiya-2",
    name: "Toshiba Seiya 2",
    brand: "toshiba",
    category: "scienny",
    tagline: "Druga generacja ekonomicznego klimatyzatora z klasą A++/A++",
    origin: "Toshiba (Japonia)",
    description:
      "Toshiba Seiya 2 to klimatyzator ścienny drugiej generacji, który łączy zaawansowaną technologię, estetyczny design i atrakcyjną cenę. Dostępny w szerokim zakresie mocy od 1,5 do 6,5 kW, zapewnia klasę energetyczną A++/A++ dzięki technologii rotacyjnych sprężarek inwerterowych Toshiba.",
    descriptionLong: [
      "Toshiba Seiya 2 to klimatyzator ścienny drugiej generacji, który łączy zaawansowaną technologię, estetyczny design i atrakcyjną cenę.",
      "Dostępny w szerokim zakresie mocy od 1,5 do 6,5 kW, zapewnia klasę energetyczną A++/A++ dzięki technologii rotacyjnych sprężarek inwerterowych Toshiba.",
      "Cicha praca od 19 dB, ekologiczny czynnik R32 i opcjonalne sterowanie WiFi czynią Seiya 2 doskonałym wyborem zarówno do domów, jak i biur.",
    ],
    highlight: "Od 5 072 zł",
    features: [
      "Klasa energetyczna A++/A++",
      "Rotacyjne sprężarki inwerterowe Toshiba",
      "Ekologiczny czynnik R32",
      "Cicha praca od 19 dB",
      "Szeroki zakres mocy: 1,5 – 6,5 kW",
      "Estetyczny, kompaktowy design",
      "Opcjonalne sterowanie WiFi",
      "Tryb grzania i chłodzenia",
      "Automatyczny restart po awarii zasilania",
      "Timer 24-godzinny",
    ],
    advantages: [
      { title: "Atrakcyjna cena", desc: "Ekonomiczny model z pełnym wyposażeniem i szerokim zakresem mocy", icon: "money-02" },
      { title: "A++/A++", desc: "Wysoka efektywność energetyczna w chłodzeniu i grzaniu", icon: "tick-02" },
      { title: "7 wariantów", desc: "Od 1,5 do 6,5 kW — dopasowanie do każdego pomieszczenia", icon: "energy" },
      { title: "19 dB", desc: "Cicha praca zapewniająca komfort w każdym pomieszczeniu", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalnie", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Seiya 2 — 1,5 kW", power: "1,5 kW", energyClass: "A++/A++", noise: "19 dB", phase: "230V", price: 5072, area: "10–20 m²" },
      { name: "Seiya 2 — 2,0 kW", power: "2,0 kW", energyClass: "A++/A++", noise: "19 dB", phase: "230V", price: 5253, area: "10–20 m²" },
      { name: "Seiya 2 — 2,5 kW", power: "2,5 kW", energyClass: "A++/A++", noise: "21 dB", phase: "230V", price: 5460, area: "20–30 m²" },
      { name: "Seiya 2 — 3,3 kW", power: "3,3 kW", energyClass: "A++/A++", noise: "24 dB", phase: "230V", price: 5745, area: "30–40 m²" },
      { name: "Seiya 2 — 4,2 kW", power: "4,2 kW", energyClass: "A++/A++", noise: "28 dB", phase: "230V", price: 6962, area: "40–50 m²" },
      { name: "Seiya 2 — 5,0 kW", power: "5,0 kW", energyClass: "A++/A++", noise: "32 dB", phase: "230V", price: 7912, area: "50–60 m²" },
      { name: "Seiya 2 — 6,5 kW", power: "6,5 kW", energyClass: "A++/A++", noise: "36 dB", phase: "230V", price: 9129, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "1,5 – 6,5 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-2-kopia-toshiba-seiya-klimatyzator-1692950465.png",
    imageAlt: "Klimatyzator ścienny Toshiba Seiya 2",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-2-kopia-17677.jpg", alt: "Toshiba Seiya 2 — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-2-kopia-17674.jpg", alt: "Toshiba Seiya 2 — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-2-kopia-17678.jpg", alt: "Toshiba Seiya 2 — szczegóły" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-2-kopia-17675.jpg", alt: "Toshiba Seiya 2 — aranżacja" },
    ],
  },
  {
    slug: "toshiba-shorai-edge-black",
    name: "Toshiba Shorai Edge Black",
    brand: "toshiba",
    category: "scienny",
    tagline: "Eleganckie czarne wykończenie z klasą A+++/A+++ i filtrem Ultra Pure",
    origin: "Toshiba (Japonia)",
    description:
      "Klimatyzator ścienny Toshiba Shorai Edge Black pracuje na czynniku R32, zapewniając doskonałą wydajność zarówno w trybie chłodzenia, jak i ogrzewania, przy zachowaniu wysokiej efektywności energetycznej A+++/A+++. Dzięki eleganckiemu czarnemu wykończeniu dodaje stylu każdemu wnętrzu. Filtr Ultra Pure eliminuje cząsteczki PM2.5 i neutralizuje mikroorganizmy.",
    descriptionLong: [
      "Klimatyzator ścienny Toshiba Shorai Edge Black pracuje na czynniku R32, zapewniając doskonałą wydajność zarówno w trybie chłodzenia, jak i ogrzewania, przy zachowaniu najwyższej efektywności energetycznej A+++/A+++.",
      "Dzięki eleganckiemu czarnemu wykończeniu z matową powłoką dodaje stylu każdemu wnętrzu. Filtr Ultra Pure eliminuje cząsteczki PM2.5, neutralizuje szkodliwe mikroorganizmy i nieprzyjemne zapachy.",
      "Innowacyjna technologia nawiewu HADA-Care utrzymuje strumień powietrza płasko przy suficie, minimalizując bezpośredni nawiew. Wbudowany moduł Wi-Fi i kompatybilność z Google Home oraz Amazon Alexa zapewniają pełną kontrolę.",
    ],
    highlight: "A+++/A+++ Black Edition",
    features: [
      "Klasa energetyczna A+++/A+++",
      "Eleganckie czarne matowe wykończenie",
      "Filtr Ultra Pure (PM2.5)",
      "Technologia nawiewu HADA-Care",
      "Rotacyjne sprężarki inwerterowe Toshiba",
      "Ekologiczny czynnik R32",
      "Cicha praca od 19 dB",
      "Wbudowane Wi-Fi z aplikacją Toshiba Home AC Control",
      "Kompatybilność z Google Home i Amazon Alexa",
      "7 wariantów mocy: 2,0 – 7,0 kW",
      "Tryb ECO i Hi-Power",
    ],
    advantages: [
      { title: "A+++/A+++", desc: "Najwyższa klasa energetyczna w obu trybach pracy", icon: "tick-02" },
      { title: "Ultra Pure", desc: "Filtr eliminujący PM2.5 i neutralizujący mikroorganizmy", icon: "shield-02" },
      { title: "Black Design", desc: "Eleganckie czarne matowe wykończenie krawędziowe", icon: "paint-board" },
      { title: "HADA-Care", desc: "Nawiew przy suficie minimalizujący bezpośredni strumień", icon: "energy" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (Toshiba Home AC)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Shorai Edge Black 2,0 kW", power: "2,0 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 7012, area: "10–20 m²" },
      { name: "Shorai Edge Black 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 7488, area: "20–30 m²" },
      { name: "Shorai Edge Black 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "22 dB", phase: "230V", price: 8438, area: "30–40 m²" },
      { name: "Shorai Edge Black 4,6 kW", power: "4,6 kW", energyClass: "A+++/A+++", noise: "26 dB", phase: "230V", price: 9576, area: "30–40 m²" },
      { name: "Shorai Edge Black 5,0 kW", power: "5,0 kW", energyClass: "A+++/A+++", noise: "28 dB", phase: "230V", price: 11160, area: "40–50 m²" },
      { name: "Shorai Edge Black 6,1 kW", power: "6,1 kW", energyClass: "A+++/A+++", noise: "32 dB", phase: "230V", price: 11980, area: "50–60 m²" },
      { name: "Shorai Edge Black 7,0 kW", power: "7,0 kW", energyClass: "A+++/A+++", noise: "36 dB", phase: "230V", price: 13010, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,0 – 7,0 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-white-kopia-toshiba-shorai-edge-black-klimatyzator-1691744930.png",
    imageAlt: "Klimatyzator ścienny Toshiba Shorai Edge Black",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-white-kopia-17688.jpg", alt: "Toshiba Shorai Edge Black — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-white-kopia-17690.jpg", alt: "Toshiba Shorai Edge Black — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-white-kopia-toshiba-shorai-edge-black-1.webp", alt: "Toshiba Shorai Edge Black — czarny front" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-white-kopia-toshiba-shorai-edge-black-2.webp", alt: "Toshiba Shorai Edge Black — aranżacja" },
    ],
  },
  {
    slug: "toshiba-shorai-edge-white",
    name: "Toshiba Shorai Edge White",
    brand: "toshiba",
    category: "scienny",
    tagline: "Najnowsza generacja z klasą A+++/A+++ i filtrem Ultra Pure",
    origin: "Toshiba (Japonia)",
    description:
      "Toshiba Shorai Edge White to najnowszy klimatyzator ścienny wykorzystujący czynnik R32 z ośmioma wariantami wydajnościowymi i efektywnością energetyczną A+++/A+++. Filtr Ultra Pure poprawia jakość powietrza, a innowacyjna technologia nawiewu HADA-Care minimalizuje bezpośredni nawiew. Zintegrowany moduł Wi-Fi umożliwia zdalne sterowanie.",
    descriptionLong: [
      "Toshiba Shorai Edge White to najnowszy klimatyzator ścienny wykorzystujący czynnik R32 z siedmioma wariantami wydajnościowymi i efektywnością energetyczną A+++/A+++.",
      "Filtr Ultra Pure poprawia jakość powietrza poprzez eliminację cząsteczek PM2.5 i neutralizację mikroorganizmów. Technologia nawiewu HADA-Care minimalizuje bezpośredni nawiew, utrzymując strumień powietrza przy suficie.",
      "Zintegrowany moduł Wi-Fi i kompatybilność z asystentami głosowymi Google Home oraz Amazon Alexa umożliwiają pełną kontrolę. Tryb ECO i przycisk Hi-Power pozwalają na optymalizację zużycia energii.",
    ],
    highlight: "A+++/A+++ White Edition",
    features: [
      "Klasa energetyczna A+++/A+++",
      "Eleganckie białe wykończenie",
      "Filtr Ultra Pure (PM2.5)",
      "Technologia nawiewu HADA-Care",
      "Rotacyjne sprężarki inwerterowe Toshiba",
      "Ekologiczny czynnik R32",
      "Cicha praca od 19 dB",
      "Wbudowane Wi-Fi z aplikacją Toshiba Home AC Control",
      "Kompatybilność z Google Home i Amazon Alexa",
      "7 wariantów mocy: 2,0 – 7,0 kW",
      "Tryb ECO i Hi-Power",
    ],
    advantages: [
      { title: "A+++/A+++", desc: "Najwyższa klasa energetyczna w obu trybach pracy", icon: "tick-02" },
      { title: "Ultra Pure", desc: "Filtr eliminujący PM2.5 i neutralizujący mikroorganizmy", icon: "shield-02" },
      { title: "HADA-Care", desc: "Nawiew przy suficie minimalizujący bezpośredni strumień", icon: "energy" },
      { title: "Smart Home", desc: "Kompatybilność z Google Home i Amazon Alexa", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (Toshiba Home AC)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Shorai Edge White 2,0 kW", power: "2,0 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 6775, area: "10–20 m²" },
      { name: "Shorai Edge White 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 7171, area: "20–30 m²" },
      { name: "Shorai Edge White 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "22 dB", phase: "230V", price: 8121, area: "30–40 m²" },
      { name: "Shorai Edge White 4,6 kW", power: "4,6 kW", energyClass: "A+++/A+++", noise: "26 dB", phase: "230V", price: 9180, area: "30–40 m²" },
      { name: "Shorai Edge White 5,0 kW", power: "5,0 kW", energyClass: "A+++/A+++", noise: "28 dB", phase: "230V", price: 10605, area: "40–50 m²" },
      { name: "Shorai Edge White 6,1 kW", power: "6,1 kW", energyClass: "A+++/A+++", noise: "32 dB", phase: "230V", price: 11347, area: "50–60 m²" },
      { name: "Shorai Edge White 7,0 kW", power: "7,0 kW", energyClass: "A+++/A+++", noise: "36 dB", phase: "230V", price: 12218, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,0 – 7,0 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-lg-standard-2-kopia-toshiba-seiya-klimatyzator-1692950465.png",
    imageAlt: "Klimatyzator ścienny Toshiba Shorai Edge White",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-seiya-2-kopia-17679.jpg", alt: "Toshiba Shorai Edge White — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-seiya-2-kopia-17680.jpg", alt: "Toshiba Shorai Edge White — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-seiya-2-kopia-17682.jpg", alt: "Toshiba Shorai Edge White — szczegóły" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-seiya-2-kopia-17684.jpg", alt: "Toshiba Shorai Edge White — aranżacja" },
    ],
  },
  {
    slug: "toshiba-daiseikai-9",
    name: "Toshiba Daiseikai 9",
    brand: "toshiba",
    category: "scienny",
    tagline: "Flagowy model A+++/A+++ z jonizatorem Plasma Ion Charger",
    origin: "Toshiba (Japonia)",
    description:
      "Toshiba Daiseikai 9 to kolejny krok naprzód w świecie klimatyzacji domowej. Z eleganckim i nowoczesnym designem, ten model nie tylko zapewnia oszczędności energii dzięki klasie A+++/A+++, ale także dba o jakość powietrza za pomocą zaawansowanego systemu filtracji Plasma Ion Charger. Jego niesamowicie ciche działanie oraz inteligentne funkcje sprawiają, że zarządzanie klimatyzacją staje się wygodne i efektywne.",
    descriptionLong: [
      "Toshiba Daiseikai 9 to kolejny krok naprzód w świecie klimatyzacji domowej. Z eleganckim i nowoczesnym designem, ten model zapewnia oszczędności energii dzięki klasie A+++/A+++.",
      "Zaawansowany system filtracji Plasma Ion Charger dba o jakość powietrza, neutralizując alergeny, bakterie i wirusy. Niesamowicie ciche działanie od 20 dB zapewnia komfort w każdym pomieszczeniu.",
      "Rozbudowany programator tygodniowy, opcjonalne sterowanie WiFi, funkcja \"kominka\" i szeroki zakres pracy w różnych warunkach klimatycznych podnoszą standardy komfortu.",
    ],
    highlight: "Plasma Ion Charger",
    features: [
      "Klasa energetyczna A+++/A+++",
      "Jonizator Plasma Ion Charger",
      "Rotacyjne sprężarki inwerterowe Toshiba",
      "Ekologiczny czynnik R32",
      "Cicha praca od 20 dB",
      "Rozbudowany programator tygodniowy",
      "Opcjonalne sterowanie WiFi",
      "Funkcja \"kominka\"",
      "Szeroki zakres pracy temperaturowej",
      "Elegancki nowoczesny design",
    ],
    advantages: [
      { title: "A+++/A+++", desc: "Flagowa efektywność energetyczna — maksymalne oszczędności", icon: "tick-02" },
      { title: "Plasma Ion", desc: "Zaawansowana filtracja neutralizująca alergeny i wirusy", icon: "shield-02" },
      { title: "20 dB", desc: "Wyjątkowo cicha praca — niemal niesłyszalna", icon: "volume-low" },
      { title: "Kominek", desc: "Funkcja szybkiego ogrzewania dla natychmiastowego komfortu", icon: "thermometer-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 20 dB", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalnie", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Daiseikai 9 — 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "20 dB", phase: "230V", price: 10735, area: "20–30 m²" },
      { name: "Daiseikai 9 — 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "22 dB", phase: "230V", price: 11210, area: "30–40 m²" },
      { name: "Daiseikai 9 — 4,5 kW", power: "4,5 kW", energyClass: "A+++/A+++", noise: "26 dB", phase: "230V", price: 12823, area: "40–50 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 4,5 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-haori-kopia-toshiba-daiseikai-9-1689074880.png",
    imageAlt: "Klimatyzator ścienny Toshiba Daiseikai 9",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-haori-kopia-17716.jpg", alt: "Toshiba Daiseikai 9 — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-haori-kopia-17708.jpg", alt: "Toshiba Daiseikai 9 — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-haori-kopia-17711.jpg", alt: "Toshiba Daiseikai 9 — szczegóły" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-haori-kopia-17712.jpg", alt: "Toshiba Daiseikai 9 — aranżacja" },
    ],
  },
  {
    slug: "toshiba-konsola-bi-flow",
    name: "Toshiba Konsola Bi-Flow",
    brand: "toshiba",
    category: "podlogowy",
    tagline: "Kompaktowa konsola podłogowa z dwukierunkowym nawiewem i klasą A+++/A+",
    origin: "Toshiba (Japonia)",
    description:
      "Klimatyzator konsola Toshiba Bi-Flow to perfekcyjne połączenie wysokiej wydajności, komfortu oraz dbałości o czyste powietrze przez cały rok. Bez względu na pogodę na zewnątrz, ten system zapewnia optymalną temperaturę i czystość powietrza, pozostając przy tym praktycznie niezauważalnym w użytkowaniu. Jego kompaktowa konstrukcja sprawia, że doskonale nadaje się do montażu nawet w niewielkich pomieszczeniach, idealnie komponując się z przestrzenią podokienną.",
    descriptionLong: [
      "Klimatyzator konsola Toshiba Bi-Flow to perfekcyjne połączenie wysokiej wydajności, komfortu oraz dbałości o czyste powietrze przez cały rok.",
      "Bez względu na pogodę na zewnątrz, ten system zapewnia optymalną temperaturę i czystość powietrza, pozostając przy tym praktycznie niezauważalnym w użytkowaniu.",
      "Jego kompaktowa konstrukcja sprawia, że doskonale nadaje się do montażu nawet w niewielkich pomieszczeniach, idealnie komponując się z przestrzenią podokienną. Toshiba Konsola Bi-Flow to gwarancja doskonałego komfortu przy minimalizacji zużycia energii.",
    ],
    highlight: "Konsola podłogowa Bi-Flow",
    features: [
      "Dwukierunkowy nawiew Bi-Flow",
      "Klasa energetyczna A+++/A+",
      "Kompaktowa konstrukcja — montaż pod oknem",
      "Ekologiczny czynnik R32",
      "Cicha praca od 24 dB",
      "Rotacyjne sprężarki inwerterowe Toshiba",
      "Tryb grzania i chłodzenia",
      "Czyszczenie i filtracja powietrza",
      "Sterowanie pilotem na podczerwień",
      "Optymalizacja zużycia energii",
    ],
    advantages: [
      { title: "Bi-Flow", desc: "Dwukierunkowy nawiew dla równomiernego rozkładu temperatury", icon: "energy" },
      { title: "Kompaktowa", desc: "Idealnie komponuje się z przestrzenią podokienną", icon: "home-01" },
      { title: "A+++/A+", desc: "Wysoka efektywność energetyczna — oszczędności na rachunkach", icon: "tick-02" },
      { title: "Cały rok", desc: "Chłodzenie latem i grzanie zimą w jednym urządzeniu", icon: "thermometer-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 24 dB", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalnie", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Konsola Bi-Flow 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+", noise: "24 dB", phase: "230V", price: 8280, area: "25–35 m²" },
      { name: "Konsola Bi-Flow 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+", noise: "28 dB", phase: "230V", price: 9309, area: "25–35 m²" },
      { name: "Konsola Bi-Flow 5,0 kW", power: "5,0 kW", energyClass: "A+++/A+", noise: "32 dB", phase: "230V", price: 12348, area: "25–35 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 5,0 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-konsola-bi-flow-big-konsola-toshiba.jpg",
    imageAlt: "Klimatyzator konsola Toshiba Bi-Flow",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-konsola-bi-flow-ras-ufvconsole-top.webp", alt: "Toshiba Konsola Bi-Flow — widok z góry" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-konsola-bi-flow-60dfce787f5b961eda8f0a18215d8869.jpg", alt: "Toshiba Konsola Bi-Flow — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-konsola-bi-flow-varrmepumpe-gulvmodell-ute-av-syne.webp", alt: "Toshiba Konsola Bi-Flow — aranżacja" },
    ],
  },
  {
    slug: "toshiba-haori",
    name: "Toshiba Haori",
    brand: "toshiba",
    category: "scienny",
    tagline: "Tekstylny front w dwóch kolorach, A+++/A+++ i filtr Ultra Pure",
    origin: "Toshiba (Japonia)",
    description:
      "Klimatyzator Toshiba Haori to symbol nieograniczonych możliwości personalizacji, doskonałej wydajności oraz cichej i efektywnej pracy, zapewniającej niespotykaną jakość powietrza. Unikalny design z tekstylnym pokryciem frontu dostępnym w dwóch standardowych kolorach — ciemnoszarym i jasnoszarym — umożliwia pełną adaptację do indywidualnych preferencji.",
    descriptionLong: [
      "Klimatyzator Toshiba Haori to symbol nieograniczonych możliwości personalizacji, doskonałej wydajności oraz cichej i efektywnej pracy.",
      "Unikalny design z tekstylnym pokryciem frontu dostępnym w dwóch standardowych kolorach — ciemnoszarym i jasnoszarym — umożliwia pełną adaptację do indywidualnych preferencji użytkownika. Klasa energetyczna A+++ w obu trybach pracy.",
      "Cicha praca od 19 dB, filtr Toshiba Ultra Pure, jonizator plazmowy, technologia Magic Coil i nawiew HADA-Care zapewniają czyste powietrze i najwyższy komfort. Wbudowane Wi-Fi z kompatybilnością Google Home i Amazon Alexa.",
    ],
    highlight: "Tekstylny design",
    features: [
      "Tekstylne pokrycie frontu — personalizacja designu",
      "Klasa energetyczna A+++/A+++",
      "Filtr Toshiba Ultra Pure",
      "Jonizator plazmowy",
      "Technologia Magic Coil (samooczyszczanie wymiennika)",
      "Technologia nawiewu HADA-Care",
      "Cicha praca od 19 dB",
      "Wbudowane Wi-Fi — Toshiba Home AC Control",
      "Kompatybilność z Google Home i Amazon Alexa",
      "Tryb ECO i Hi-Power",
      "Ekologiczny czynnik R32",
    ],
    advantages: [
      { title: "Tekstylny front", desc: "Wymienne tkaniny w dwóch kolorach — dopasowanie do wnętrza", icon: "paint-board" },
      { title: "A+++/A+++", desc: "Najwyższa efektywność energetyczna — maksymalne oszczędności", icon: "tick-02" },
      { title: "Ultra Pure", desc: "Filtr i jonizator plazmowy dla czystego, zdrowego powietrza", icon: "shield-02" },
      { title: "Magic Coil", desc: "Samooczyszczanie wymiennika ciepła dla higieny urządzenia", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (Toshiba Home AC)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Haori 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 8042, area: "20–30 m²" },
      { name: "Haori 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "22 dB", phase: "230V", price: 8992, area: "30–40 m²" },
      { name: "Haori 4,6 kW", power: "4,6 kW", energyClass: "A+++/A+++", noise: "26 dB", phase: "230V", price: 11627, area: "40–50 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 4,6 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-black-kopia-toshiba-haori-klimatyzator-1692948156.png",
    imageAlt: "Klimatyzator ścienny Toshiba Haori",
    gallery: [
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-black-kopia-17693.jpg", alt: "Toshiba Haori — widok z przodu" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-black-kopia-17707.jpg", alt: "Toshiba Haori — widok boczny" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-black-kopia-17694.jpg", alt: "Toshiba Haori — tekstylny front" },
      { src: "https://pbac.pl/wp-content/uploads/2024/03/jachceklime.pl-toshiba-shorai-edge-black-kopia-toshiba-haori-3.webp", alt: "Toshiba Haori — aranżacja" },
    ],
  },
];
