import type { Product } from "@/types";

// ═══════════════════════════════════════════════════════════════
// Products scraped from pbac.pl — Haier
// Scraped: 2026-03-17
// ═══════════════════════════════════════════════════════════════

export const haierProducts: Product[] = [
  // ═══════════════════════════════════════════════
  // Haier (6 products)
  // ═══════════════════════════════════════════════
  {
    slug: "haier-flexis-plus-white-matt",
    name: "Haier Flexis Plus White Matt",
    brand: "haier",
    category: "scienny",
    tagline: "Smukła obudowa w białym macie z klasą A+++ i czynnikiem R32",
    origin: "Haier (Chiny)",
    description:
      "Haier Flexis Plus White Matt to klimatyzator ścienny o smukłej obudowie w białym matowym kolorze, która będzie pasować do wielu nowoczesnych aranżacji, w których przeważają powierzchnie bez połysku. Urządzenie posiada klasę energetyczną A+++ dla chłodzenia oraz A++ dla grzania, dlatego nie będzie generować wysokich kosztów eksploatacji. Wpływ na to ma zastosowanie w układzie ekologicznego i efektywnego czynnika chłodniczego R32.",
    descriptionLong: [
      "Flexis Plus w białym matowym wykończeniu to odpowiedź Haier na rosnące zapotrzebowanie na klimatyzatory, które nie tylko schładzają powietrze, ale też stanowią przemyślany element wystroju. Matowa powierzchnia bez połysku wpisuje się w aktualne trendy wnętrzarskie, gdzie dominują stonowane, pozbawione blasku materiały. Przy SEER 8,5 i SCOP 5,1 klimatyzator osiąga klasę A+++ w chłodzeniu i A++ w grzaniu.",
      "Technologia sterylizacji UV-C Pro to jedna z najskuteczniejszych metod oczyszczania powietrza stosowanych w klimatyzatorach domowych. Promieniowanie ultrafioletowe eliminuje do 99,9% bakterii i wirusów przechodzących przez jednostkę wewnętrzną. Dodatkowa funkcja 56°C Steri Clean podgrzewa wymiennik ciepła do 56°C, skutecznie niszcząc drobnoustroje — rozwiązanie opracowane z myślą o higienie w dobie zwiększonej świadomości epidemiologicznej.",
      "Technologia Coanda Plus kieruje strumień powietrza wzdłuż sufitu, zapewniając równomierne schłodzenie pomieszczenia bez bezpośredniego nawiewu na osoby przebywające w pokoju. Czujnik ruchu automatycznie dostosowuje kierunek i intensywność nawiewu w zależności od lokalizacji użytkowników, a czujnik temperatury w pilocie pozwala mierzyć temperaturę w miejscu przebywania, nie przy jednostce wewnętrznej.",
      "Cicha praca od 18 dB(A), wbudowany moduł Wi-Fi z aplikacją mobilną, automatyczne sterowanie nawiewem 3D i kompaktowa konstrukcja ułatwiająca czyszczenie — Flexis Plus to jeden z najbardziej kompletnych klimatyzatorów w segmencie średnim. 5-letnia gwarancja producenta dodatkowo potwierdza zaufanie Haier do trwałości tego modelu.",
    ],
    highlight: "Biały mat A+++",
    features: [
      "Klasa energetyczna A+++ (chłodzenie) / A++ (grzanie)",
      "Smukła obudowa w białym matowym kolorze",
      "Ekologiczny czynnik chłodniczy R32",
      "Sterylizacja UV-C Pro",
      "Funkcja 56°C Steri Clean",
      "Technologia Coanda Plus",
      "Moduł Wi-Fi w standardzie",
      "Kompaktowa konstrukcja ułatwiająca czyszczenie",
      "Czujnik temperatury w pilocie",
      "Czujnik ruchu",
      "Automatyczne sterowanie nawiewem 3D",
      "Cicha praca od 18 dB",
    ],
    advantages: [
      { title: "Biały mat", desc: "Smukła obudowa w białym matowym kolorze pasująca do nowoczesnych aranżacji", icon: "paint-board" },
      { title: "A+++", desc: "Najwyższa klasa energetyczna w trybie chłodzenia obniżająca rachunki", icon: "tick-02" },
      { title: "UV-C Pro", desc: "Sterylizacja powietrza eliminująca bakterie i wirusy", icon: "sun-03" },
      { title: "Coanda Plus", desc: "Silniejszy nawiew docierający do każdej części pomieszczenia", icon: "energy" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 18 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Flexis Plus White Matt 2,6 kW", power: "2,6 kW", energyClass: "A+++/A++", noise: "18 dB", phase: "230V", price: 4690, area: "20–30 m²" },
      { name: "Flexis Plus White Matt 3,5 kW", power: "3,5 kW", energyClass: "A+++/A++", noise: "18 dB", phase: "230V", price: 5160, area: "30–40 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 3,5 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/haier-flexis-plus-white-matt.jpg",
    imageAlt: "Klimatyzator ścienny Haier Flexis Plus White Matt",
    gallery: [
      { src: "/images/products/haier-flexis-plus-white-matt-gallery-0.webp", alt: "Haier Flexis Plus White Matt — utrzymanie temperatury +10°C" },
      { src: "/images/products/haier-flexis-plus-white-matt-gallery-1.webp", alt: "Haier Flexis Plus White Matt — automatyczne sterowanie nawiewem 3D" },
      { src: "/images/products/haier-flexis-plus-white-matt-gallery-2.jpg", alt: "Haier Flexis Plus White Matt — widok z boku" },
      { src: "/images/products/haier-flexis-plus-white-matt-gallery-3.jpg", alt: "Haier Flexis Plus White Matt — widok z przodu" },
      { src: "/images/products/haier-flexis-plus-white-matt-gallery-4.jpg", alt: "Haier Flexis Plus White Matt — szczegóły" },
      { src: "/images/products/haier-flexis-plus-white-matt-gallery-5.jpg", alt: "Haier Flexis Plus White Matt — panel" },
      { src: "/images/products/haier-flexis-plus-white-matt-gallery-6.jpg", alt: "Haier Flexis Plus White Matt — widok dolny" },
      { src: "/images/products/haier-flexis-plus-white-matt-gallery-7.jpg", alt: "Haier Flexis Plus White Matt — montaż" },
      { src: "/images/products/haier-flexis-plus-white-matt-gallery-8.jpg", alt: "Haier Flexis Plus White Matt — wnętrze" },
    ],
  },
  {
    slug: "haier-jade-plus",
    name: "Haier Jade Plus",
    brand: "haier",
    category: "scienny",
    tagline: "Flagowy klimatyzator A+++ z pracą od 15 dB i zaawansowanymi czujnikami jakości powietrza",
    origin: "Haier (Chiny)",
    description:
      "Haier Jade Plus to zaawansowany klimatyzator ścienny, który zadebiutował na rynku w 2019 roku, przynoszący ze sobą rewolucję w dziedzinie klimatyzacji. Jego wyjątkowość tkwi w szerokim wachlarzu funkcji oraz innowacyjnych rozwiązaniach, które gwarantują nie tylko czyste powietrze najwyższej jakości, ale także niski poziom hałasu już od 15 dB. Do dziś jest to jedno z najcichszych oraz najbardziej atrakcyjnych urządzeń dostępnych na rynku. Klimatyzator Haier Jade Plus to także symbol energooszczędności — zdobył on najwyższą klasę energetyczną A+++, zarówno w trybie chłodzenia, jak i grzania. Jego układ chłodniczy opiera się na wysoce efektywnym i ekologicznym czynniku R32. Ponadto klimatyzator wyposażony jest w zestaw zaawansowanych czujników, które monitorują jakość powietrza w pomieszczeniu, zapewniając jeszcze wyższy poziom komfortu użytkowania.",
    descriptionLong: [
      "Haier Jade Plus to bezapelacyjnie jeden z najlepszych klimatyzatorów domowych dostępnych na polskim rynku. Współczynniki SEER 8,75 i SCOP 5,10 dla wariantu 2,6 kW plasują go wśród absolutnych liderów efektywności energetycznej — klasa A+++ zarówno w chłodzeniu, jak i grzaniu to wynik, który osiąga zaledwie garstka modeli na rynku. Roczne zużycie energii wynosi zaledwie 104 kWh (chłodzenie) i 714 kWh (grzanie), co przekłada się na jedne z najniższych kosztów eksploatacji.",
      "Poziom hałasu od 15 dB(A) to wartość na granicy percepcji ludzkiego ucha — ciszej niż spadający liść. Jade Plus jest jednym z najcichszych klimatyzatorów na świecie, co czyni go idealnym wyborem do sypialni, pokoi dziecięcych i gabinetów, gdzie cisza jest priorytetem. Jednostka wewnętrzna generuje ciśnienie akustyczne na poziomie 36/32/29/15 dB(A) na poszczególnych biegach wentylatora.",
      "Zestaw zaawansowanych czujników jakości powietrza monitoruje środowisko w pomieszczeniu w czasie rzeczywistym i automatycznie dostosowuje parametry pracy. Haier Jade Plus chłodzi przy temperaturach zewnętrznych od -10°C do +43°C, a grzeje nawet przy -20°C — zakres, który pozwala wykorzystywać urządzenie jako uzupełniające źródło ciepła w polskich warunkach klimatycznych. Współczynnik EER 4,5 i COP 4,8 potwierdzają wyjątkową wydajność termodynamiczną.",
      "Wbudowany moduł Wi-Fi, konstrukcja rurowa 2-drogowa ułatwiająca montaż, tryb Turbo Cooling do szybkiego schładzania oraz 5-letnia gwarancja producenta. Jade Plus jest dostępny w wariantach 2,6 kW, 3,5 kW i 5,2 kW. Na tle konkurencji — Samsung Wind-Free Elite czy Toshiba Daiseikai 9 — Jade Plus oferuje porównywalną efektywność energetyczną przy niższej cenie, co czyni go jednym z najbardziej opłacalnych premium klimatyzatorów na polskim rynku.",
    ],
    highlight: "A+++ chłodzenie i grzanie",
    features: [
      "Klasa energetyczna A+++ (chłodzenie i grzanie)",
      "Cicha praca od 15 dB",
      "Zaawansowane czujniki jakości powietrza",
      "Ekologiczny czynnik chłodniczy R32",
      "Konstrukcja rurowa 2-drogowa",
      "Gwarancja 5 lat",
      "Automatyczny restart",
      "Autodiagnostyka",
      "Chłodzenie do -10°C",
      "Ciepły start",
      "Grzanie do -20°C",
      "Inteligentne odszranianie",
      "Karta On/Off",
      "Tryb komfortowego snu",
      "Sterowanie przewodowe (opcja)",
      "Tryb Turbo Cooling",
      "Wyświetlacz LED",
      "Moduł Wi-Fi w standardzie",
    ],
    advantages: [
      { title: "Od 15 dB", desc: "Jedno z najcichszych urządzeń klimatyzacyjnych na rynku", icon: "volume-low" },
      { title: "A+++ / A+++", desc: "Najwyższa klasa energetyczna zarówno w chłodzeniu, jak i grzaniu", icon: "tick-02" },
      { title: "Czujniki jakości", desc: "Zaawansowane czujniki monitorujące jakość powietrza w pomieszczeniu", icon: "shield-02" },
      { title: "R32 Eco", desc: "Ekologiczny i wydajny czynnik chłodniczy nowej generacji", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 15 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Jade Plus 2,6 kW", power: "2,6 kW", energyClass: "A+++/A+++", noise: "15 dB", phase: "230V", price: 7872, area: "20–30 m²" },
      { name: "Jade Plus 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "16 dB", phase: "230V", price: 8224, area: "30–40 m²" },
      { name: "Jade Plus 5,2 kW", power: "5,2 kW", energyClass: "A+++/A+++", noise: "16 dB", phase: "230V", price: 11496, area: "40–60 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 5,2 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/haier-jade-plus.png",
    imageAlt: "Klimatyzator ścienny Haier Jade Plus",
    gallery: [
      { src: "/images/products/haier-jade-plus-gallery-0.jpg", alt: "Haier Jade Plus — widok z przodu" },
      { src: "/images/products/haier-jade-plus-gallery-1.jpg", alt: "Haier Jade Plus — widok z boku" },
      { src: "/images/products/haier-jade-plus-gallery-2.jpg", alt: "Haier Jade Plus — panel sterowania" },
      { src: "/images/products/haier-jade-plus-gallery-3.jpg", alt: "Haier Jade Plus — nawiew" },
      { src: "/images/products/haier-jade-plus-gallery-4.jpg", alt: "Haier Jade Plus — szczegóły techniczne" },
      { src: "/images/products/haier-jade-plus-gallery-5.jpg", alt: "Haier Jade Plus — filtracja" },
      { src: "/images/products/haier-jade-plus-gallery-6.jpg", alt: "Haier Jade Plus — montaż" },
      { src: "/images/products/haier-jade-plus-gallery-7.jpg", alt: "Haier Jade Plus — wymiennik" },
      { src: "/images/products/haier-jade-plus-gallery-8.jpg", alt: "Haier Jade Plus — wnętrze jednostki" },
      { src: "/images/products/haier-jade-plus-gallery-9.jpg", alt: "Haier Jade Plus — czujniki" },
      { src: "/images/products/haier-jade-plus-gallery-10.jpg", alt: "Haier Jade Plus — pilot" },
      { src: "/images/products/haier-jade-plus-gallery-11.jpg", alt: "Haier Jade Plus — jednostka zewnętrzna" },
      { src: "/images/products/haier-jade-plus-gallery-12.jpg", alt: "Haier Jade Plus — instalacja" },
    ],
  },
  {
    slug: "haier-expert-plus",
    name: "Haier Expert Plus",
    brand: "haier",
    category: "scienny",
    tagline: "Cicha praca od 16 dB, sterylizacja UV-C Pro i klasa A+++ z 5-letnią gwarancją",
    origin: "Haier (Chiny)",
    description:
      "Haier Expert Plus to nowoczesny klimatyzator ścienny, który dzięki zastosowaniu technologii inwerterowej osiąga bardzo wysoką klasę energetyczną A+++ w trybie chłodzenia i A++ w trybie grzania. Urządzenie sprawdza się zarówno w upalne dni latem, jak i w chłodniejsze dni w okresie przejściowym. Zastosowane w nim funkcje sterylizacji UV-C Pro oraz 56°C Steri Clean zapewniają czyste powietrze wylotowe. Klimatyzator pracuje na czynniku chłodniczym R32, co czyni go niemal obojętnym dla środowiska naturalnego i znacznie wydajniejszym niż rozwiązania z czynnikiem R410. Klimatyzator Haier Expert Plus cechuje elegancka biała obudowa, która doskonale wpisuje się w większość nowoczesnych aranżacji i nie dominuje swoją obecnością w pomieszczeniu. Warto podkreślić, że urządzenie jest niemal niesłyszalne — pracuje już od 16 dB(A). Dzięki temu może być stosowane również w sypialniach czy miejscach pracy. Producent zadbał o komfort użytkownika, wyposażył klimatyzator w czujnik ECO i regulację żaluzji 3D, które w połączeniu z funkcją Coanda Plus zapewniają optymalne rozprowadzanie powietrza w pomieszczeniu. Dodatkowo klimatyzacja jest wyposażona w wbudowany moduł Wi-Fi, umożliwiający zdalne sterowanie. Całość objęta jest aż 5-letnią gwarancją producenta.",
    descriptionLong: [
      "Haier Expert Plus to nowoczesny klimatyzator ścienny, który dzięki zastosowaniu technologii inwerterowej osiąga bardzo wysoką klasę energetyczną A+++ w trybie chłodzenia i A++ w trybie grzania.",
      "Zastosowane w nim funkcje sterylizacji UV-C Pro oraz 56°C Steri Clean zapewniają czyste powietrze wylotowe. Klimatyzator pracuje na czynniku chłodniczym R32, co czyni go niemal obojętnym dla środowiska naturalnego.",
      "Urządzenie jest niemal niesłyszalne — pracuje już od 16 dB(A). Dzięki temu może być stosowane również w sypialniach czy miejscach pracy.",
      "Producent zadbał o komfort użytkownika, wyposażył klimatyzator w czujnik ECO i regulację żaluzji 3D, które w połączeniu z funkcją Coanda Plus zapewniają optymalne rozprowadzanie powietrza. Całość objęta jest aż 5-letnią gwarancją producenta.",
    ],
    highlight: "Od 16 dB + UV-C Pro",
    features: [
      "Klasa energetyczna A+++ (chłodzenie) / A++ (grzanie)",
      "Cicha praca od 16 dB(A)",
      "Sterylizacja UV-C Pro",
      "Funkcja 56°C Steri Clean",
      "Technologia Coanda Plus",
      "Czujnik ECO",
      "Regulacja żaluzji 3D",
      "Moduł Wi-Fi w standardzie",
      "Ekologiczny czynnik R32",
      "Konstrukcja rurowa 2-drogowa",
      "Gwarancja 5 lat",
      "Automatyczny restart",
      "Autodiagnostyka",
      "Chłodzenie do -10°C",
      "Ciepły start",
      "Grzanie do -20°C",
      "Inteligentne odszranianie",
      "Karta On/Off",
      "Tryb komfortowego snu",
      "Sterowanie przewodowe (opcja)",
      "Tryb Turbo Cooling",
      "Wyświetlacz LED",
    ],
    advantages: [
      { title: "Od 16 dB", desc: "Niemal niesłyszalna praca — idealna do sypialni i biur", icon: "volume-low" },
      { title: "UV-C Pro", desc: "Sterylizacja powietrza eliminująca bakterie i wirusy", icon: "sun-03" },
      { title: "Coanda Plus", desc: "Silniejszy nawiew docierający do każdej części pomieszczenia", icon: "energy" },
      { title: "5 lat gwarancji", desc: "Długa gwarancja producenta zapewniająca spokój użytkownika", icon: "shield-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 16 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Expert Plus 2,8 kW", power: "2,8 kW", energyClass: "A+++/A++", noise: "16 dB", phase: "230V", price: 5918, area: "20–30 m²" },
      { name: "Expert Plus 3,5 kW", power: "3,5 kW", energyClass: "A+++/A++", noise: "16 dB", phase: "230V", price: 6089, area: "30–40 m²" },
      { name: "Expert Plus 5,0 kW", power: "5,0 kW", energyClass: "A+++/A++", noise: "16 dB", phase: "230V", price: 7345, area: "40–60 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,8 – 5,0 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/haier-expert-plus.png",
    imageAlt: "Klimatyzator ścienny Haier Expert Plus",
    gallery: [
      { src: "/images/products/haier-expert-plus-gallery-0.jpg", alt: "Haier Expert Plus — widok z przodu" },
      { src: "/images/products/haier-expert-plus-gallery-1.jpg", alt: "Haier Expert Plus — widok z boku" },
      { src: "/images/products/haier-expert-plus-gallery-2.jpg", alt: "Haier Expert Plus — panel" },
      { src: "/images/products/haier-expert-plus-gallery-3.jpg", alt: "Haier Expert Plus — nawiew" },
      { src: "/images/products/haier-expert-plus-gallery-4.jpg", alt: "Haier Expert Plus — szczegóły" },
      { src: "/images/products/haier-expert-plus-gallery-5.webp", alt: "Haier Expert Plus — utrzymanie temperatury +10°C" },
    ],
  },
  {
    slug: "haier-arctic-expert-plus",
    name: "Haier Arctic Expert Plus",
    brand: "haier",
    category: "scienny",
    tagline: "Grzanie do -30°C z UV-C Pro, Coanda Plus i klasą A+++ w chłodzeniu",
    origin: "Haier (Chiny)",
    description:
      "Haier Arctic Expert Plus — klimatyzator ścienny do ogrzewania — to nowość na sezon 2023 od lidera branży klimatyzacyjnej. Dzięki specjalnej konstrukcji grzałki tacy ociekowej, urządzenie jest w stanie zapewnić ciepło nawet w temperaturach sięgających -30°C. Dodatkowo, funkcja sterylizacji UV-C Pro dezynfekuje powietrze, a opcja 56°C Steri Clean skutecznie eliminuje bakterie i wirusy. Dzięki technologii Coanda Plus, nawiew z klimatyzatora jest silniejszy i osiąga większy zasięg, dotykając każdą część pomieszczenia. Klimatyzator Haier Arctic Expert Plus zapewnia niezwykle cichą pracę zarówno jednostki wewnętrznej, jak i zewnętrznej. Dzięki zastosowaniu technologii inwerterowej, urządzenie osiąga bardzo wysoką klasę energetyczną A+++ w trybie chłodzenia oraz A++ w trybie grzania. Wbudowany moduł Wi-Fi umożliwia sterowanie klimatyzatorem za pomocą dowolnego urządzenia mobilnego. Dodatkowo, kompaktowa konstrukcja klimatyzatora ułatwia jego demontaż i czyszczenie. Producent wyposażył urządzenie w czujnik temperatury w pilocie oraz czujnik ruchu, co dodatkowo podnosi jego funkcjonalność.",
    descriptionLong: [
      "Haier Arctic Expert Plus — klimatyzator ścienny do ogrzewania — to nowość na sezon 2023 od lidera branży klimatyzacyjnej. Dzięki specjalnej konstrukcji grzałki tacy ociekowej, urządzenie jest w stanie zapewnić ciepło nawet w temperaturach sięgających -30°C.",
      "Funkcja sterylizacji UV-C Pro dezynfekuje powietrze, a opcja 56°C Steri Clean skutecznie eliminuje bakterie i wirusy. Dzięki technologii Coanda Plus, nawiew z klimatyzatora jest silniejszy i osiąga większy zasięg.",
      "Klimatyzator zapewnia niezwykle cichą pracę zarówno jednostki wewnętrznej, jak i zewnętrznej. Dzięki zastosowaniu technologii inwerterowej osiąga klasę energetyczną A+++ w trybie chłodzenia oraz A++ w trybie grzania.",
      "Wbudowany moduł Wi-Fi umożliwia sterowanie za pomocą dowolnego urządzenia mobilnego. Kompaktowa konstrukcja ułatwia demontaż i czyszczenie, a czujnik temperatury w pilocie oraz czujnik ruchu podnoszą funkcjonalność.",
    ],
    highlight: "Grzanie do -30°C",
    features: [
      "Grzanie do -30°C dzięki specjalnej konstrukcji grzałki tacy ociekowej",
      "Klasa energetyczna A+++ (chłodzenie) / A++ (grzanie)",
      "Sterylizacja UV-C Pro",
      "Funkcja 56°C Steri Clean",
      "Technologia Coanda Plus",
      "Moduł Wi-Fi w standardzie",
      "Czujnik temperatury w pilocie",
      "Czujnik ruchu",
      "Kompaktowa konstrukcja — łatwy demontaż i czyszczenie",
      "Cicha praca od 18 dB",
      "Ekologiczny czynnik chłodniczy R32",
      "Gwarancja 5 lat",
      "Automatyczny restart",
      "Autodiagnostyka",
      "Inteligentne odszranianie",
    ],
    advantages: [
      { title: "Grzanie -30°C", desc: "Specjalna konstrukcja grzałki zapewnia ciepło nawet przy ekstremalnych mrozach", icon: "thermometer-01" },
      { title: "UV-C Pro", desc: "Sterylizacja powietrza eliminująca bakterie i wirusy", icon: "sun-03" },
      { title: "Coanda Plus", desc: "Silniejszy nawiew o większym zasięgu docierający do każdej części pomieszczenia", icon: "energy" },
      { title: "Czujnik ruchu", desc: "Automatyczna regulacja pracy na podstawie obecności osób w pomieszczeniu", icon: "motion-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 18 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Arctic Expert Plus 2,6 kW", power: "2,6 kW", energyClass: "A+++/A++", noise: "18 dB", phase: "230V", price: 6700, area: "20–30 m²" },
      { name: "Arctic Expert Plus 3,5 kW", power: "3,5 kW", energyClass: "A+++/A++", noise: "18 dB", phase: "230V", price: 7050, area: "30–40 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 3,5 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/haier-arctic-expert-plus.png",
    imageAlt: "Klimatyzator ścienny Haier Arctic Expert Plus",
    gallery: [
      { src: "/images/products/haier-arctic-expert-plus-gallery-0.jpg", alt: "Haier Arctic Expert Plus — widok z przodu" },
      { src: "/images/products/haier-arctic-expert-plus-gallery-1.jpg", alt: "Haier Arctic Expert Plus — widok z boku" },
      { src: "/images/products/haier-arctic-expert-plus-gallery-2.jpg", alt: "Haier Arctic Expert Plus — panel" },
      { src: "/images/products/haier-arctic-expert-plus-gallery-3.jpg", alt: "Haier Arctic Expert Plus — nawiew" },
      { src: "/images/products/haier-arctic-expert-plus-gallery-4.jpg", alt: "Haier Arctic Expert Plus — szczegóły" },
      { src: "/images/products/haier-arctic-expert-plus-gallery-5.webp", alt: "Haier Arctic Expert Plus — utrzymanie temperatury +10°C" },
    ],
  },
  {
    slug: "haier-revive-plus",
    name: "Haier Revive Plus",
    brand: "haier",
    category: "scienny",
    tagline: "Nowość 2024 — świetny stosunek jakości do ceny z WiFi i nawiewem 3D",
    origin: "Haier (Chiny)",
    description:
      "Klimatyzator ścienny Haier Revive Plus jest nowością producenta na sezon 2024 oferujący bardzo dobry stosunek jakości do ceny. Produkt jest energooszczędny, czego dowodem jest klasa energetyczna A++ dla chłodzenia oraz A+ dla grzania. Klimatyzator cechuje się wysoką kulturą pracy — jednakowo jednostka wewnętrzna oraz zewnętrzna są bardzo ciche (głośność 19 dB / 49 dB). Producent w standardzie wyposażył swój model w moduł Wi-Fi umożliwiający zdalną kontrolę przez aplikację mobilną. Klimatyzacja posiada przepływ powietrza 3D, czyli żaluzje z możliwością sterowania w poziomie oraz pionie. Haier Revive Plus został wyposażony w praktyczną funkcję samoczyszczenia (Self Clean) oraz w czujnik w pilocie pozwalający na kontrolę poziomu temperatury powietrza. Warto również zaznaczyć obecność funkcji podtrzymującej temperaturę, która nie dopuszcza do zbytnego wyziębienia pomieszczeń. Model do swojej pracy wykorzystuje bardzo ekologiczny czynnik chłodniczy R32, który jest również niezwykle wydajnym gazem do instalacji klimatyzacyjnej.",
    descriptionLong: [
      "Klimatyzator ścienny Haier Revive Plus jest nowością producenta na sezon 2024 oferujący bardzo dobry stosunek jakości do ceny. Produkt jest energooszczędny, czego dowodem jest klasa energetyczna A++ dla chłodzenia oraz A+ dla grzania.",
      "Klimatyzator cechuje się wysoką kulturą pracy — jednakowo jednostka wewnętrzna oraz zewnętrzna są bardzo ciche (głośność 19 dB / 49 dB). Producent w standardzie wyposażył swój model w moduł Wi-Fi umożliwiający zdalną kontrolę przez aplikację mobilną.",
      "Klimatyzacja posiada przepływ powietrza 3D, czyli żaluzje z możliwością sterowania w poziomie oraz pionie. Haier Revive Plus został wyposażony w praktyczną funkcję samoczyszczenia (Self Clean) oraz w czujnik w pilocie pozwalający na kontrolę poziomu temperatury powietrza.",
      "Warto również zaznaczyć obecność funkcji podtrzymującej temperaturę, która nie dopuszcza do zbytnego wyziębienia pomieszczeń. Model do swojej pracy wykorzystuje bardzo ekologiczny czynnik chłodniczy R32.",
    ],
    highlight: "Najlepsza cena w ofercie",
    features: [
      "Klasa energetyczna A++ (chłodzenie) / A+ (grzanie)",
      "Cicha praca od 19 dB (jednostka wewnętrzna)",
      "Moduł Wi-Fi w standardzie",
      "Przepływ powietrza 3D — żaluzje sterowane w poziomie i pionie",
      "Funkcja samoczyszczenia Self Clean",
      "Czujnik temperatury w pilocie",
      "Funkcja podtrzymania temperatury",
      "Ekologiczny czynnik chłodniczy R32",
      "Bardzo dobry stosunek jakości do ceny",
      "Cicha jednostka zewnętrzna (49 dB)",
      "Sterowanie przez aplikację mobilną",
      "Gwarancja 5 lat",
    ],
    advantages: [
      { title: "Najlepsza cena", desc: "Bardzo dobry stosunek jakości do ceny w ofercie Haier", icon: "money-bag-02" },
      { title: "Nawiew 3D", desc: "Żaluzje sterowane w poziomie i pionie dla optymalnego rozprowadzania powietrza", icon: "energy" },
      { title: "Self Clean", desc: "Funkcja samoczyszczenia zapewniająca higieniczną pracę urządzenia", icon: "shield-02" },
      { title: "WiFi", desc: "Zdalna kontrola przez aplikację mobilną w standardzie", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (aplikacja)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Revive Plus 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 3130, area: "20–30 m²" },
      { name: "Revive Plus 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 3240, area: "40–50 m²" },
      { name: "Revive Plus 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 4320, area: "40–60 m²" },
      { name: "Revive Plus 6,2 kW", power: "6,2 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 5670, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,2 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/haier-revive-plus.png",
    imageAlt: "Klimatyzator ścienny Haier Revive Plus",
    gallery: [
      { src: "/images/products/haier-revive-plus-gallery-0.png", alt: "Haier Revive Plus — widok z przodu" },
      { src: "/images/products/haier-revive-plus-gallery-1.png", alt: "Haier Revive Plus — widok z boku" },
      { src: "/images/products/haier-revive-plus-gallery-2.png", alt: "Haier Revive Plus — szczegóły" },
      { src: "/images/products/haier-revive-plus-gallery-3.png", alt: "Haier Revive Plus — nawiew" },
      { src: "/images/products/haier-revive-plus-gallery-4.png", alt: "Haier Revive Plus — jednostka zewnętrzna" },
    ],
  },
  {
    slug: "haier-flexis-plus-white-matt-2",
    name: "Haier Flexis Plus White Matt",
    brand: "haier",
    category: "scienny",
    tagline: "Ultranowoczesny klimatyzator A+++ z UV-C Pro, Coanda Plus i czujnikiem ruchu",
    origin: "Haier (Chiny)",
    description:
      "Haier Flexis Plus White Matt to ultranowoczesny klimatyzator ścienny, który dzięki technologii inwerterowej osiąga bardzo wysoką klasę energetyczną A+++ w trybie chłodzenia oraz A++ w trybie grzania. Urządzenie wyposażone jest w sterylizację UV-C Pro oraz funkcję 56°C Steri Clean, które skutecznie eliminują bakterie i wirusy z powietrza. Technologia Coanda Plus zapewnia silniejszy nawiew o większym zasięgu, docierający do każdej części pomieszczenia. Kompaktowa konstrukcja ułatwia demontaż i czyszczenie, a wbudowany moduł Wi-Fi umożliwia sterowanie za pomocą dowolnego urządzenia mobilnego. Czujnik temperatury w pilocie oraz czujnik ruchu dodatkowo podnoszą funkcjonalność urządzenia.",
    descriptionLong: [
      "Haier Flexis Plus White Matt to ultranowoczesny klimatyzator ścienny, który dzięki technologii inwerterowej osiąga bardzo wysoką klasę energetyczną A+++ w trybie chłodzenia oraz A++ w trybie grzania.",
      "Urządzenie wyposażone jest w sterylizację UV-C Pro oraz funkcję 56°C Steri Clean, które skutecznie eliminują bakterie i wirusy z powietrza.",
      "Technologia Coanda Plus zapewnia silniejszy nawiew o większym zasięgu, docierający do każdej części pomieszczenia. Kompaktowa konstrukcja ułatwia demontaż i czyszczenie.",
      "Wbudowany moduł Wi-Fi umożliwia sterowanie za pomocą dowolnego urządzenia mobilnego. Czujnik temperatury w pilocie oraz czujnik ruchu dodatkowo podnoszą funkcjonalność urządzenia.",
    ],
    highlight: "UV-C Pro + Coanda Plus",
    features: [
      "Klasa energetyczna A+++ (chłodzenie) / A++ (grzanie)",
      "Sterylizacja UV-C Pro",
      "Funkcja 56°C Steri Clean",
      "Technologia Coanda Plus",
      "Moduł Wi-Fi w standardzie",
      "Czujnik temperatury w pilocie",
      "Czujnik ruchu",
      "Kompaktowa konstrukcja — łatwy demontaż i czyszczenie",
      "Cicha praca od 18 dB",
      "Ekologiczny czynnik chłodniczy R32",
      "Automatyczne sterowanie nawiewem 3D",
      "Gwarancja 5 lat",
    ],
    advantages: [
      { title: "UV-C Pro", desc: "Sterylizacja powietrza eliminująca bakterie i wirusy", icon: "sun-03" },
      { title: "Coanda Plus", desc: "Silniejszy nawiew o większym zasięgu w całym pomieszczeniu", icon: "energy" },
      { title: "Czujnik ruchu", desc: "Automatyczna regulacja pracy na podstawie obecności osób", icon: "motion-01" },
      { title: "A+++", desc: "Najwyższa klasa energetyczna w chłodzeniu obniżająca koszty eksploatacji", icon: "tick-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 18 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Flexis Plus White Matt 2,6 kW", power: "2,6 kW", energyClass: "A+++/A++", noise: "18 dB", phase: "230V", price: 4690, area: "20–30 m²" },
      { name: "Flexis Plus White Matt 3,5 kW", power: "3,5 kW", energyClass: "A+++/A++", noise: "18 dB", phase: "230V", price: 5160, area: "30–40 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 3,5 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/haier-flexis-plus-white-matt-2.jpg",
    imageAlt: "Klimatyzator ścienny Haier Flexis Plus White Matt",
    gallery: [
      { src: "/images/products/haier-flexis-plus-white-matt-2-gallery-0.webp", alt: "Haier Flexis Plus White Matt — utrzymanie temperatury +10°C" },
      { src: "/images/products/haier-flexis-plus-white-matt-2-gallery-1.webp", alt: "Haier Flexis Plus White Matt — automatyczne sterowanie nawiewem 3D" },
      { src: "/images/products/haier-flexis-plus-white-matt-2-gallery-2.jpg", alt: "Haier Flexis Plus White Matt — widok z boku" },
      { src: "/images/products/haier-flexis-plus-white-matt-2-gallery-3.jpg", alt: "Haier Flexis Plus White Matt — widok z przodu" },
      { src: "/images/products/haier-flexis-plus-white-matt-2-gallery-4.jpg", alt: "Haier Flexis Plus White Matt — szczegóły" },
      { src: "/images/products/haier-flexis-plus-white-matt-2-gallery-5.jpg", alt: "Haier Flexis Plus White Matt — panel" },
      { src: "/images/products/haier-flexis-plus-white-matt-2-gallery-6.jpg", alt: "Haier Flexis Plus White Matt — widok dolny" },
      { src: "/images/products/haier-flexis-plus-white-matt-2-gallery-7.jpg", alt: "Haier Flexis Plus White Matt — montaż" },
      { src: "/images/products/haier-flexis-plus-white-matt-2-gallery-8.jpg", alt: "Haier Flexis Plus White Matt — wnętrze" },
    ],
  },
];
