import type { Product } from "@/types";

// ═══════════════════════════════════════════════════════════════
// Gree products — converted from pbac source data
// 12 products: Pular Matt (x2), Clivia Silver/Navy Blue/White,
// Amber Standard Silver, Amber Prestige, Fairy White/Silver/Dark,
// Lomo Luxury Plus, Soyal
// Converted: 2026-03-17
// ═══════════════════════════════════════════════════════════════

export const greeProducts: Product[] = [
  // ═══════════════════════════════════════════════
  // Gree (12 products)
  // ═══════════════════════════════════════════════
  {
    slug: "gree-pular-matt",
    name: "Gree Pular Matt",
    brand: "gree",
    category: "scienny",
    tagline: "Klimatyzator ścienny o niewielkich rozmiarach i sporych możliwościach",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Gree Pular Matt to klimatyzator ścienny o niewielkich rozmiarach i sporych możliwościach. Pod stylowym matowym panelem kryje się wiele przydatnych, innowacyjnych technologii, które pozytywnie wpływają na efektywność, żywotność i energooszczędność urządzenia. Minimalistyczny wygląd sprawia, że sprzęt będzie dobrze wyglądał zarówno w klasycznie urządzonych pomieszczeniach, jak i w przestrzeniach w loftowym stylu.",
    descriptionLong: [
      "Gree Pular Matt to klimatyzator ścienny o niewielkich rozmiarach i sporych możliwościach. Pod stylowym matowym panelem kryje się wiele przydatnych, innowacyjnych technologii, które pozytywnie wpływają na efektywność, żywotność i energooszczędność urządzenia. Minimalistyczny wygląd sprawia, że sprzęt będzie dobrze wyglądał zarówno w klasycznie urządzonych pomieszczeniach, jak i w przestrzeniach w loftowym stylu.",
      "Klimatyzator Gree Pular Matt charakteryzuje się klasą energetyczną A++ w przypadku chłodzenia oraz A+ w ramach grzania. Za tym stanem rzeczy stoi zastosowanie inwertera z mikroprocesorowym sterowaniem i unikalnym układem zasilania. Wykorzystano także czynnik chłodniczy R32, który charakteryzuje się dużą wydajnością i niską szkodliwością na środowisko. Energooszczędność i ekologia jednak nie przeszkodziły producentowi w wyposażenie sprzętu w ogrom przydatnych funkcji.",
    ],
    highlight: "Matowy design i inwerter",
    features: [
      "Matowy panel o minimalistycznym designie",
      "Technologia inwerterowa z mikroprocesorowym sterowaniem",
      "Czynnik chłodniczy R32",
      "Sterowanie Wi-Fi przez aplikację",
      "Funkcja grzania i chłodzenia",
      "Jonizator powietrza",
      "Tryb cichy pracy",
      "7 biegów wentylatora",
    ],
    advantages: [
      { title: "Energooszczędność", desc: "Klasa A++ dla chłodzenia dzięki technologii inwerterowej i czynnikowi R32", icon: "energy" },
      { title: "Minimalistyczny design", desc: "Matowy panel pasujący do klasycznych i loftowych wnętrz", icon: "paint-board" },
      { title: "Sterowanie Wi-Fi", desc: "Wygodne sterowanie klimatyzatorem z poziomu smartfona", icon: "wifi-full-signal" },
      { title: "Ekologia", desc: "Czynnik chłodniczy R32 o niskim wpływie na środowisko", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "24–41 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Pular Matt 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 3240, area: "20–30 m²" },
      { name: "Pular Matt 3,2 kW", power: "3,2 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 3400, area: "30–40 m²" },
      { name: "Pular Matt 4,6 kW", power: "4,6 kW", energyClass: "A++/A+", noise: "34 dB", phase: "230V", price: 4430, area: "40–60 m²" },
      { name: "Pular Matt 6,2 kW", power: "6,2 kW", energyClass: "A++/A+", noise: "41 dB", phase: "230V", price: 5780, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,2 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-pular-matt-gree-pular-1645080452.png",
    imageAlt: "Klimatyzator Gree Pular Matt",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-pular-matt-gree-pular-1645080452.png",
        alt: "Gree Pular Matt - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-pular-matt-13211.jpg",
        alt: "Gree Pular Matt - jednostka zewnętrzna",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-pular-matt-13213.jpg",
        alt: "Gree Pular Matt - pilot zdalnego sterowania",
      },
    ],
  },
  {
    slug: "gree-pular-matt-2",
    name: "Gree Pular Matt",
    brand: "gree",
    category: "scienny",
    tagline: "Klimatyzator ścienny o niewielkich rozmiarach i sporych możliwościach",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Gree Pular Matt to klimatyzator ścienny o niewielkich rozmiarach i sporych możliwościach. Pod stylowym matowym panelem kryje się wiele przydatnych, innowacyjnych technologii, które pozytywnie wpływają na efektywność, żywotność i energooszczędność urządzenia.",
    descriptionLong: [
      "Gree Pular Matt to klimatyzator ścienny o niewielkich rozmiarach i sporych możliwościach. Pod stylowym matowym panelem kryje się wiele przydatnych, innowacyjnych technologii, które pozytywnie wpływają na efektywność, żywotność i energooszczędność urządzenia. Minimalistyczny wygląd sprawia, że sprzęt będzie dobrze wyglądał zarówno w klasycznie urządzonych pomieszczeniach, jak i w przestrzeniach w loftowym stylu.",
      "Klimatyzator Gree Pular Matt charakteryzuje się klasą energetyczną A++ w przypadku chłodzenia oraz A+ w ramach grzania. Za tym stanem rzeczy stoi zastosowanie inwertera z mikroprocesorowym sterowaniem i unikalnym układem zasilania. Wykorzystano także czynnik chłodniczy R32, który charakteryzuje się dużą wydajnością i niską szkodliwością na środowisko.",
    ],
    highlight: "Matowy design i inwerter",
    features: [
      "Matowy panel o minimalistycznym designie",
      "Technologia inwerterowa z mikroprocesorowym sterowaniem",
      "Czynnik chłodniczy R32",
      "Sterowanie Wi-Fi przez aplikację",
      "Funkcja grzania i chłodzenia",
      "Jonizator powietrza",
      "Tryb cichy pracy",
      "7 biegów wentylatora",
    ],
    advantages: [
      { title: "Energooszczędność", desc: "Klasa A++ dla chłodzenia dzięki technologii inwerterowej i czynnikowi R32", icon: "energy" },
      { title: "Minimalistyczny design", desc: "Matowy panel pasujący do klasycznych i loftowych wnętrz", icon: "paint-board" },
      { title: "Sterowanie Wi-Fi", desc: "Wygodne sterowanie klimatyzatorem z poziomu smartfona", icon: "wifi-full-signal" },
      { title: "Ekologia", desc: "Czynnik chłodniczy R32 o niskim wpływie na środowisko", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "24–41 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Pular Matt 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 3240, area: "20–30 m²" },
      { name: "Pular Matt 3,2 kW", power: "3,2 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 3400, area: "30–40 m²" },
      { name: "Pular Matt 4,6 kW", power: "4,6 kW", energyClass: "A++/A+", noise: "34 dB", phase: "230V", price: 4430, area: "40–60 m²" },
      { name: "Pular Matt 6,2 kW", power: "6,2 kW", energyClass: "A++/A+", noise: "41 dB", phase: "230V", price: 5780, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,2 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-pular-matt-gree-pular-1645080452.png",
    imageAlt: "Klimatyzator Gree Pular Matt",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-pular-matt-gree-pular-1645080452.png",
        alt: "Gree Pular Matt - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-pular-matt-13211.jpg",
        alt: "Gree Pular Matt - jednostka zewnętrzna",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-pular-matt-13213.jpg",
        alt: "Gree Pular Matt - pilot zdalnego sterowania",
      },
    ],
  },
  {
    slug: "gree-clivia-silver",
    name: "Gree Clivia Silver",
    brand: "gree",
    category: "scienny",
    tagline: "Komfortowe życie dzięki inteligencji — klimatyzator z wbudowaną sztuczną inteligencją",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Innowacyjny klimatyzator Gree Clivia Silver: komfortowe życie dzięki inteligencji. Gree Clivia to rewolucyjna propozycja wśród klimatyzatorów. Zintegrowana sztuczna inteligencja zapewnia nie tylko innowacyjne funkcje i możliwości, ale także dostosowuje urządzenie do potrzeb użytkowników, tworząc przy tym komfortowe warunki życia.",
    descriptionLong: [
      "Innowacyjny klimatyzator Gree Clivia Silver: komfortowe życie dzięki inteligencji. Gree Clivia to rewolucyjna propozycja wśród klimatyzatorów. Zintegrowana sztuczna inteligencja zapewnia nie tylko innowacyjne funkcje i możliwości, ale także dostosowuje urządzenie do potrzeb użytkowników, tworząc przy tym komfortowe warunki życia.",
      "Klimatyzator Gree Clivia Silver to nie tylko innowacyjny klimatyzator, ale także gwarancja komfortu i zdrowego powietrza. Oprócz regulacji wilgotności w pomieszczeniu, oszczędności energii i inteligentnego działania, Gree Clivia wyposażony został w technologię LED UV, eliminującą drobnoustroje z otoczenia. Dodatkowo nocny tryb cichej pracy jednostki zewnętrznej zapewnia spokój i harmonię dla wszystkich mieszkańców.",
    ],
    highlight: "AI i LED UV",
    features: [
      "Zintegrowana sztuczna inteligencja AI",
      "Technologia LED UV eliminująca drobnoustroje",
      "Regulacja wilgotności powietrza",
      "Nocny tryb cichej pracy jednostki zewnętrznej",
      "Sterowanie Wi-Fi przez aplikację",
      "Srebrna elegancka obudowa",
      "Klasa energetyczna A+++ (chłodzenie) / A++ (grzanie)",
      "Czynnik chłodniczy R32",
    ],
    advantages: [
      { title: "Sztuczna inteligencja", desc: "Zintegrowana AI dostosowuje urządzenie do potrzeb użytkowników automatycznie", icon: "ai-brain-04" },
      { title: "Technologia LED UV", desc: "Eliminacja drobnoustrojów z otoczenia dzięki promieniowaniu UV", icon: "sun-03" },
      { title: "Najwyższa efektywność", desc: "Klasa energetyczna A+++ dla chłodzenia zapewnia minimalne zużycie energii", icon: "energy" },
      { title: "Cichy tryb nocny", desc: "Nocny tryb cichej pracy jednostki zewnętrznej — spokój dla mieszkańców", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "22–38 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Clivia Silver 2,7 kW", power: "2,7 kW", energyClass: "A+++/A++", noise: "22 dB", phase: "230V", price: 5162, area: "20–30 m²" },
      { name: "Clivia Silver 3,51 kW", power: "3,51 kW", energyClass: "A+++/A++", noise: "26 dB", phase: "230V", price: 5320, area: "30–40 m²" },
      { name: "Clivia Silver 5,3 kW", power: "5,3 kW", energyClass: "A+++/A++", noise: "32 dB", phase: "230V", price: 7080, area: "40–60 m²" },
      { name: "Clivia Silver 7,1 kW", power: "7,1 kW", energyClass: "A+++/A++", noise: "38 dB", phase: "230V", price: 7660, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,1 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-silver-imageid.webp",
    imageAlt: "Klimatyzator Gree Clivia Silver",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-silver-imageid.webp",
        alt: "Gree Clivia Silver - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-silver-gree-clivia-silver-17446.jpg",
        alt: "Gree Clivia Silver - perspektywa",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-silver-gree-clivia-silver-7.webp",
        alt: "Gree Clivia Silver - detal",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-silver-gree-clivia-silver-6.webp",
        alt: "Gree Clivia Silver - widok boczny",
      },
    ],
  },
  {
    slug: "gree-clivia-navy-blue",
    name: "Gree Clivia Navy Blue",
    brand: "gree",
    category: "scienny",
    tagline: "Komfortowe życie dzięki inteligencji — klimatyzator w odważnym granatowym kolorze",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Innowacyjny klimatyzator Gree Clivia Navy Blue: komfortowe życie dzięki inteligencji. Gree Clivia to rewolucyjna propozycja wśród klimatyzatorów. Zintegrowana sztuczna inteligencja zapewnia nie tylko innowacyjne funkcje i możliwości, ale także dostosowuje urządzenie do potrzeb użytkowników, tworząc przy tym komfortowe warunki życia.",
    descriptionLong: [
      "Innowacyjny klimatyzator Gree Clivia Navy Blue: komfortowe życie dzięki inteligencji. Gree Clivia to rewolucyjna propozycja wśród klimatyzatorów. Zintegrowana sztuczna inteligencja zapewnia nie tylko innowacyjne funkcje i możliwości, ale także dostosowuje urządzenie do potrzeb użytkowników, tworząc przy tym komfortowe warunki życia.",
      "Klimatyzator Gree Clivia Navy Blue to nie tylko innowacyjny klimatyzator, ale także gwarancja komfortu i zdrowego powietrza. Oprócz regulacji wilgotności w pomieszczeniu, oszczędności energii i inteligentnego działania, Gree Clivia wyposażony został w technologię LED UV, eliminującą drobnoustroje z otoczenia. Dodatkowo nocny tryb cichej pracy jednostki zewnętrznej zapewnia spokój i harmonię dla wszystkich mieszkańców.",
    ],
    highlight: "AI i granatowy design",
    features: [
      "Zintegrowana sztuczna inteligencja AI",
      "Technologia LED UV eliminująca drobnoustroje",
      "Regulacja wilgotności powietrza",
      "Nocny tryb cichej pracy jednostki zewnętrznej",
      "Sterowanie Wi-Fi przez aplikację",
      "Granatowa elegancka obudowa Navy Blue",
      "Klasa energetyczna A+++ (chłodzenie) / A++ (grzanie)",
      "Czynnik chłodniczy R32",
    ],
    advantages: [
      { title: "Sztuczna inteligencja", desc: "Zintegrowana AI dostosowuje urządzenie do potrzeb użytkowników automatycznie", icon: "ai-brain-04" },
      { title: "Technologia LED UV", desc: "Eliminacja drobnoustrojów z otoczenia dzięki promieniowaniu UV", icon: "sun-03" },
      { title: "Odważny design", desc: "Granatowa obudowa Navy Blue — unikatowy akcent we wnętrzu", icon: "paint-board" },
      { title: "Cichy tryb nocny", desc: "Nocny tryb cichej pracy jednostki zewnętrznej — spokój dla mieszkańców", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "22–38 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Clivia Navy Blue 2,7 kW", power: "2,7 kW", energyClass: "A+++/A++", noise: "22 dB", phase: "230V", price: 5162, area: "20–30 m²" },
      { name: "Clivia Navy Blue 3,51 kW", power: "3,51 kW", energyClass: "A+++/A++", noise: "26 dB", phase: "230V", price: 5320, area: "30–40 m²" },
      { name: "Clivia Navy Blue 5,3 kW", power: "5,3 kW", energyClass: "A+++/A++", noise: "32 dB", phase: "230V", price: 7080, area: "40–60 m²" },
      { name: "Clivia Navy Blue 7,1 kW", power: "7,1 kW", energyClass: "A+++/A++", noise: "38 dB", phase: "230V", price: 7660, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,1 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-navy-blue-imageid.webp",
    imageAlt: "Klimatyzator Gree Clivia Navy Blue",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-navy-blue-imageid.webp",
        alt: "Gree Clivia Navy Blue - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-navy-blue-gree-clivia-navy-blue-17427.jpg",
        alt: "Gree Clivia Navy Blue - perspektywa",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-navy-blue-gree-clivia-navy-blue-1.webp",
        alt: "Gree Clivia Navy Blue - detal",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-navy-blue-gree-clivia-navy-blue-2.webp",
        alt: "Gree Clivia Navy Blue - widok boczny",
      },
    ],
  },
  {
    slug: "gree-clivia-white",
    name: "Gree Clivia White",
    brand: "gree",
    category: "scienny",
    tagline: "Komfortowe życie dzięki inteligencji — klasyczna biel z technologią AI",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Innowacyjny klimatyzator Gree Clivia White: komfortowe życie dzięki inteligencji. Gree Clivia White to rewolucyjna propozycja wśród klimatyzatorów. Zintegrowana sztuczna inteligencja zapewnia nie tylko innowacyjne funkcje i możliwości, ale także dostosowuje urządzenie do potrzeb użytkowników, tworząc przy tym komfortowe warunki życia.",
    descriptionLong: [
      "Innowacyjny klimatyzator Gree Clivia White: komfortowe życie dzięki inteligencji. Gree Clivia White to rewolucyjna propozycja wśród klimatyzatorów. Zintegrowana sztuczna inteligencja zapewnia nie tylko innowacyjne funkcje i możliwości, ale także dostosowuje urządzenie do potrzeb użytkowników, tworząc przy tym komfortowe warunki życia.",
      "Klimatyzator Gree Clivia White to nie tylko innowacyjny klimatyzator, ale także gwarancja komfortu i zdrowego powietrza. Oprócz regulacji wilgotności w pomieszczeniu, oszczędności energii i inteligentnego działania, Gree Clivia White wyposażony został w technologię LED UV, eliminującą drobnoustroje z otoczenia. Dodatkowo nocny tryb cichej pracy jednostki zewnętrznej zapewnia spokój i harmonię dla wszystkich mieszkańców.",
    ],
    highlight: "AI i klasyczna biel",
    features: [
      "Zintegrowana sztuczna inteligencja AI",
      "Technologia LED UV eliminująca drobnoustroje",
      "Regulacja wilgotności powietrza",
      "Nocny tryb cichej pracy jednostki zewnętrznej",
      "Sterowanie Wi-Fi przez aplikację",
      "Klasyczna biała obudowa",
      "Klasa energetyczna A+++ (chłodzenie) / A++ (grzanie)",
      "Czynnik chłodniczy R32",
    ],
    advantages: [
      { title: "Sztuczna inteligencja", desc: "Zintegrowana AI dostosowuje urządzenie do potrzeb użytkowników automatycznie", icon: "ai-brain-04" },
      { title: "Technologia LED UV", desc: "Eliminacja drobnoustrojów z otoczenia dzięki promieniowaniu UV", icon: "sun-03" },
      { title: "Najwyższa efektywność", desc: "Klasa energetyczna A+++ dla chłodzenia zapewnia minimalne zużycie energii", icon: "energy" },
      { title: "Cichy tryb nocny", desc: "Nocny tryb cichej pracy jednostki zewnętrznej — spokój dla mieszkańców", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "22–38 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Clivia White 2,7 kW", power: "2,7 kW", energyClass: "A+++/A++", noise: "22 dB", phase: "230V", price: 4310, area: "20–30 m²" },
      { name: "Clivia White 3,51 kW", power: "3,51 kW", energyClass: "A+++/A++", noise: "26 dB", phase: "230V", price: 4525, area: "30–40 m²" },
      { name: "Clivia White 5,3 kW", power: "5,3 kW", energyClass: "A+++/A++", noise: "32 dB", phase: "230V", price: 6685, area: "40–60 m²" },
      { name: "Clivia White 7,1 kW", power: "7,1 kW", energyClass: "A+++/A++", noise: "38 dB", phase: "230V", price: 7440, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,1 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-white-17431.jpg",
    imageAlt: "Klimatyzator Gree Clivia White",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-white-17431.jpg",
        alt: "Gree Clivia White - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-white-gree-clivia-white-klimatyzator-1706282655.png",
        alt: "Gree Clivia White - klimatyzator",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-white-gree-clivia-white-7.webp",
        alt: "Gree Clivia White - detal",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-clivia-white-gree-clivia-white-2.webp",
        alt: "Gree Clivia White - widok boczny",
      },
    ],
  },
  {
    slug: "gree-amber-standard-silver",
    name: "Gree Amber Standard Silver",
    brand: "gree",
    category: "scienny",
    tagline: "Nowoczesne rozwiązanie łączące wysoką wydajność z eleganckim srebrnym wyglądem",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Klimatyzator Gree Amber Standard Silver to nowoczesne rozwiązanie, które doskonale łączy wysoką wydajność z eleganckim wyglądem. Srebrna obudowa sprawia, że urządzenie doskonale wpisuje się zarówno w klasyczne, jak i nowoczesne wnętrza. Dzięki wykorzystaniu czynnika chłodniczego R32 oraz technologii inwerterowej, klimatyzator osiąga najwyższą klasę efektywności energetycznej A+++ dla chłodzenia oraz A++ dla grzania.",
    descriptionLong: [
      "Klimatyzator Gree Amber Standard Silver to nowoczesne rozwiązanie, które doskonale łączy wysoką wydajność z eleganckim wyglądem. Srebrna obudowa sprawia, że urządzenie doskonale wpisuje się zarówno w klasyczne, jak i nowoczesne wnętrza. Dzięki wykorzystaniu czynnika chłodniczego R32 oraz technologii inwerterowej, klimatyzator osiąga najwyższą klasę efektywności energetycznej A+++ dla chłodzenia oraz A++ dla grzania, co korzystnie wpływa na domowy budżet.",
      "Gree Amber Standard Silver działa sprawnie w różnorodnych warunkach temperaturowych, gwarantując komfortowe warunki pomieszczenia niezależnie od pogody. Dodatkowo, jonizacja powietrza poprawia jakość powietrza, zapewniając świeże i zdrowe otoczenie. Dzięki wbudowanemu modułowi Wi-Fi, użytkownicy mogą łatwo sterować urządzeniem za pomocą smartfona, zapewniając sobie jeszcze większą wygodę użytkowania.",
    ],
    highlight: "A+++ i jonizacja",
    features: [
      "Srebrna elegancka obudowa",
      "Klasa energetyczna A+++ (chłodzenie) / A++ (grzanie)",
      "Technologia inwerterowa",
      "Czynnik chłodniczy R32",
      "Jonizacja powietrza",
      "Wbudowany moduł Wi-Fi",
      "Praca w szerokim zakresie temperatur",
      "Grzałki do pracy zimowej",
    ],
    advantages: [
      { title: "Najwyższa efektywność", desc: "Klasa A+++ dla chłodzenia i A++ dla grzania — minimalne zużycie energii", icon: "energy" },
      { title: "Jonizacja powietrza", desc: "Wbudowany jonizator poprawia jakość powietrza w pomieszczeniu", icon: "leaf-02" },
      { title: "Sterowanie Wi-Fi", desc: "Łatwe sterowanie urządzeniem za pomocą smartfona", icon: "wifi-full-signal" },
      { title: "Praca zimowa", desc: "Grzałki do pracy zimowej zapewniają komfort przez cały rok", icon: "thermometer-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "24–41 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Amber Standard Silver 2,7 kW", power: "2,7 kW", energyClass: "A+++/A++", noise: "24 dB", phase: "230V", price: 4895, area: "20–30 m²" },
      { name: "Amber Standard Silver 3,5 kW", power: "3,5 kW", energyClass: "A+++/A++", noise: "28 dB", phase: "230V", price: 4973, area: "30–40 m²" },
      { name: "Amber Standard Silver 5,3 kW", power: "5,3 kW", energyClass: "A+++/A++", noise: "34 dB", phase: "230V", price: 6687, area: "40–60 m²" },
      { name: "Amber Standard Silver 7,0 kW", power: "7,0 kW", energyClass: "A+++/A++", noise: "41 dB", phase: "230V", price: 7345, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,0 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-standard-silver-gree-amber-standard-silver-14362.webp",
    imageAlt: "Klimatyzator Gree Amber Standard Silver",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-standard-silver-gree-amber-standard-silver-14362.webp",
        alt: "Gree Amber Standard Silver - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-standard-silver-gree-amber-standard-silver-1616955399.webp",
        alt: "Gree Amber Standard Silver - perspektywa",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-standard-silver-gree-amber-standard-silver-14360.webp",
        alt: "Gree Amber Standard Silver - detal",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-standard-silver-gree-amber-standard-silver-grzalki-do-pracy-zimowej.webp",
        alt: "Gree Amber Standard Silver - grzałki do pracy zimowej",
      },
    ],
  },
  {
    slug: "gree-amber-prestige",
    name: "Gree Amber Prestige",
    brand: "gree",
    category: "scienny",
    tagline: "Kompaktowy klimatyzator premium z najwyższą klasą A+++ dla obu trybów pracy",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Dzięki swoim kompaktowym rozmiarom, Gree Amber Prestige doskonale sprawdza się w małych pomieszczeniach, gdzie umieszczenie większych urządzeń byłoby problematyczne. Klasyczna biel minimalistycznej obudowy sprawia, że Gree Amber Prestige doskonale komponuje się z różnymi aranżacjami wnętrz. Klimatyzator charakteryzuje się najwyższą klasą efektywności energetycznej A+++ dla obu trybów.",
    descriptionLong: [
      "Dzięki swoim kompaktowym rozmiarom, Gree Amber Prestige doskonale sprawdza się w małych pomieszczeniach, gdzie umieszczenie większych urządzeń byłoby problematyczne. Klasyczna biel minimalistycznej obudowy sprawia, że Gree Amber Prestige doskonale komponuje się z różnymi aranżacjami wnętrz. Klimatyzator Gree Amber Prestige charakteryzuje się najwyższą klasą efektywności energetycznej A+++ dla obu trybów. Dodatkowo, dzięki zastosowaniu grzałki do pracy zimowej, Gree Amber Prestige to doskonały klimatyzator z funkcją ogrzewania, który zapewnia komfort przez cały rok.",
      "Gree Amber Prestige wyposażony został wyłącznie w podzespoły najwyższej jakości. Szczególnie warto zwrócić uwagę na zaawansowaną technologicznie dwustopniową sprężarkę, która w połączeniu z technologią inwerterową zapewnia niezwykłą wydajność urządzenia przy minimalnym zużyciu energii elektrycznej. Dodatkowo, Gree Amber Prestige cechuje się niskim poziomem hałasu (od 18 dB), co sprawia, że doskonale nadaje się do przestrzeni, gdzie wymagana jest cisza i spokój.",
    ],
    highlight: "A+++ i dwustopniowa sprężarka",
    features: [
      "Klasa energetyczna A+++ dla chłodzenia i grzania",
      "Dwustopniowa sprężarka o najwyższej wydajności",
      "Kompaktowe rozmiary",
      "Grzałka do pracy zimowej",
      "Niski poziom hałasu od 18 dB",
      "Sterowanie Wi-Fi przez aplikację",
      "Technologia inwerterowa",
      "Czynnik chłodniczy R32",
    ],
    advantages: [
      { title: "A+++ w obu trybach", desc: "Najwyższa klasa energetyczna zarówno dla chłodzenia jak i grzania", icon: "energy" },
      { title: "Dwustopniowa sprężarka", desc: "Zaawansowana sprężarka zapewnia niezwykłą wydajność przy minimalnym zużyciu energii", icon: "settings-01" },
      { title: "Ultracicha praca", desc: "Poziom hałasu od zaledwie 18 dB — idealny do sypialni", icon: "volume-low" },
      { title: "Kompaktowe rozmiary", desc: "Doskonale sprawdza się nawet w małych pomieszczeniach", icon: "square-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "18–43 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Amber Prestige 2,7 kW", power: "2,7 kW", energyClass: "A+++/A+++", noise: "18 dB", phase: "230V", price: 6040, area: "20–30 m²" },
      { name: "Amber Prestige 3,53 kW", power: "3,53 kW", energyClass: "A+++/A+++", noise: "22 dB", phase: "230V", price: 6580, area: "30–40 m²" },
      { name: "Amber Prestige 5,3 kW", power: "5,3 kW", energyClass: "A+++/A+++", noise: "34 dB", phase: "230V", price: 7550, area: "40–60 m²" },
      { name: "Amber Prestige 7,0 kW", power: "7,0 kW", energyClass: "A+++/A+++", noise: "43 dB", phase: "230V", price: 8200, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,0 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-prestige-14387.png",
    imageAlt: "Klimatyzator Gree Amber Prestige",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-prestige-14387.png",
        alt: "Gree Amber Prestige - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-prestige-gree-amber-prestige-front-1616955069.png",
        alt: "Gree Amber Prestige - front",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-prestige-14388.jpg",
        alt: "Gree Amber Prestige - widok boczny",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-amber-prestige-14385.jpg",
        alt: "Gree Amber Prestige - detal",
      },
    ],
  },
  {
    slug: "gree-fairy-white",
    name: "Gree Fairy White",
    brand: "gree",
    category: "scienny",
    tagline: "Innowacyjny klimatyzator ścienny z wyjątkowym designem i jonizatorem powietrza",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Gree Fairy White to innowacyjny klimatyzator ścienny, łączący doskonałą jakość komponentów z wyjątkowym designem. Model ten, w kolorze białym, wyróżnia się zaokrąglonymi bokami oraz eleganckim wykończeniem, idealnie pasując do większości nowoczesnych aranżacji. Zapewniając dużą wydajność i szerokie możliwości sterowania, klimatyzator ten gwarantuje skuteczne działanie oraz wygodną obsługę.",
    descriptionLong: [
      "Gree Fairy White to innowacyjny klimatyzator ścienny, łączący doskonałą jakość komponentów z wyjątkowym designem. Model ten, w kolorze białym, wyróżnia się zaokrąglonymi bokami oraz eleganckim wykończeniem, idealnie pasując do większości nowoczesnych aranżacji. Zapewniając dużą wydajność i szerokie możliwości sterowania, klimatyzator ten gwarantuje skuteczne działanie oraz wygodną obsługę, spełniając oczekiwania współczesnych użytkowników.",
      "Klimatyzator ścienny Gree Fairy White cechuje się również wysoką klasą energetyczną, A++ dla chłodzenia i A+ dla trybu grzania. Dzięki zastosowanej grzałce sprężarki, doskonale sprawdza się również w ogrzewaniu wybranych pomieszczeń w okresie przejściowym. Dodatkowo, działanie urządzenia wspiera jonizator, który odpowiada za usuwanie szkodliwych zanieczyszczeń i poprawę wilgotności powietrza.",
    ],
    highlight: "Jonizator i elegancki design",
    features: [
      "Elegancki biały design z zaokrąglonymi bokami",
      "Jonizator powietrza",
      "Grzałka sprężarki do pracy zimowej",
      "Klasa energetyczna A++ (chłodzenie) / A+ (grzanie)",
      "Sterowanie Wi-Fi przez aplikację",
      "Czynnik chłodniczy R32",
      "Szerokie możliwości sterowania",
      "Wysoka wydajność pracy",
    ],
    advantages: [
      { title: "Jonizator powietrza", desc: "Usuwa szkodliwe zanieczyszczenia i poprawia wilgotność powietrza", icon: "leaf-02" },
      { title: "Elegancki design", desc: "Zaokrąglone boki i białe wykończenie pasujące do nowoczesnych wnętrz", icon: "paint-board" },
      { title: "Grzałka sprężarki", desc: "Umożliwia ogrzewanie pomieszczeń nawet w okresie przejściowym", icon: "thermometer-01" },
      { title: "Sterowanie Wi-Fi", desc: "Wygodne sterowanie klimatyzatorem z poziomu smartfona", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "25–38 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Fairy White 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "25 dB", phase: "230V", price: 3990, area: "20–30 m²" },
      { name: "Fairy White 3,51 kW", power: "3,51 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 4310, area: "30–40 m²" },
      { name: "Fairy White 5,2 kW", power: "5,2 kW", energyClass: "A++/A+", noise: "34 dB", phase: "230V", price: 5940, area: "40–60 m²" },
      { name: "Fairy White 7,0 kW", power: "7,0 kW", energyClass: "A++/A+", noise: "38 dB", phase: "230V", price: 6750, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,0 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-white-gree-fairy-white-1652171039.png",
    imageAlt: "Klimatyzator Gree Fairy White",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-white-gree-fairy-white-1652171039.png",
        alt: "Gree Fairy White - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-white-16400.jpg",
        alt: "Gree Fairy White - perspektywa",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-white-16399.jpg",
        alt: "Gree Fairy White - detal",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-white-gree-fairy-white-jonizator-powietrza.webp",
        alt: "Gree Fairy White - jonizator powietrza",
      },
    ],
  },
  {
    slug: "gree-fairy-silver",
    name: "Gree Fairy Silver",
    brand: "gree",
    category: "scienny",
    tagline: "Wydajność i designerska srebrna obudowa z metalowymi akcentami",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Seria klimatyzatorów ściennych Gree Fairy Silver łączy w sobie wysoką wydajność oraz designerską obudowę. Ich srebrny matowy kolor, opływowy kształt oraz metalowe błyszczące elementy doskonale komponują się z nowoczesnym wystrojem wnętrz. Zapewniając zarówno estetykę, jak i zaawansowane funkcje, te urządzenia są idealnym wyborem dla osób ceniących sobie styl i wydajność.",
    descriptionLong: [
      "Seria klimatyzatorów ściennych Gree Fairy Silver łączy w sobie wysoką wydajność oraz designerską obudowę. Ich srebrny matowy kolor, opływowy kształt oraz metalowe błyszczące elementy doskonale komponują się z nowoczesnym wystrojem wnętrz. Zapewniając zarówno estetykę, jak i zaawansowane funkcje, te urządzenia są idealnym wyborem dla osób ceniących sobie styl i wydajność.",
      "Klimatyzatory ścienne Gree Fairy Silver osiągają efektywność energetyczną na poziomie A++ dla chłodzenia i A+ dla grzania. Dzięki szerokiemu zakresowi temperatur zewnętrznych, urządzenia te mogą działać nawet w ekstremalnych warunkach, zapewniając komfortowe warunki wewnętrzne niezależnie od pogody. Dodatkowo, zaawansowane technologie autokonserwacji dbają o zachowanie stałej efektywności pracy klimatyzatorów, nawet przy intensywnym użytkowaniu.",
    ],
    highlight: "Srebrny design i autokonserwacja",
    features: [
      "Srebrna matowa obudowa z metalowymi akcentami",
      "Opływowy designerski kształt",
      "Technologie autokonserwacji",
      "Klasa energetyczna A++ (chłodzenie) / A+ (grzanie)",
      "Szeroki zakres temperatur pracy",
      "Sterowanie Wi-Fi przez aplikację",
      "Czynnik chłodniczy R32",
      "Grzałka sprężarki do pracy zimowej",
    ],
    advantages: [
      { title: "Designerska obudowa", desc: "Srebrny matowy kolor z metalowymi akcentami — element dekoracyjny wnętrza", icon: "paint-board" },
      { title: "Autokonserwacja", desc: "Zaawansowane technologie dbają o stałą efektywność pracy urządzenia", icon: "settings-01" },
      { title: "Ekstremalne temperatury", desc: "Praca nawet w ekstremalnych warunkach temperaturowych", icon: "thermometer-01" },
      { title: "Sterowanie Wi-Fi", desc: "Wygodne sterowanie klimatyzatorem z poziomu smartfona", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "25–38 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Fairy Silver 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "25 dB", phase: "230V", price: 4300, area: "20–30 m²" },
      { name: "Fairy Silver 3,51 kW", power: "3,51 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 4310, area: "30–40 m²" },
      { name: "Fairy Silver 5,2 kW", power: "5,2 kW", energyClass: "A++/A+", noise: "34 dB", phase: "230V", price: 6685, area: "40–60 m²" },
      { name: "Fairy Silver 7,0 kW", power: "7,0 kW", energyClass: "A++/A+", noise: "38 dB", phase: "230V", price: 7550, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,0 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-silver-gree-fairy-silver-1618932258.png",
    imageAlt: "Klimatyzator Gree Fairy Silver",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-silver-gree-fairy-silver-1618932258.png",
        alt: "Gree Fairy Silver - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-silver-13168.jpg",
        alt: "Gree Fairy Silver - perspektywa",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-silver-13180.jpg",
        alt: "Gree Fairy Silver - detal",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-silver-13177.jpg",
        alt: "Gree Fairy Silver - widok boczny",
      },
    ],
  },
  {
    slug: "gree-fairy-dark",
    name: "Gree Fairy Dark",
    brand: "gree",
    category: "scienny",
    tagline: "Wysoka jakość wykonania z atrakcyjnym czarnym matowym designem",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Gree Fairy Dark to linia klimatyzatorów ściennych, które łączą wysoką jakość wykonania z atrakcyjnym designem. Ich czarna matowa obudowa o zaokrąglonych krawędziach, wzbogacona metalowym obramowaniem po bokach, doskonale wpisuje się w nowoczesne wnętrza. Oferując zarówno estetykę, jak i zaawansowane funkcje, te urządzenia są doskonałym wyborem dla osób, które cenią sobie nie tylko wygląd, ale także skuteczność działania.",
    descriptionLong: [
      "Gree Fairy Dark to linia klimatyzatorów ściennych, które łączą wysoką jakość wykonania z atrakcyjnym designem. Ich czarna matowa obudowa o zaokrąglonych krawędziach, wzbogacona metalowym obramowaniem po bokach, doskonale wpisuje się w nowoczesne wnętrza. Oferując zarówno estetykę, jak i zaawansowane funkcje, te urządzenia są doskonałym wyborem dla osób, które cenią sobie nie tylko wygląd, ale także skuteczność działania.",
      "Klimatyzatory ścienne Gree Fairy Dark zapewniają wysoką efektywność pracy, zwłaszcza w trybie ogrzewania. Modelom z tej serii przyznano ocenę A++ dla chłodzenia i A+ dla grzania. Oprócz regulacji warunków termicznych, urządzenia te wpływają także na czystość i wilgotność powietrza w pomieszczeniu, zapewniając kompleksową opiekę nad komfortem użytkowników.",
    ],
    highlight: "Czarny mat i efektywne ogrzewanie",
    features: [
      "Czarna matowa obudowa z metalowym obramowaniem",
      "Zaokrąglone krawędzie designerskiej obudowy",
      "Klasa energetyczna A++ (chłodzenie) / A+ (grzanie)",
      "Regulacja czystości i wilgotności powietrza",
      "Sterowanie Wi-Fi przez aplikację",
      "Czynnik chłodniczy R32",
      "Grzałka tacy skroplin",
      "Wysoka efektywność w trybie ogrzewania",
    ],
    advantages: [
      { title: "Czarny matowy design", desc: "Elegancka czarna obudowa z metalowymi akcentami — element dekoracyjny wnętrza", icon: "paint-board" },
      { title: "Kompleksowa opieka", desc: "Regulacja temperatury, czystości i wilgotności powietrza w jednym urządzeniu", icon: "leaf-02" },
      { title: "Efektywne ogrzewanie", desc: "Wysoka efektywność pracy w trybie ogrzewania z grzałką tacy skroplin", icon: "thermometer-01" },
      { title: "Sterowanie Wi-Fi", desc: "Wygodne sterowanie klimatyzatorem z poziomu smartfona", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "25–38 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Fairy Dark 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "25 dB", phase: "230V", price: 4300, area: "20–30 m²" },
      { name: "Fairy Dark 3,51 kW", power: "3,51 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 4310, area: "30–40 m²" },
      { name: "Fairy Dark 5,2 kW", power: "5,2 kW", energyClass: "A++/A+", noise: "34 dB", phase: "230V", price: 6685, area: "40–60 m²" },
      { name: "Fairy Dark 7,0 kW", power: "7,0 kW", energyClass: "A++/A+", noise: "38 dB", phase: "230V", price: 7550, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,0 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-dark-gree-fairy-dark-1618932259.png",
    imageAlt: "Klimatyzator Gree Fairy Dark",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-dark-gree-fairy-dark-1618932259.png",
        alt: "Gree Fairy Dark - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-dark-13183.jpg",
        alt: "Gree Fairy Dark - perspektywa",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-silver-13180.jpg",
        alt: "Gree Fairy Dark - detal",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-dark-gree-fairy-dark-grzalka-tacy-skroplin.webp",
        alt: "Gree Fairy Dark - grzałka tacy skroplin",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-fairy-dark-13194.jpg",
        alt: "Gree Fairy Dark - widok boczny",
      },
    ],
  },
  {
    slug: "gree-lomo-luxury-plus",
    name: "Gree Lomo Luxury Plus",
    brand: "gree",
    category: "scienny",
    tagline: "Ulepszona wersja cenionego klimatyzatora z najniższym wskaźnikiem awaryjności",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Gree Lomo Luxury Plus to nowa, ulepszona wersja cenionego przez użytkowników klimatyzatora Gree Lomo Luxury. Dzięki unowocześnionej konstrukcji dodano do urządzenia nowe funkcje, takie jak sterowanie nawiewem w pionie i poziomie, 7 biegów wentylatora oraz 3 tryby snu. Klimatyzatory z serii Gree Lomo Luxury Plus cechują się wysoką klasą energetyczną A++ dla chłodzenia oraz optymalną głośnością pracy (od 24 dB).",
    descriptionLong: [
      "Gree Lomo Luxury Plus to nowa, ulepszona wersja cenionego przez użytkowników klimatyzatora Gree Lomo Luxury. Dzięki unowocześnionej konstrukcji dodano do urządzenia nowe funkcje, takie jak sterowanie nawiewem w pionie i poziomie, 7 biegów wentylatora oraz 3 tryby snu. Klimatyzatory z serii Gree Lomo Luxury Plus cechują się wysoką klasą energetyczną A++ dla chłodzenia oraz optymalną głośnością pracy (od 24 dB).",
      "Gree Lomo Luxury Plus to klimatyzator charakteryzujący się bardzo niskim wskaźnikiem awaryjności, co zostało osiągnięte poprzez wykorzystanie podzespołów najwyższej jakości i najdłuższej żywotności. Sprężarka o zmiennej prędkości obrotowej oraz grzałki do pracy zimowej umożliwiają działanie klimatyzatora nawet przy bardzo niskich temperaturach zewnętrznych. Plazmowy jonizator powietrza dba o jakość nawiewu, a moduł Wi-Fi podnosi komfort sterowania urządzeniem na wyższy poziom.",
    ],
    highlight: "Niska awaryjność i jonizator plazmowy",
    features: [
      "Sterowanie nawiewem w pionie i poziomie",
      "7 biegów wentylatora",
      "3 tryby snu",
      "Plazmowy jonizator powietrza",
      "Sprężarka o zmiennej prędkości obrotowej",
      "Grzałki do pracy zimowej",
      "Moduł Wi-Fi",
      "Bardzo niski wskaźnik awaryjności",
    ],
    advantages: [
      { title: "Niezawodność", desc: "Bardzo niski wskaźnik awaryjności dzięki podzespołom najwyższej jakości", icon: "shield-02" },
      { title: "Plazmowy jonizator", desc: "Jonizator plazmowy dba o jakość nawiewu i czystość powietrza", icon: "leaf-02" },
      { title: "Praca zimowa", desc: "Grzałki i sprężarka o zmiennej prędkości — praca nawet przy bardzo niskich temperaturach", icon: "thermometer-01" },
      { title: "3 tryby snu", desc: "Trzy dedykowane tryby nocne zapewniające komfort podczas odpoczynku", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "24–41 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Lomo Luxury Plus 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 3445, area: "20–30 m²" },
      { name: "Lomo Luxury Plus 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 3660, area: "30–40 m²" },
      { name: "Lomo Luxury Plus 5,2 kW", power: "5,2 kW", energyClass: "A++/A+", noise: "34 dB", phase: "230V", price: 5890, area: "40–60 m²" },
      { name: "Lomo Luxury Plus 7,1 kW", power: "7,1 kW", energyClass: "A++/A+", noise: "41 dB", phase: "230V", price: 6750, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,1 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-lomo-luxury-plus-14370.jpg",
    imageAlt: "Klimatyzator Gree Lomo Luxury Plus",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-lomo-luxury-plus-14370.jpg",
        alt: "Gree Lomo Luxury Plus - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-lomo-luxury-plus-14374.jpg",
        alt: "Gree Lomo Luxury Plus - perspektywa",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-lomo-luxury-plus-gree-lomo-luxury-plus-front-1616955098.png",
        alt: "Gree Lomo Luxury Plus - front",
      },
    ],
  },
  {
    slug: "gree-soyal",
    name: "Gree Soyal",
    brand: "gree",
    category: "scienny",
    tagline: "Futurystyczny design z najwyższą klasą A+++ i ultracichą pracą od 19 dB",
    origin: "Gree Electric Appliances (Chiny)",
    description:
      "Gree Soyal to model klimatyzatora ściennego, który imponuje swoją wydajnością, futurystycznym designem i innowacyjnymi rozwiązaniami. Jego ekstrawagancka obudowa doskonale komponuje się z nowoczesnymi aranżacjami, stanowiąc nie tylko źródło komfortu, ale także element dekoracyjny przyciągający wzrok gości.",
    descriptionLong: [
      "Gree Soyal to model klimatyzatora ściennego, który imponuje swoją wydajnością, futurystycznym designem i innowacyjnymi rozwiązaniami. Jego ekstrawagancka obudowa doskonale komponuje się z nowoczesnymi aranżacjami, stanowiąc nie tylko źródło komfortu, ale także element dekoracyjny przyciągający wzrok gości. Ponadto, urządzenie wyróżnia się najwyższą klasą energetyczną, osiągając nawet ocenę A+++ dla chłodzenia i grzania, oraz niskim poziomem hałasu, który nie przekracza 19 dB(A).",
      "Klimatyzator Gree Soyal nie ustępuje wydajności nawet przy bardzo niskich temperaturach, sięgając nawet -25°C podczas grzania. Dodatkowo, wyposażony w czujnik obecności ludzi, urządzenie automatycznie dostosowuje swoją pracę do preferencji użytkowników, zapewniając jeszcze większy komfort przebywania w pomieszczeniu. Funkcja samooczyszczania to kolejny praktyczny dodatek, który gwarantuje utrzymanie urządzenia w doskonałej kondycji przez długi czas.",
    ],
    highlight: "A+++ i czujnik obecności",
    features: [
      "Najwyższa klasa energetyczna A+++ dla chłodzenia i grzania",
      "Ultracisza praca od 19 dB",
      "Futurystyczny design obudowy",
      "Czujnik obecności ludzi",
      "Funkcja samooczyszczania",
      "Praca grzania do -25°C",
      "Sterowanie Wi-Fi przez aplikację",
      "Czynnik chłodniczy R32",
    ],
    advantages: [
      { title: "A+++ w obu trybach", desc: "Najwyższa klasa energetyczna zarówno dla chłodzenia jak i grzania", icon: "energy" },
      { title: "Ultracisza praca", desc: "Poziom hałasu od zaledwie 19 dB — niemal niesłyszalny", icon: "volume-low" },
      { title: "Czujnik obecności", desc: "Automatyczne dostosowanie pracy do obecności i preferencji użytkowników", icon: "ai-brain-04" },
      { title: "Grzanie do -25°C", desc: "Wydajna praca w trybie ogrzewania nawet przy ekstremalnie niskich temperaturach", icon: "thermometer-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–42 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 5 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Soyal 2,7 kW", power: "2,7 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 5930, area: "20–30 m²" },
      { name: "Soyal 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "24 dB", phase: "230V", price: 6360, area: "30–40 m²" },
      { name: "Soyal 5,3 kW", power: "5,3 kW", energyClass: "A+++/A+++", noise: "42 dB", phase: "230V", price: 7330, area: "40–60 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 5,3 kW",
    warranty: "3 lata + 5 lat sprężarka",
    imageUrl:
      "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-soyal-gree-soyal-zestawy-1624370659.png",
    imageAlt: "Klimatyzator Gree Soyal",
    gallery: [
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-soyal-gree-soyal-zestawy-1624370659.png",
        alt: "Gree Soyal - zestawy",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-soyal-14043.png",
        alt: "Gree Soyal - widok z przodu",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-soyal-14042.jpg",
        alt: "Gree Soyal - perspektywa",
      },
      {
        src: "https://pbac.pl/wp-content/uploads/2024/03/jachce.renj1b3t64-yjr3ovgyr61m.p.temp-site.link-gree-soyal-14039.jpg",
        alt: "Gree Soyal - detal",
      },
    ],
  },
];
