import type { Product } from "@/types";

// ═══════════════════════════════════════════════════════════════
// Products scraped from pbac.pl — LG, Toshiba
// Scraped: 2026-03-17
// ═══════════════════════════════════════════════════════════════

export const lgToshibaProducts: Product[] = [
  // ═══════════════════════════════════════════════
  // LG (7 products)
  // ═══════════════════════════════════════════════
  {
    slug: "lg-standard-2",
    name: "LG Standard 2",
    brand: "lg",
    category: "scienny",
    tagline: "Dual Inverter i automatyczne oczyszczanie w kompaktowej obudowie",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG Standard 2 wprowadza nową jakość w segmencie klimatyzacji ściennych, łącząc zaawansowaną technologię z prostotą użytkowania. Wyposażony w innowacyjną sprężarkę Dual Inverter, urządzenie zapewnia wysoką efektywność energetyczną i cichą pracę, minimalizując wpływ na środowisko dzięki ekologicznemu czynnikowi chłodzącemu R32. System automatycznego oczyszczania utrzymuje wnętrze jednostki w czystości.",
    descriptionLong: [
      "LG Standard 2 wprowadza nową jakość w segmencie klimatyzacji ściennych, łącząc zaawansowaną technologię z prostotą użytkowania.",
      "Wyposażony w innowacyjną sprężarkę Dual Inverter, urządzenie zapewnia wysoką efektywność energetyczną i cichą pracę, minimalizując wpływ na środowisko dzięki ekologicznemu czynnikowi chłodzącemu R32.",
      "System automatycznego oczyszczania utrzymuje wnętrze jednostki w czystości, eliminując szkodliwe drobnoustroje i zapewniając zdrowy nawiew. Poziom hałasu od 19 dB czyni ten klimatyzator idealnym wyborem dla domów i mieszkań.",
    ],
    highlight: "Dual Inverter i autooczyszczanie",
    features: [
      "Sprężarka Dual Inverter",
      "Ekologiczny czynnik R32",
      "Automatyczne oczyszczanie",
      "Cicha praca od 19 dB",
      "Klasa energetyczna A++/A+",
      "Sterowanie WiFi",
      "Tryb grzania i chłodzenia",
      "Kompaktowa konstrukcja",
    ],
    advantages: [
      { title: "Dual Inverter", desc: "Innowacyjna sprężarka zapewniająca cichą i energooszczędną pracę", icon: "energy" },
      { title: "Autooczyszczanie", desc: "System automatycznego czyszczenia eliminujący drobnoustroje", icon: "shield-02" },
      { title: "Cicha praca", desc: "Poziom hałasu od zaledwie 19 dB — niemal niesłyszalny", icon: "volume-low" },
      { title: "WiFi", desc: "Sterowanie klimatyzatorem z poziomu smartfona", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Standard 2 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 4820, area: "20–30 m²" },
      { name: "Standard 2 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 4981, area: "30–40 m²" },
      { name: "Standard 2 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 6439, area: "40–60 m²" },
      { name: "Standard 2 6,6 kW", power: "6,6 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 7438, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji + 10 lat na sprężarkę",
    imageUrl: "/images/products/lg-standard-2.png",
    imageAlt: "Klimatyzator ścienny LG Standard 2",
    gallery: [
      { src: "/images/products/lg-standard-2-gallery-0.jpg", alt: "LG Standard 2 — widok z przodu" },
      { src: "/images/products/lg-standard-2-gallery-1.jpg", alt: "LG Standard 2 — widok boczny" },
      { src: "/images/products/lg-standard-2-gallery-2.jpg", alt: "LG Standard 2 — szczegóły" },
    ],
  },
  {
    slug: "lg-standard-plus",
    name: "LG Standard Plus",
    brand: "lg",
    category: "scienny",
    tagline: "Dual Inverter z klasą A++ i 10-letnią gwarancją na sprężarkę",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "Klimatyzator LG Standard Plus wyróżnia się zastosowaniem ekologicznego czynnika chłodniczego R32 oraz innowacyjnej sprężarki Dual Inverter, które razem przyczyniają się do wyjątkowo wysokiej efektywności energetycznej A++ dla chłodzenia i A+ dla grzania. Niezwykle cicha praca od 19 dB sprawia, że jest niemal niezauważalny w codziennym użytkowaniu.",
    descriptionLong: [
      "Klimatyzator LG Standard Plus wyróżnia się zastosowaniem ekologicznego czynnika chłodniczego R32 oraz innowacyjnej sprężarki Dual Inverter, które razem przyczyniają się do wyjątkowo wysokiej efektywności energetycznej.",
      "Klasa A++ dla chłodzenia i A+ dla grzania to gwarancja oszczędności energetycznych oraz szybkiej adaptacji do potrzeb termicznych pomieszczenia.",
      "Niezwykle cicha praca od 19 dB sprawia, że jest niemal niezauważalny w codziennym użytkowaniu. 3-letnia gwarancja na całe urządzenie oraz 10-letnia ochrona na sprężarkę podkreślają trwałość i niezawodność.",
    ],
    highlight: "A++ i 10 lat gwarancji sprężarki",
    features: [
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Ekologiczny czynnik R32",
      "Klasa energetyczna A++/A+",
      "Cicha praca od 19 dB",
      "Sterowanie WiFi",
      "Automatyczne oczyszczanie",
      "Tryb grzania i chłodzenia",
      "Szybkie chłodzenie/grzanie",
    ],
    advantages: [
      { title: "10 lat gwarancji", desc: "Rozszerzona gwarancja na sprężarkę Dual Inverter", icon: "shield-02" },
      { title: "Klasa A++", desc: "Wysoka efektywność energetyczna w trybie chłodzenia", icon: "tick-02" },
      { title: "Cicha praca", desc: "Poziom hałasu od 19 dB — komfort w każdym pomieszczeniu", icon: "volume-low" },
      { title: "R32", desc: "Ekologiczny czynnik chłodniczy nowej generacji", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Standard Plus 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 5253, area: "20–30 m²" },
      { name: "Standard Plus 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 5406, area: "30–40 m²" },
      { name: "Standard Plus 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 7050, area: "40–60 m²" },
      { name: "Standard Plus 6,6 kW", power: "6,6 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 8278, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji + 10 lat na sprężarkę",
    imageUrl: "/images/products/lg-standard-plus.png",
    imageAlt: "Klimatyzator ścienny LG Standard Plus",
    gallery: [
      { src: "/images/products/lg-standard-plus-gallery-0.jpg", alt: "LG Standard Plus — widok boczny" },
      { src: "/images/products/lg-standard-plus-gallery-1.jpg", alt: "LG Standard Plus — szczegóły" },
      { src: "/images/products/lg-standard-plus-gallery-2.jpg", alt: "LG Standard Plus — panel sterowania" },
    ],
  },
  {
    slug: "lg-deluxe",
    name: "LG Deluxe",
    brand: "lg",
    category: "scienny",
    tagline: "A++ chłodzenie i grzanie, Gold Fin i 10-letnia gwarancja sprężarki",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "Klimatyzator ścienny LG Deluxe to połączenie kompaktowej konstrukcji, wysokiej efektywności energetycznej i cichej pracy. Osiągając klasę A++ zarówno w trybie chłodzenia, jak i grzania dzięki sprężarce DUAL Inverter i czynnikowi R32, stanowi ekonomiczne i przyjazne dla środowiska rozwiązanie. Złota powłoka Gold Fin na lamelach wymiennika zapewnia dodatkową trwałość i ochronę.",
    descriptionLong: [
      "LG Deluxe to propozycja dla tych, którzy oczekują premium osiągów w klasycznej, eleganckiej formie. Model ten osiąga SEER 7,0 i SCOP 4,3, co przekłada się na klasę energetyczną A++ zarówno w chłodzeniu, jak i grzaniu. Jednostka wewnętrzna o wymiarach 998 x 345 x 210 mm mieści zaawansowany wymiennik ciepła pokryty złotą powłoką Gold Fin, która zwiększa odporność na korozję i przedłuża żywotność urządzenia — szczególnie istotne w warunkach miejskich, gdzie powietrze zawiera więcej zanieczyszczeń.",
      "Sprężarka DUAL Inverter objęta jest 10-letnią gwarancją producenta — jedną z najdłuższych na rynku. W połączeniu z ekologicznym czynnikiem R32 zapewnia cichą i stabilną pracę z poziomem hałasu od zaledwie 19 dB w trybie nocnym. Technologia UVnano sterylizuje powietrze przechodzące przez wymiennik, eliminując do 99,99% bakterii na łopatkach wentylatora.",
      "Jonizator Plasmaster Ionizer+ generuje ponad 3 miliony jonów ujemnych na centymetr sześcienny, neutralizując alergeny, pyłki i drobne cząsteczki unoszące się w powietrzu. Dla alergików i rodzin z małymi dziećmi to funkcja, która realnie wpływa na jakość życia. Automatyczne oczyszczanie wnętrza jednostki zapobiega rozwojowi pleśni i grzybów.",
      "Sterowanie przez aplikację LG ThinQ z wbudowanym modułem Wi-Fi pozwala na zdalne zarządzanie temperaturą i harmonogramem pracy. Deluxe jest dostępny w czterech wariantach mocy od 2,5 do 6,6 kW, obsługując pomieszczenia od 20 do nawet 90 m². Na tle konkurencji wyróżnia się idealnym balansem między ceną, efektywnością energetyczną i jakością filtracji powietrza.",
    ],
    highlight: "A++/A++ i Gold Fin",
    features: [
      "Sprężarka DUAL Inverter z 10-letnią gwarancją",
      "Klasa A++/A++ (chłodzenie i grzanie)",
      "Powłoka Gold Fin na wymienniku",
      "Ekologiczny czynnik R32",
      "Cicha praca od 19 dB",
      "Sterowanie WiFi",
      "Jonizator powietrza",
      "Automatyczne oczyszczanie",
    ],
    advantages: [
      { title: "A++/A++", desc: "Najwyższa klasa efektywności energetycznej w obu trybach pracy", icon: "tick-02" },
      { title: "Gold Fin", desc: "Złota powłoka chroniąca wymiennik przed korozją", icon: "paint-board" },
      { title: "10 lat gwarancji", desc: "Rozszerzona gwarancja na sprężarkę DUAL Inverter", icon: "shield-02" },
      { title: "Cicha praca", desc: "Poziom hałasu od 19 dB — komfort bez kompromisów", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Deluxe 2,5 kW", power: "2,5 kW", energyClass: "A++/A++", noise: "19 dB", phase: "230V", price: 5949, area: "20–30 m²" },
      { name: "Deluxe 3,5 kW", power: "3,5 kW", energyClass: "A++/A++", noise: "19 dB", phase: "230V", price: 6110, area: "30–40 m²" },
      { name: "Deluxe 5,0 kW", power: "5,0 kW", energyClass: "A++/A++", noise: "22 dB", phase: "230V", price: 7465, area: "40–60 m²" },
      { name: "Deluxe 6,6 kW", power: "6,6 kW", energyClass: "A++/A++", noise: "24 dB", phase: "230V", price: 8744, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji + 10 lat na sprężarkę",
    imageUrl: "/images/products/lg-deluxe.png",
    imageAlt: "Klimatyzator ścienny LG Deluxe",
    gallery: [
      { src: "/images/products/lg-deluxe-gallery-0.jpg", alt: "LG Deluxe — widok z przodu" },
      { src: "/images/products/lg-deluxe-gallery-1.jpg", alt: "LG Deluxe — widok boczny" },
      { src: "/images/products/lg-deluxe-gallery-2.jpg", alt: "LG Deluxe — szczegóły konstrukcji" },
    ],
  },
  {
    slug: "lg-dualcool",
    name: "LG Dualcool",
    brand: "lg",
    category: "scienny",
    tagline: "Zaawansowane oczyszczanie powietrza i sprężarka Dual Inverter",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG DualCool to jeden z najnowszych klimatyzatorów ściennych SPLIT od koreańskiego giganta. Wyróżnia się zaawansowanym systemem oczyszczania powietrza, który skutecznie wykrywa i neutralizuje zanieczyszczenia. Sprężarka Dual Inverter zapewnia klasę A++ dla chłodzenia i A+ dla grzania, przekładając się na znaczące ograniczenie zużycia prądu.",
    descriptionLong: [
      "Seria DualCool od LG łączy zaawansowane oczyszczanie powietrza z klimatyzacją w jednym urządzeniu. Wbudowany system filtracji wykrywa i neutralizuje cząsteczki zanieczyszczeń — pyłki, kurz, alergeny i mikroorganizmy — co czyni ten model szczególnie wartościowym w miastach o podwyższonym stężeniu smogu. SEER 6,6 i SCOP 4,0 zapewniają klasę A++ w chłodzeniu i A+ w grzaniu.",
      "Sprężarka DUAL Inverter pracuje z maksymalną wydajnością przy minimalnym zużyciu energii i hałasie. Poziom ciśnienia akustycznego jednostki wewnętrznej wynosi od 21 dB(A) — zbliżony do szmeru liści na wietrze. Jednostka zewnętrzna o wymiarach 717 x 495 x 230 mm jest jedną z najbardziej kompaktowych w swojej klasie, co ułatwia montaż na balkonach i elewacjach z ograniczoną przestrzenią.",
      "Na sprężarkę producent udziela aż 10-letniej gwarancji, co jest wyrazem zaufania do trwałości zastosowanej konstrukcji. Ekologiczny czynnik R32 zapewnia wyższą wydajność chłodniczą niż starszy R410A, przy jednoczesnym obniżeniu wpływu na efekt cieplarniany o ponad 70%. Wbudowany moduł Wi-Fi pozwala sterować urządzeniem przez aplikację LG ThinQ z dowolnego miejsca.",
    ],
    highlight: "Oczyszczanie powietrza i Dual Inverter",
    features: [
      "Zaawansowany system oczyszczania powietrza",
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Ekologiczny czynnik R32",
      "Klasa energetyczna A++/A+",
      "Cicha praca od 21 dB",
      "Sterowanie WiFi",
      "Smukła konstrukcja",
      "Tryb grzania i chłodzenia",
    ],
    advantages: [
      { title: "Oczyszczanie", desc: "Zaawansowany system wykrywający i neutralizujący zanieczyszczenia", icon: "shield-02" },
      { title: "Dual Inverter", desc: "Sprężarka z 10-letnią gwarancją i wysoką efektywnością", icon: "energy" },
      { title: "R32", desc: "Ekologiczny czynnik chłodniczy o niskim GWP", icon: "leaf-02" },
      { title: "WiFi", desc: "Sterowanie urządzeniem z poziomu smartfona", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 21 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "DualCool 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "21 dB", phase: "230V", price: 6169, area: "20–30 m²" },
      { name: "DualCool 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "21 dB", phase: "230V", price: 6517, area: "30–40 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 3,5 kW",
    warranty: "3 lata gwarancji + 10 lat na sprężarkę",
    imageUrl: "/images/products/lg-dualcool.png",
    imageAlt: "Klimatyzator ścienny LG DualCool",
    gallery: [
      { src: "/images/products/lg-dualcool-gallery-0.jpg", alt: "LG DualCool — widok z przodu" },
      { src: "/images/products/lg-dualcool-gallery-1.jpg", alt: "LG DualCool — widok boczny" },
      { src: "/images/products/lg-dualcool-gallery-2.jpg", alt: "LG DualCool — szczegóły" },
    ],
  },
  {
    slug: "lg-artcool-mirror",
    name: "LG Artcool Mirror",
    brand: "lg",
    category: "scienny",
    tagline: "Designerski klimatyzator z czarną, lustrzaną obudową",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG Artcool Mirror to niezwykle atrakcyjny klimatyzator ścienny SPLIT, który zachwyca designerskim wyglądem. Czarna obudowa z połyskliwym wykończeniem idealnie komponuje się w nowoczesnych wnętrzach. Urządzenie cechuje się wysoką wydajnością przy niezwykle cichej pracy od 19 dB. Sprężarka Dual Inverter zapewnia klasę A++ dla chłodzenia i A+ dla grzania.",
    descriptionLong: [
      "LG Artcool Mirror to niezwykle atrakcyjny klimatyzator ścienny SPLIT, który zachwyca designerskim wyglądem. Czarna obudowa z połyskliwym wykończeniem idealnie komponuje się w nowoczesnych wnętrzach.",
      "Urządzenie cechuje się wysoką wydajnością przy niezwykle cichej pracy, osiągając poziom hałasu od 19 dB. Czynnik R32 w układzie chłodzącym zapewnia ekologiczność i efektywność.",
      "Innowacyjna sprężarka Dual Inverter przekłada się na niski poziom głośności oraz klasę A++ dla chłodzenia i A+ dla grzania. Liczne rozwiązania poprawiają jakość powietrza w pomieszczeniu.",
    ],
    highlight: "Designerska lustrzana obudowa",
    features: [
      "Czarna lustrzana obudowa premium",
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Klasa energetyczna A++/A+",
      "Ekologiczny czynnik R32",
      "Cicha praca od 19 dB",
      "Sterowanie WiFi",
      "Jonizator Plasmaster",
      "Tryb grzania i chłodzenia",
    ],
    advantages: [
      { title: "Design", desc: "Lustrzana czarna obudowa — elegancja w nowoczesnym wnętrzu", icon: "paint-board" },
      { title: "Dual Inverter", desc: "Sprężarka z 10-letnią gwarancją i cichą pracą", icon: "energy" },
      { title: "Plasmaster", desc: "Jonizator poprawiający jakość powietrza w pomieszczeniu", icon: "shield-02" },
      { title: "Cicha praca", desc: "Poziom hałasu od zaledwie 19 dB", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Artcool Mirror 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 6789, area: "20–30 m²" },
      { name: "Artcool Mirror 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 7120, area: "30–40 m²" },
      { name: "Artcool Mirror 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 8229, area: "40–60 m²" },
      { name: "Artcool Mirror 6,6 kW", power: "6,6 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 9491, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji + 10 lat na sprężarkę",
    imageUrl: "/images/products/lg-artcool-mirror.png",
    imageAlt: "Klimatyzator ścienny LG Artcool Mirror",
    gallery: [
      { src: "/images/products/lg-artcool-mirror-gallery-0.jpg", alt: "LG Artcool Mirror — widok z przodu" },
      { src: "/images/products/lg-artcool-mirror-gallery-1.jpg", alt: "LG Artcool Mirror — widok boczny" },
      { src: "/images/products/lg-artcool-mirror-gallery-2.jpg", alt: "LG Artcool Mirror — szczegóły wykończenia" },
    ],
  },
  {
    slug: "lg-artcool-beige",
    name: "LG Artcool Beige",
    brand: "lg",
    category: "scienny",
    tagline: "Beżowy design, filtr antyalergiczny i Plasmaster Ionizer++",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "Klimatyzator LG ARTCOOL Beige to nowa definicja elegancji i innowacji w klimatyzacji. Beżowy kolor wpisuje się w nowoczesne trendy wnętrzarskie, oferując estetyczne i funkcjonalne uzupełnienie przestrzeni domowej czy biurowej. Wyposażony w filtr antyalergiczny, technologię Plasmaster Ionizer++ oraz zaawansowany system filtracji, zapewnia wyjątkowo czyste powietrze.",
    descriptionLong: [
      "Klimatyzator LG ARTCOOL Beige to nowa definicja elegancji i innowacji w klimatyzacji. Beżowy kolor wpisuje się w nowoczesne trendy wnętrzarskie.",
      "Wyposażony w filtr antyalergiczny i technologię Plasmaster Ionizer++, zapewnia wyjątkowo czyste powietrze — odpowiedź na rosnące wymagania dotyczące jakości środowiska wewnętrznego.",
      "Sprężarka Dual Inverter z 10-letnią gwarancją i czynnik R32 gwarantują klasę A++ dla chłodzenia i A+ dla grzania przy niezwykle cichej pracy od 19 dB.",
    ],
    highlight: "Beżowy design i Plasmaster Ionizer++",
    features: [
      "Beżowa obudowa w nowoczesnym stylu",
      "Filtr antyalergiczny",
      "Technologia Plasmaster Ionizer++",
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Klasa energetyczna A++/A+",
      "Ekologiczny czynnik R32",
      "Cicha praca od 19 dB",
      "Sterowanie WiFi",
    ],
    advantages: [
      { title: "Design Beige", desc: "Beżowa obudowa wpisująca się w nowoczesne trendy wnętrzarskie", icon: "paint-board" },
      { title: "Plasmaster Ionizer++", desc: "Zaawansowana jonizacja zapewniająca czyste powietrze", icon: "shield-02" },
      { title: "Filtr antyalergiczny", desc: "Ochrona przed alergenami i zanieczyszczeniami", icon: "leaf-02" },
      { title: "Dual Inverter", desc: "Sprężarka z 10-letnią gwarancją i cichą pracą", icon: "energy" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Artcool Beige 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 7026, area: "20–30 m²" },
      { name: "Artcool Beige 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 7374, area: "30–40 m²" },
      { name: "Artcool Beige 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 8543, area: "40–60 m²" },
      { name: "Artcool Beige 6,6 kW", power: "6,6 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 9865, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,6 kW",
    warranty: "3 lata gwarancji + 10 lat na sprężarkę",
    imageUrl: "/images/products/lg-artcool-beige.png",
    imageAlt: "Klimatyzator ścienny LG Artcool Beige",
    gallery: [
      { src: "/images/products/lg-artcool-beige-gallery-0.jpg", alt: "LG Artcool Beige — widok z przodu" },
      { src: "/images/products/lg-artcool-beige-gallery-1.jpg", alt: "LG Artcool Beige — widok boczny" },
      { src: "/images/products/lg-artcool-beige-gallery-2.jpg", alt: "LG Artcool Beige — szczegóły wykończenia" },
    ],
  },
  {
    slug: "lg-artcool-gallery",
    name: "LG Artcool Gallery",
    brand: "lg",
    category: "scienny",
    tagline: "Klimatyzator z wymienną ramką na obraz — funkcjonalność i sztuka",
    origin: "LG Electronics (Korea Południowa)",
    description:
      "LG Artcool Gallery to niezwykły klimatyzator ścienno-sufitowy, który pełni również funkcję estetyczną. Wyposażony w czarną ramę umożliwiającą personalizację ulubionym obrazem czy zdjęciem, stanowi idealne połączenie praktyczności i elegancji. Sprężarka Dual Inverter z 10-letnią gwarancją oraz czynnik R32 zapewniają klasę A++ dla chłodzenia i A+ dla grzania.",
    descriptionLong: [
      "Żaden inny klimatyzator na rynku nie łączy sztuki z klimatyzacją tak jak LG Artcool Gallery. Przedni panel urządzenia mieści wymienną ramkę, w której można umieścić własne zdjęcie, reprodukcję obrazu lub grafikę — klimatyzator staje się elementem dekoracyjnym wnętrza, a nie sprzętem, który trzeba ukrywać. To rozwiązanie docenili projektanci wnętrz na całym świecie, a sam model zdobył liczne nagrody za wzornictwo.",
      "Pod minimalistyczną, kwadratową obudową kryje się sprawdzona technologia LG. Sprężarka DUAL Inverter z 10-letnią gwarancją producenta zapewnia stabilną i energooszczędną pracę, osiągając SEER 6,6 i SCOP 4,0 (klasa A++ w chłodzeniu, A+ w grzaniu). Maksymalny przepływ powietrza sięga 9,0 m³/min, a zdolność osuszania wynosi 1,3 l/h — parametry, które gwarantują skuteczne działanie nawet w wilgotne, upalne dni.",
      "Trójstronny nawiew rozprowadza powietrze w trzech kierunkach jednocześnie, zapewniając szybkie i równomierne schłodzenie całego pomieszczenia. Funkcja Mocne Chłodzenie przyspiesza osiągnięcie docelowej temperatury, a system automatycznego oczyszczania utrzymuje wnętrze jednostki w czystości, eliminując drobnoustroje.",
      "Sterowanie Wi-Fi przez aplikację LG ThinQ umożliwia zarządzanie klimatyzatorem z poziomu smartfona. Czynnik R32 o niskim współczynniku GWP minimalizuje wpływ na środowisko. Artcool Gallery jest dostępny w wariantach 2,5 i 3,5 kW — idealny do salonów, gabinetów i przestrzeni, gdzie estetyka ma równie duże znaczenie co komfort termiczny.",
    ],
    highlight: "Wymienna ramka na obraz",
    features: [
      "Wymienna ramka na obraz lub zdjęcie",
      "Sprężarka Dual Inverter z 10-letnią gwarancją",
      "Klasa energetyczna A++/A+",
      "Ekologiczny czynnik R32",
      "Cicha praca od 27 dB",
      "Sterowanie WiFi",
      "Minimalistyczna konstrukcja",
      "Automatyczne oczyszczanie",
    ],
    advantages: [
      { title: "Galeria", desc: "Wymienna ramka pozwala ozdobić klimatyzator ulubionym obrazem", icon: "paint-board" },
      { title: "Dual Inverter", desc: "Sprężarka z 10-letnią gwarancją i cichą pracą", icon: "energy" },
      { title: "Minimalizm", desc: "Smukła konstrukcja doskonale wkomponowująca się we wnętrze", icon: "home-01" },
      { title: "R32", desc: "Ekologiczny czynnik chłodniczy nowej generacji", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 27 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata + 10 lat sprężarka", icon: "shield-02" },
    ],
    models: [
      { name: "Artcool Gallery 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "27 dB", phase: "230V", price: 8028, area: "20–30 m²" },
      { name: "Artcool Gallery 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "27 dB", phase: "230V", price: 9139, area: "30–40 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 3,5 kW",
    warranty: "3 lata gwarancji + 10 lat na sprężarkę",
    imageUrl: "/images/products/lg-artcool-gallery.png",
    imageAlt: "Klimatyzator ścienny LG Artcool Gallery",
    gallery: [
      { src: "/images/products/lg-artcool-gallery-gallery-0.jpg", alt: "LG Artcool Gallery — widok z przodu" },
      { src: "/images/products/lg-artcool-gallery-gallery-1.jpg", alt: "LG Artcool Gallery — szczegóły ramki" },
      { src: "/images/products/lg-artcool-gallery-gallery-2.jpg", alt: "LG Artcool Gallery — aranżacja wnętrza" },
    ],
  },

  // ═══════════════════════════════════════════════
  // Toshiba (6 products)
  // ═══════════════════════════════════════════════
  {
    slug: "toshiba-seiya-2",
    name: "Toshiba Seiya 2",
    brand: "toshiba",
    category: "scienny",
    tagline: "Druga generacja — zaawansowana technologia w atrakcyjnej cenie",
    origin: "Toshiba (Japonia)",
    description:
      "Toshiba Seiya 2 to klimatyzator ścienny drugiej generacji, łączący zaawansowaną technologię, estetyczny design i atrakcyjną cenę. Dostępny w wydajnościach od 1,5 do 6,5 kW, pozwala precyzyjnie dostosować się do potrzeb. Rotacyjne sprężarki inwerterowe zapewniają klasę A++/A++, a funkcja samooczyszczania dba o czystość wnętrza.",
    descriptionLong: [
      "Toshiba Seiya 2 to klimatyzator ścienny drugiej generacji, łączący zaawansowaną technologię, estetyczny design i atrakcyjną cenę.",
      "Dostępny w wydajnościach od 1,5 do 6,5 kW, pozwala precyzyjnie dostosować się do potrzeb. Rotacyjne sprężarki inwerterowe zapewniają klasę A++/A++.",
      "Działa skutecznie nawet w skrajnych warunkach temperaturowych, a niezwykle cicha praca gwarantuje spokój i komfort. Funkcja samooczyszczania eliminuje wilgoć i pleśń. Sterowanie przez WiFi.",
    ],
    highlight: "A++/A++ w atrakcyjnej cenie",
    features: [
      "Rotacyjna sprężarka inwerterowa",
      "Klasa energetyczna A++/A++",
      "Ekologiczny czynnik R32",
      "Cicha praca od 19 dB",
      "Funkcja samooczyszczania",
      "Sterowanie WiFi",
      "Szeroki zakres wydajności 1,5–6,5 kW",
      "Praca w szerokim zakresie temperatur",
    ],
    advantages: [
      { title: "Atrakcyjna cena", desc: "Doskonały stosunek jakości do ceny w segmencie premium", icon: "tick-02" },
      { title: "A++/A++", desc: "Najwyższa klasa efektywności energetycznej w obu trybach", icon: "energy" },
      { title: "Samooczyszczanie", desc: "Automatyczne usuwanie wilgoci i pleśni z wnętrza jednostki", icon: "shield-02" },
      { title: "WiFi", desc: "Zdalne sterowanie przez aplikację mobilną", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Seiya 2 1,5 kW", power: "1,5 kW", energyClass: "A++/A++", noise: "19 dB", phase: "230V", price: 5072, area: "10–20 m²" },
      { name: "Seiya 2 2,0 kW", power: "2,0 kW", energyClass: "A++/A++", noise: "19 dB", phase: "230V", price: 5230, area: "10–20 m²" },
      { name: "Seiya 2 2,5 kW", power: "2,5 kW", energyClass: "A++/A++", noise: "19 dB", phase: "230V", price: 5626, area: "20–30 m²" },
      { name: "Seiya 2 3,3 kW", power: "3,3 kW", energyClass: "A++/A++", noise: "22 dB", phase: "230V", price: 5745, area: "30–40 m²" },
      { name: "Seiya 2 4,2 kW", power: "4,2 kW", energyClass: "A++/A++", noise: "24 dB", phase: "230V", price: 6962, area: "40–50 m²" },
      { name: "Seiya 2 5,0 kW", power: "5,0 kW", energyClass: "A++/A++", noise: "26 dB", phase: "230V", price: 7912, area: "50–60 m²" },
      { name: "Seiya 2 6,5 kW", power: "6,5 kW", energyClass: "A++/A++", noise: "28 dB", phase: "230V", price: 9129, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "1,5 – 6,5 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/toshiba-seiya-2.png",
    imageAlt: "Klimatyzator ścienny Toshiba Seiya 2",
    gallery: [
      { src: "/images/products/toshiba-seiya-2-gallery-0.jpg", alt: "Toshiba Seiya 2 — widok z przodu" },
      { src: "/images/products/toshiba-seiya-2-gallery-1.jpg", alt: "Toshiba Seiya 2 — widok boczny" },
      { src: "/images/products/toshiba-seiya-2-gallery-2.jpg", alt: "Toshiba Seiya 2 — szczegóły" },
    ],
  },
  {
    slug: "toshiba-shorai-edge-white",
    name: "Toshiba Shorai Edge White",
    brand: "toshiba",
    category: "scienny",
    tagline: "Filtr Ultra Pure, nawiew HADA-Care i wbudowany WiFi",
    origin: "Toshiba (Japonia)",
    description:
      "Toshiba Shorai Edge White to najnowsza propozycja klimatyzatora ściennego, łącząca elegancki design z doskonałą wydajnością. Dostępny w ośmiu wariantach wydajnościowych, działa na czynniku R32 z klasą energetyczną A+++/A+++. Filtr Ultra Pure zapewnia wysoką jakość oczyszczenia powietrza, a technologia nawiewu HADA-Care podnosi komfort użytkowania.",
    descriptionLong: [
      "Shorai Edge to flagowa seria ściennych klimatyzatorów Toshiba, która osiąga imponujące wartości SEER 8,5 i SCOP 5,1 w wariancie 2,0 kW — jedne z najwyższych na rynku. Każdy model w serii spełnia wymagania klasy A+++ zarówno w chłodzeniu, jak i grzaniu, co w skali sezonu przekłada się na roczne zużycie energii na poziomie zaledwie 104 kWh w trybie chłodzenia.",
      "Technologia nawiewu HADA-Care (z japońskiego 'hada' oznacza 'skóra') została zaprojektowana z myślą o delikatnym, nieskoncentrowanym strumieniu powietrza, który nie wysusza skóry i nie powoduje dyskomfortu. Filtr Ultra Pure PM2.5 wychwytuje do 94% drobnych cząstek stałych, pyłków i alergenów, a wymiennik ciepła z powłoką Magic Coil utrudnia gromadzenie się zanieczyszczeń, zachowując pełną wydajność przez lata.",
      "Seria Shorai Edge White oferuje siedem wariantów mocy od 2,0 do 7,0 kW, dzięki czemu pokrywa potrzeby zarówno niewielkich sypialni (od 10 m²), jak i obszernych salonów czy biur (do 70 m²). Rotacyjne sprężarki inwerterowe Toshiba słyną z niezawodności — producent udziela 5-letniej gwarancji na całe urządzenie. Poziom hałasu od 19 dB(A) w trybie cichym zapewnia komfort nocą.",
      "Wbudowany moduł Wi-Fi umożliwia zdalne sterowanie przez aplikację mobilną, a programator tygodniowy pozwala precyzyjnie zaplanować harmonogram pracy na cały tydzień. Czynnik R32 zapewnia wysoką efektywność termodynamiczną przy niskim wpływie na środowisko. Shorai Edge White to wybór dla osób, które szukają najwyższej klasy energetycznej bez kompromisów w kwestii komfortu i jakości powietrza.",
    ],
    highlight: "A+++/A+++ i Ultra Pure",
    features: [
      "Klasa energetyczna A+++/A+++",
      "Filtr Ultra Pure",
      "Technologia nawiewu HADA-Care",
      "Ekologiczny czynnik R32",
      "Wbudowany moduł WiFi",
      "Rotacyjna sprężarka inwerterowa",
      "Cicha praca od 19 dB",
      "Szeroki zakres wydajności 2,0–7,0 kW",
    ],
    advantages: [
      { title: "A+++/A+++", desc: "Najwyższa klasa efektywności energetycznej na rynku", icon: "tick-02" },
      { title: "Ultra Pure", desc: "Zaawansowany filtr zapewniający najwyższą jakość powietrza", icon: "shield-02" },
      { title: "HADA-Care", desc: "Innowacyjna technologia nawiewu dla maksymalnego komfortu", icon: "energy" },
      { title: "WiFi", desc: "Wbudowany moduł do zdalnego sterowania", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (wbudowany)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Shorai Edge White 2,0 kW", power: "2,0 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 6775, area: "10–20 m²" },
      { name: "Shorai Edge White 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 7171, area: "20–30 m²" },
      { name: "Shorai Edge White 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 8121, area: "30–40 m²" },
      { name: "Shorai Edge White 4,6 kW", power: "4,6 kW", energyClass: "A+++/A+++", noise: "22 dB", phase: "230V", price: 9180, area: "30–40 m²" },
      { name: "Shorai Edge White 5,0 kW", power: "5,0 kW", energyClass: "A+++/A+++", noise: "24 dB", phase: "230V", price: 10605, area: "40–50 m²" },
      { name: "Shorai Edge White 6,1 kW", power: "6,1 kW", energyClass: "A+++/A+++", noise: "26 dB", phase: "230V", price: 11347, area: "50–60 m²" },
      { name: "Shorai Edge White 7,0 kW", power: "7,0 kW", energyClass: "A+++/A+++", noise: "28 dB", phase: "230V", price: 12218, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,0 – 7,0 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/toshiba-shorai-edge-white.png",
    imageAlt: "Klimatyzator ścienny Toshiba Shorai Edge White",
    gallery: [
      { src: "/images/products/toshiba-shorai-edge-white-gallery-0.jpg", alt: "Toshiba Shorai Edge White — widok z przodu" },
      { src: "/images/products/toshiba-shorai-edge-white-gallery-1.jpg", alt: "Toshiba Shorai Edge White — widok boczny" },
      { src: "/images/products/toshiba-shorai-edge-white-gallery-2.jpg", alt: "Toshiba Shorai Edge White — szczegóły" },
    ],
  },
  {
    slug: "toshiba-shorai-edge-black",
    name: "Toshiba Shorai Edge Black",
    brand: "toshiba",
    category: "scienny",
    tagline: "Eleganckie czarne wykończenie krawędziowe z matową powłoką",
    origin: "Toshiba (Japonia)",
    description:
      "Klimatyzator ścienny Toshiba Shorai Edge Black pracuje na czynniku R32, zapewniając doskonałą wydajność w trybie chłodzenia i ogrzewania przy klasie A+++/A+++. Eleganckie czarne wykończenie z matową powłoką dodaje stylu każdemu wnętrzu. Rotacyjne sprężarki inwerterowe umożliwiają pracę w szerokim zakresie temperatur przez cały rok.",
    descriptionLong: [
      "Czarna wersja Shorai Edge to odpowiedź Toshiby na rosnące zapotrzebowanie na klimatyzatory, które są nie tylko wydajne, ale też stanowią świadomy element wystroju. Matowe czarne wykończenie krawędziowe nadaje urządzeniu charakter premium i doskonale komponuje się z ciemnymi akcentami we wnętrzach — od industrialnych loftów po minimalistyczne apartamenty. Parametry techniczne pozostają identyczne z wersją białą: SEER do 8,5 i SCOP do 5,1, klasa A+++/A+++.",
      "Jednostka wewnętrzna wyposażona jest w filtr Ultra Pure PM2.5, technologię nawiewu HADA-Care zapewniającą delikatny, nieskoncentrowany strumień powietrza, oraz powłokę Magic Coil na wymienniku ciepła, która utrudnia gromadzenie się zanieczyszczeń i pleśni. Rotacyjne sprężarki inwerterowe Toshiba są jednymi z najcichszych na rynku — poziom hałasu od 19 dB(A) pozwala na komfortowy sen bez konieczności wyłączania urządzenia.",
      "Siedem wariantów mocy od 2,0 do 7,0 kW pokrywa szeroki zakres zastosowań. Klimatyzator pracuje efektywnie w temperaturach zewnętrznych od -15°C do +46°C, co oznacza, że sprawdzi się jako źródło ciepła również w okresie przejściowym. Wbudowany moduł Wi-Fi i 5-letnia gwarancja producenta dopełniają pakiet premium.",
    ],
    highlight: "Czarny mat i A+++/A+++",
    features: [
      "Czarne matowe wykończenie krawędziowe",
      "Klasa energetyczna A+++/A+++",
      "Filtr Ultra Pure",
      "Ekologiczny czynnik R32",
      "Wbudowany moduł WiFi",
      "Rotacyjna sprężarka inwerterowa",
      "Cicha praca od 19 dB",
      "Praca w ekstremalnych temperaturach",
    ],
    advantages: [
      { title: "Czarny mat", desc: "Eleganckie matowe wykończenie pasujące do nowoczesnych wnętrz", icon: "paint-board" },
      { title: "A+++/A+++", desc: "Najwyższa klasa efektywności energetycznej w obu trybach", icon: "tick-02" },
      { title: "Ultra Pure", desc: "Zaawansowany filtr zapewniający najwyższą jakość powietrza", icon: "shield-02" },
      { title: "WiFi", desc: "Wbudowany moduł do zdalnego sterowania", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (wbudowany)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Shorai Edge Black 2,0 kW", power: "2,0 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 7012, area: "10–20 m²" },
      { name: "Shorai Edge Black 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 7488, area: "20–30 m²" },
      { name: "Shorai Edge Black 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 8438, area: "30–40 m²" },
      { name: "Shorai Edge Black 4,6 kW", power: "4,6 kW", energyClass: "A+++/A+++", noise: "22 dB", phase: "230V", price: 9576, area: "30–40 m²" },
      { name: "Shorai Edge Black 5,0 kW", power: "5,0 kW", energyClass: "A+++/A+++", noise: "24 dB", phase: "230V", price: 11160, area: "40–50 m²" },
      { name: "Shorai Edge Black 6,1 kW", power: "6,1 kW", energyClass: "A+++/A+++", noise: "26 dB", phase: "230V", price: 11980, area: "50–60 m²" },
      { name: "Shorai Edge Black 7,0 kW", power: "7,0 kW", energyClass: "A+++/A+++", noise: "28 dB", phase: "230V", price: 13010, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,0 – 7,0 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/toshiba-shorai-edge-black.png",
    imageAlt: "Klimatyzator ścienny Toshiba Shorai Edge Black",
    gallery: [
      { src: "/images/products/toshiba-shorai-edge-black-gallery-0.jpg", alt: "Toshiba Shorai Edge Black — widok z przodu" },
      { src: "/images/products/toshiba-shorai-edge-black-gallery-1.jpg", alt: "Toshiba Shorai Edge Black — widok boczny" },
      { src: "/images/products/toshiba-shorai-edge-black-gallery-2.webp", alt: "Toshiba Shorai Edge Black — aranżacja" },
    ],
  },
  {
    slug: "toshiba-haori",
    name: "Toshiba Haori",
    brand: "toshiba",
    category: "scienny",
    tagline: "Tekstylny front z personalizacją, A+++ i filtr Ultra Pure",
    origin: "Toshiba (Japonia)",
    description:
      "Klimatyzator Toshiba Haori to symbol nieograniczonych możliwości personalizacji, doskonałej wydajności oraz cichej pracy. Unikalny design z tekstylnym pokryciem frontu dostępnym w dwóch kolorach umożliwia pełną adaptację wyglądu. Klasa A+++ w trybach chłodzenia i ogrzewania, cicha praca od 19 dB, filtr Ultra Pure oraz jonizator plazmowy zapewniają czyste powietrze.",
    descriptionLong: [
      "Toshiba Haori to jedyny klimatyzator na rynku z wymiennym tekstylnym panelem przednim — rozwiązanie, które do tej pory nie istniało w żadnym innym urządzeniu tego typu. Nazwa 'haori' nawiązuje do tradycyjnego japońskiego okrycia wierzchniego, a sam koncept polega na tym, że front klimatyzatora pokryty jest tkaniną, którą można zmienić odpowiednio do wystroju pomieszczenia. W zestawie dostępne są dwa kolory — jasnoszary i ciemnoszary — ale Toshiba oferuje też dodatkowe warianty do osobnego zakupu.",
      "Pod designerską fasadą kryje się technologia najwyższej klasy. SEER 8,6 i SCOP 5,1 plasują Haori w absolutnej czołówce rynku pod względem efektywności energetycznej (klasa A+++/A+++ w obu trybach). Jednostka wewnętrzna o wymiarach 987 x 300 x 210 mm mieści filtr Ultra Pure PM2.5 wychwytujący do 94% drobnych cząstek stałych oraz jonizator plazmowy, który neutralizuje wirusy i bakterie na poziomie mikronowym.",
      "Technologia Magic Coil to specjalna powłoka na wymienniku ciepła, która utrudnia przyleganie zabrudzeń i pleśni, wydłużając okres między przeglądami serwisowymi. Funkcja Quiet redukuje hałas jednostki wewnętrznej do 19 dB(A), a jednostka zewnętrzna generuje zaledwie 37–44 dB(A) — jedne z najniższych wartości w klasie premium.",
      "Haori dostępny jest w trzech wariantach mocy: 2,5 kW, 3,5 kW i 4,6 kW, co pokrywa pomieszczenia od 20 do 50 m². Wbudowany moduł Wi-Fi, 5-letnia gwarancja producenta i ekologiczny czynnik R32 dopełniają obraz klimatyzatora, który jest tak samo piękny, jak skuteczny.",
    ],
    highlight: "Tekstylny front i A+++",
    features: [
      "Tekstylne pokrycie frontu w dwóch kolorach",
      "Klasa energetyczna A+++/A+++",
      "Filtr Toshiba Ultra Pure",
      "Jonizator plazmowy",
      "Technologia Magic Coil",
      "Ekologiczny czynnik R32",
      "Cicha praca od 19 dB",
      "Sterowanie WiFi",
    ],
    advantages: [
      { title: "Personalizacja", desc: "Tekstylny front dostępny w różnych kolorach — dopasuj do wnętrza", icon: "paint-board" },
      { title: "A+++/A+++", desc: "Najwyższa klasa efektywności energetycznej w obu trybach", icon: "tick-02" },
      { title: "Ultra Pure", desc: "Filtr i jonizator plazmowy zapewniające czyste powietrze", icon: "shield-02" },
      { title: "Magic Coil", desc: "Technologia utrzymująca czystość wymiennika ciepła", icon: "energy" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Haori 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 8042, area: "20–30 m²" },
      { name: "Haori 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 8992, area: "30–40 m²" },
      { name: "Haori 4,6 kW", power: "4,6 kW", energyClass: "A+++/A+++", noise: "22 dB", phase: "230V", price: 11627, area: "40–50 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 4,6 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/toshiba-haori.png",
    imageAlt: "Klimatyzator ścienny Toshiba Haori",
    gallery: [
      { src: "/images/products/toshiba-haori-gallery-0.jpg", alt: "Toshiba Haori — widok z przodu" },
      { src: "/images/products/toshiba-haori-gallery-1.jpg", alt: "Toshiba Haori — tekstylny front" },
      { src: "/images/products/toshiba-haori-gallery-2.jpg", alt: "Toshiba Haori — aranżacja wnętrza" },
    ],
  },
  {
    slug: "toshiba-daiseikai-9",
    name: "Toshiba Daiseikai 9",
    brand: "toshiba",
    category: "scienny",
    tagline: "Flagowy model A+++/A+++ z Plasma Ion Charger i trybem kominka",
    origin: "Toshiba (Japonia)",
    description:
      "Toshiba Daiseikai 9 to kolejny krok naprzód w świecie klimatyzacji domowej. Elegancki i nowoczesny design, klasa A+++/A+++ zapewniająca maksymalne oszczędności energii, oraz zaawansowany system filtracji Plasma Ion Charger dbający o jakość powietrza. Niesamowicie ciche działanie, rozbudowany programator tygodniowy i opcjonalne sterowanie WiFi.",
    descriptionLong: [
      "Daiseikai 9 to absolutna perła w portfolio Toshiby — model, w którym japońska precyzja inżynieryjna spotyka się z bezkompromisową efektywnością. Współczynnik SEER sięga imponujących 8,5–10,6 w zależności od wariantu mocy, a SCOP wynosi 4,6–5,2. To jedne z najwyższych wartości wśród klimatyzatorów ściennych dostępnych na polskim rynku, przekładające się na klasę energetyczną A+++ w obu trybach pracy.",
      "Podwójna sprężarka rotacyjna DC to serce urządzenia — zapewnia wyjątkową stabilność pracy i pozwala na precyzyjne utrzymanie temperatury z dokładnością do 0,5°C. System filtracji Plasma Ion Charger aktywnie oczyszcza powietrze, generując jony, które neutralizują wirusy, bakterie, pyłki i zapachy. Jednostka wewnętrzna pracuje z poziomem hałasu od zaledwie 20 dB(A), a jednostka zewnętrzna — od 43 dB(A), co jest wartością imponującą przy tak dużej wydajności.",
      "Unikalna funkcja kominka nawiewa ciepłe powietrze z dolnej krawędzi jednostki, symulując poczucie ciepła znane z tradycyjnych kominków — komfortowe rozwiązanie na chłodne wieczory. Rozbudowany programator tygodniowy pozwala zaplanować pracę klimatyzatora na każdy dzień tygodnia osobno. Nawiew 3D z automatyczną regulacją żaluzji poziomych i pionowych zapewnia równomierne rozprowadzenie powietrza.",
      "Daiseikai 9 dostępny jest w trzech wariantach mocy: 2,5 kW, 3,5 kW i 4,5 kW. Moduł Wi-Fi oferowany jest jako opcja. Czynnik R32 i 5-letnia gwarancja producenta potwierdzają, że to urządzenie stworzone z myślą o wieloletniej, bezawaryjnej eksploatacji. Wybór dla najbardziej wymagających użytkowników, którzy oczekują od klimatyzatora absolutnej ciszy, najwyższej efektywności i nieskazitelnej jakości powietrza.",
    ],
    highlight: "Flagowy A+++/A+++ z Plasma Ion",
    features: [
      "Klasa energetyczna A+++/A+++",
      "System filtracji Plasma Ion Charger",
      "Funkcja kominka",
      "Rozbudowany programator tygodniowy",
      "Ekologiczny czynnik R32",
      "Opcjonalne sterowanie WiFi",
      "Cicha praca od 20 dB",
      "Szeroki zakres pracy w różnych warunkach",
    ],
    advantages: [
      { title: "A+++/A+++", desc: "Najwyższa klasa efektywności — maksymalne oszczędności energii", icon: "tick-02" },
      { title: "Plasma Ion Charger", desc: "Zaawansowana filtracja zapewniająca czyste i zdrowe powietrze", icon: "shield-02" },
      { title: "Tryb kominka", desc: "Funkcja symulująca ciepło kominka dla dodatkowego komfortu", icon: "thermometer-01" },
      { title: "Cicha praca", desc: "Niesamowicie ciche działanie od 20 dB", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 20 dB", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalnie", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Daiseikai 9 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "20 dB", phase: "230V", price: 10735, area: "20–30 m²" },
      { name: "Daiseikai 9 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "20 dB", phase: "230V", price: 11210, area: "30–40 m²" },
      { name: "Daiseikai 9 4,5 kW", power: "4,5 kW", energyClass: "A+++/A+++", noise: "22 dB", phase: "230V", price: 12823, area: "40–50 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 4,5 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/toshiba-daiseikai-9.png",
    imageAlt: "Klimatyzator ścienny Toshiba Daiseikai 9",
    gallery: [
      { src: "/images/products/toshiba-daiseikai-9-gallery-0.jpg", alt: "Toshiba Daiseikai 9 — widok z przodu" },
      { src: "/images/products/toshiba-daiseikai-9-gallery-1.jpg", alt: "Toshiba Daiseikai 9 — widok boczny" },
      { src: "/images/products/toshiba-daiseikai-9-gallery-2.jpg", alt: "Toshiba Daiseikai 9 — szczegóły panelu" },
    ],
  },
  {
    slug: "toshiba-konsola-bi-flow",
    name: "Toshiba Konsola Bi-Flow",
    brand: "toshiba",
    category: "kanalowy",
    tagline: "Kompaktowa konsola podłogowa z dwukierunkowym nawiewem",
    origin: "Toshiba (Japonia)",
    description:
      "Klimatyzator konsola Toshiba Bi-Flow to perfekcyjne połączenie wysokiej wydajności, komfortu oraz dbałości o czyste powietrze przez cały rok. Kompaktowa konstrukcja sprawia, że doskonale nadaje się do montażu nawet w niewielkich pomieszczeniach, idealnie komponując się z przestrzenią podokienną. Klasa A++/A+ gwarantuje minimalne zużycie energii.",
    descriptionLong: [
      "Klimatyzator konsola Toshiba Bi-Flow to perfekcyjne połączenie wysokiej wydajności, komfortu oraz dbałości o czyste powietrze przez cały rok.",
      "Kompaktowa konstrukcja sprawia, że doskonale nadaje się do montażu nawet w niewielkich pomieszczeniach, idealnie komponując się z przestrzenią podokienną.",
      "Dwukierunkowy nawiew zapewnia równomierne rozprowadzenie powietrza, a klasa A++/A+ gwarantuje minimalne zużycie energii przy optymalnej temperaturze i czystości powietrza.",
    ],
    highlight: "Konsola z dwukierunkowym nawiewem",
    features: [
      "Dwukierunkowy nawiew Bi-Flow",
      "Kompaktowa konstrukcja podłogowa",
      "Klasa energetyczna A++/A+",
      "Ekologiczny czynnik R32",
      "Cicha praca od 24 dB",
      "Idealny montaż podokienny",
      "Tryb grzania i chłodzenia",
      "Sterowanie pilotem",
    ],
    advantages: [
      { title: "Bi-Flow", desc: "Dwukierunkowy nawiew zapewniający równomierne rozprowadzenie powietrza", icon: "energy" },
      { title: "Kompaktowa", desc: "Idealnie wpasowuje się w przestrzeń podokienną", icon: "home-01" },
      { title: "A++/A+", desc: "Wysoka efektywność energetyczna gwarantująca oszczędności", icon: "tick-02" },
      { title: "Cicha praca", desc: "Poziom hałasu od 24 dB — praktycznie niezauważalny", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 24 dB", icon: "volume-low" },
      { label: "Nawiew", value: "Bi-Flow", icon: "energy" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Konsola Bi-Flow 2,5 kW", power: "2,5 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 8280, area: "25–35 m²" },
      { name: "Konsola Bi-Flow 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "26 dB", phase: "230V", price: 9309, area: "25–35 m²" },
      { name: "Konsola Bi-Flow 5,0 kW", power: "5,0 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 12348, area: "25–35 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 5,0 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/toshiba-konsola-bi-flow.jpg",
    imageAlt: "Klimatyzator konsola Toshiba Bi-Flow",
    gallery: [
      { src: "/images/products/toshiba-konsola-bi-flow-gallery-0.webp", alt: "Toshiba Konsola Bi-Flow — widok z góry" },
      { src: "/images/products/toshiba-konsola-bi-flow-gallery-1.jpg", alt: "Toshiba Konsola Bi-Flow — montaż podokienny" },
      { src: "/images/products/toshiba-konsola-bi-flow-gallery-2.webp", alt: "Toshiba Konsola Bi-Flow — aranżacja" },
    ],
  },
];
