import type { Product } from "@/types";

// ═══════════════════════════════════════════════════════════════
// Products scraped from pbac.pl — AUX, Kaisai, Daikin,
// Mitsubishi Electric, Mitsubishi Heavy, GE, Rotenso
// Scraped: 2026-03-17
// ═══════════════════════════════════════════════════════════════

export const scrapedProducts: Product[] = [
  // ═══════════════════════════════════════════════
  // AUX (8 products)
  // ═══════════════════════════════════════════════
  {
    slug: "aux-q-smart",
    name: "AUX Q-Smart",
    brand: "aux",
    category: "scienny",
    tagline: "Nowoczesny design z jonizatorem i czujnikiem I Feel",
    origin: "AUX Group (Chiny)",
    description:
      "AUX Q-Smart to nowoczesny klimatyzator ścienny, który połączył w sobie najważniejsze funkcje zapewniające komfort użytkownikowi oraz wyjątkowy design będący eleganckim wykończeniem nowoczesnego wnętrza. Producent zadbał o zastosowanie rozwiązań, które pozwolą nie tylko zadbać o temperaturę powietrza, ale również jego jakość — w urządzeniu pojawiły się jonizator i dodatkowe filtry. Czujnik temperatury I Feel zastosowany w pilocie sprawia, że klimatyzacja działa wydajnie, cicho i energooszczędnie.",
    descriptionLong: [
      "AUX Q-Smart to nowoczesny klimatyzator ścienny, który połączył w sobie najważniejsze funkcje zapewniające komfort użytkownikowi oraz wyjątkowy design będący eleganckim wykończeniem nowoczesnego wnętrza.",
      "Producent zadbał o zastosowanie rozwiązań, które pozwolą nie tylko zadbać o temperaturę powietrza, ale również jego jakość — w urządzeniu pojawiły się jonizator i dodatkowe filtry.",
      "Czujnik temperatury I Feel zastosowany w pilocie sprawia, że klimatyzacja działa wydajnie, cicho i energooszczędnie.",
    ],
    highlight: "Jonizator i I Feel",
    features: [
      "Jonizator powietrza",
      "Dodatkowe filtry poprawiające jakość powietrza",
      "Czujnik temperatury I Feel w pilocie",
      "Energooszczędna praca inwerterowa",
      "Elegancki, nowoczesny design",
      "Tryb grzania i chłodzenia",
      "Sterowanie pilotem",
      "Cicha praca",
    ],
    advantages: [
      { title: "Jonizator", desc: "Wbudowany jonizator poprawiający jakość powietrza w pomieszczeniu", icon: "leaf-02" },
      { title: "I Feel", desc: "Czujnik w pilocie mierzy temperaturę tam, gdzie przebywasz", icon: "thermometer-01" },
      { title: "Nowoczesny design", desc: "Elegancka obudowa pasująca do każdego wnętrza", icon: "paint-board" },
      { title: "Filtracja", desc: "Dodatkowe filtry wychwytujące zanieczyszczenia z powietrza", icon: "shield-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 22 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Q-Smart 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 3200, area: "20–30 m²" },
      { name: "Q-Smart 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 3400, area: "30–40 m²" },
      { name: "Q-Smart 5,4 kW", power: "5,4 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 4800, area: "50–60 m²" },
      { name: "Q-Smart 6,7 kW", power: "6,7 kW", energyClass: "A++/A+", noise: "32 dB", phase: "230V", price: 6200, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 6,7 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/aux-q-smart.webp",
    imageAlt: "Klimatyzator ścienny AUX Q-Smart",
    gallery: [],
  },
  {
    slug: "aux-q-smart-premium",
    name: "AUX Q-Smart Premium",
    brand: "aux",
    category: "scienny",
    tagline: "Lampy UV, filtry PM2.5 i technologia Q-Smart w eleganckiej obudowie",
    origin: "AUX Group (Chiny)",
    description:
      "AUX Q-Smart Premium to kompaktowy klimatyzator ścienny, który zachwyca eleganckim i ponadczasowym designem, oferując jednocześnie liczne rozwiązania wpływające na komfort mieszkańców oraz jakość powietrza w pomieszczeniu. Wyposażony w lampy UV zapewniające skuteczną dezynfekcję i hamowanie rozwoju wirusów, oraz dodatkowe filtry wychwytujące cząsteczki PM2.5, bakterie i kurz.",
    descriptionLong: [
      "AUX Q-Smart Premium to dowód na to, że zaawansowana filtracja i sterylizacja powietrza nie muszą kosztować fortuny. Jednostka wewnętrzna o wymiarach 960 x 315 x 220 mm mieści w sobie imponujący arsenał technologii oczyszczania: lampę UV-C sterylizującą przepływające powietrze z wirusów i bakterii, wbudowany jonizator Cold Plasma eliminujący drobne cząsteczki kurzu, wirusy, roztocza, pyłki i pleśń, oraz filtr PM2.5 zatrzymujący do 99,9% cząsteczek smogu.",
      "Przy SEER 6,1 i SCOP 4,0 klimatyzator osiąga klasę A++ w chłodzeniu i A+ w grzaniu — solidne parametry w segmencie cenowym poniżej 4 000 zł. Gęsty filtr ze specjalną powłoką antybakteryjną oraz pozłacane lamele wymiennika ciepła zwiększają odporność na korozję i wydłużają żywotność urządzenia. Hydrofobiczne lamele aluminiowe odpychają wodę, zapobiegając gromadzeniu się wilgoci.",
      "Technologia wielokierunkowego nawiewu Q-Smart zapewnia równomierny rozkład temperatury w całym pomieszczeniu. Czujnik I Feel, umieszczony w pilocie zdalnego sterowania, mierzy temperaturę w miejscu przebywania użytkownika, a nie w pobliżu jednostki wewnętrznej — dzięki temu klimatyzator reaguje na faktyczne potrzeby, nie na zniekształcone odczyty. Urządzenie grzeje efektywnie przy temperaturze zewnętrznej do -22°C.",
      "Moduł Wi-Fi z programatorem tygodniowym w standardzie pozwala na zdalne sterowanie i automatyzację harmonogramu. Tryb czuwania zużywa zaledwie 0,3W. Funkcja Anti-Cold-Air zapobiega nawiewaniu zimnego powietrza na starcie trybu grzania. Cztery warianty mocy od 2,7 do 6,7 kW obsługują pomieszczenia od 20 do 70 m². Q-Smart Premium to jeden z najlepiej wyposażonych klimatyzatorów w swoim przedziale cenowym — idealna alternatywa dla droższych modeli premium.",
    ],
    highlight: "Lampy UV i PM2.5",
    features: [
      "Gwarancja 5 lat",
      "Obudowa odpornej na korozję jednostki zewnętrznej",
      "Autodiagnostyka",
      "Automatyczny restart",
      "Dwukierunkowy odpływ skroplin",
      "Filtr antybakteryjny",
      "Filtr o wysokiej gęstości",
      "Funkcja Anti-Cold-Air",
      "Inteligentne odszranianie",
      "Lampy UV do dezynfekcji",
      "Filtry PM2.5",
      "Technologia Q-Smart (wielokierunkowy nawiew)",
      "Czujnik I Feel",
      "Łatwy i szybki montaż",
      "Hydrofobiczne lamele aluminiowe",
      "Timer 24-godzinny",
      "Super EMC",
      "Szybkie chłodzenie/grzanie",
      "Tryb czuwania 0,3W",
      "Tryb osuszania",
      "Tryb ekonomiczny",
      "Tryb nocny",
      "Tryb TURBO",
      "Tryb wentylacji",
      "Wyświetlacz LED",
      "Pozłacane lamele wymiennika ciepła",
      "Samooczyszczanie",
      "Sterowanie przez aplikację mobilną",
    ],
    advantages: [
      { title: "Lampy UV", desc: "Skuteczna dezynfekcja powietrza i hamowanie rozwoju wirusów", icon: "sun-03" },
      { title: "Filtry PM2.5", desc: "Wychwytują cząsteczki smogu, bakterie i kurz", icon: "shield-02" },
      { title: "Q-Smart", desc: "Wielokierunkowy nawiew zapewniający równomierny rozkład temperatury", icon: "energy" },
      { title: "I Feel", desc: "Czujnik w pilocie mierzący temperaturę w miejscu przebywania", icon: "thermometer-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 20 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (aplikacja)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Q-Smart Premium 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "20 dB", phase: "230V", price: 3400, area: "20–30 m²" },
      { name: "Q-Smart Premium 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 3670, area: "30–40 m²" },
      { name: "Q-Smart Premium 5,4 kW", power: "5,4 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 5230, area: "50–60 m²" },
      { name: "Q-Smart Premium 6,7 kW", power: "6,7 kW", energyClass: "A++/A+", noise: "32 dB", phase: "230V", price: 6570, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 6,7 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/aux-q-smart-premium.png",
    imageAlt: "Klimatyzator ścienny AUX Q-Smart Premium",
    gallery: [
      { src: "/images/products/aux-q-smart-premium-gallery-0.jpg", alt: "AUX Q-Smart Premium — widok boczny" },
      { src: "/images/products/aux-q-smart-premium-gallery-1.jpg", alt: "AUX Q-Smart Premium — szczegóły" },
    ],
  },
  {
    slug: "aux-q-smart-premium-grey",
    name: "AUX Q-Smart Premium Grey",
    brand: "aux",
    category: "scienny",
    tagline: "Elegancka szarość z lampami UV i filtrami PM2.5",
    origin: "AUX Group (Chiny)",
    description:
      "AUX Q-Smart Premium Grey to kompaktowy klimatyzator ścienny, który zachwyca eleganckim i ponadczasowym designem w szarym kolorze, oferując jednocześnie liczne rozwiązania wpływające na komfort mieszkańców oraz jakość powietrza w pomieszczeniu. Wyposażony w lampy UV zapewniające skuteczną dezynfekcję i hamowanie rozwoju wirusów, oraz dodatkowe filtry wychwytujące cząsteczki PM2.5, bakterie i kurz.",
    descriptionLong: [
      "AUX Q-Smart Premium Grey to kompaktowy klimatyzator ścienny w eleganckiej szarej kolorystyce, który zachwyca ponadczasowym designem.",
      "Wyposażony w lampy UV zapewniające skuteczną dezynfekcję i hamowanie rozwoju wirusów, oraz dodatkowe filtry wychwytujące cząsteczki PM2.5, bakterie i kurz.",
      "Wielokierunkowy nawiew Q-Smart oraz czujnik temperatury I Feel zapewniają równomierny rozkład temperatury. Wysoka klasa energetyczna A++ w chłodzeniu i A+ w grzaniu.",
    ],
    highlight: "Szara elegancja",
    features: [
      "Gwarancja 5 lat",
      "Obudowa odpornej na korozję jednostki zewnętrznej",
      "Autodiagnostyka",
      "Automatyczny restart",
      "Dwukierunkowy odpływ skroplin",
      "Filtr antybakteryjny",
      "Filtr o wysokiej gęstości",
      "Funkcja Anti-Cold-Air",
      "Inteligentne odszranianie",
      "Lampy UV do dezynfekcji",
      "Filtry PM2.5",
      "Łatwy i szybki montaż",
      "Hydrofobiczne lamele aluminiowe",
      "Timer 24-godzinny",
      "Super EMC",
      "Szybkie chłodzenie/grzanie",
      "Tryb czuwania 0,3W",
      "Tryb osuszania",
      "Tryb ekonomiczny",
      "Tryb nocny",
      "Tryb TURBO",
      "Tryb wentylacji",
      "Wyświetlacz LED",
      "Pozłacane lamele wymiennika ciepła",
      "Sterowanie przez aplikację mobilną",
    ],
    advantages: [
      { title: "Szary design", desc: "Elegancka szara obudowa pasująca do nowoczesnych aranżacji", icon: "paint-board" },
      { title: "Lampy UV", desc: "Skuteczna dezynfekcja powietrza i hamowanie rozwoju wirusów", icon: "sun-03" },
      { title: "Filtry PM2.5", desc: "Wychwytują cząsteczki smogu, bakterie i kurz", icon: "shield-02" },
      { title: "Klasa A++", desc: "Wysoka efektywność energetyczna obniżająca rachunki", icon: "tick-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 20 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (aplikacja)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Q-Smart Premium Grey 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "20 dB", phase: "230V", price: 4413, area: "20–30 m²" },
      { name: "Q-Smart Premium Grey 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 4798, area: "30–40 m²" },
      { name: "Q-Smart Premium Grey 5,4 kW", power: "5,4 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 5909, area: "50–60 m²" },
      { name: "Q-Smart Premium Grey 6,7 kW", power: "6,7 kW", energyClass: "A++/A+", noise: "32 dB", phase: "230V", price: 7097, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 6,7 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/aux-q-smart-premium-grey.png",
    imageAlt: "Klimatyzator ścienny AUX Q-Smart Premium Grey",
    gallery: [],
  },
  {
    slug: "aux-halo",
    name: "AUX Halo",
    brand: "aux",
    category: "scienny",
    tagline: "Zaawansowana technologia i energooszczędność w smukłej białej obudowie",
    origin: "AUX Group (Chiny)",
    description:
      "Klimatyzator AUX Halo, wprowadzony na rynek w 2020 roku, to symbol zaawansowanej technologii i energooszczędności. Umieszczony w eleganckiej, smukłej obudowie w kolorze białym, oferuje wysoką klasę energetyczną A++ w trybie chłodzenia i A+ w trybie grzania, z poziomem hałasu od 19 dB. Wielokierunkowy nawiew zapewnia równomierny rozkład temperatury. Wyposażony w filtry PM2.5 wychwytujące szkodliwe składniki smogu oraz jonizator neutralizujący dodatkowe zanieczyszczenia. Moduł WiFi umożliwia zdalne sterowanie z dowolnego miejsca na świecie.",
    descriptionLong: [
      "Klimatyzator AUX Halo, wprowadzony na rynek w 2020 roku, to symbol zaawansowanej technologii i energooszczędności. Umieszczony w eleganckiej, smukłej obudowie w kolorze białym.",
      "Wysoka klasa energetyczna A++ w trybie chłodzenia i A+ w trybie grzania, z poziomem hałasu od zaledwie 19 dB.",
      "Wielokierunkowy nawiew zapewnia równomierny rozkład temperatury w pomieszczeniu. Filtry PM2.5 wychwytują szkodliwe składniki smogu, a jonizator neutralizuje dodatkowe zanieczyszczenia.",
      "Moduł WiFi umożliwia zdalne sterowanie z dowolnego miejsca na świecie za pomocą dedykowanej aplikacji mobilnej.",
    ],
    highlight: "Od 19 dB",
    features: [
      "Gwarancja 5 lat",
      "Obudowa odpornej na korozję jednostki zewnętrznej",
      "Autodiagnostyka",
      "Automatyczny restart",
      "Dwukierunkowy odpływ skroplin",
      "Filtr antybakteryjny",
      "Filtr o wysokiej gęstości",
      "Inteligentne odszranianie",
      "Filtry PM2.5",
      "Jonizator powietrza",
      "Moduł WiFi",
      "Łatwy i szybki montaż",
      "Hydrofobiczne lamele aluminiowe",
      "Timer 24-godzinny",
      "Super EMC",
      "Tryb czuwania 0,3W",
      "Tryb osuszania",
      "Tryb ekonomiczny",
      "Tryb nocny",
      "Tryb TURBO",
      "Tryb wentylacji",
      "Wyświetlacz LED",
      "Pozłacane lamele wymiennika ciepła",
    ],
    advantages: [
      { title: "Cisza od 19 dB", desc: "Wyjątkowo cicha praca — poniżej progu percepcji", icon: "volume-low" },
      { title: "Filtry PM2.5", desc: "Wychwytują cząsteczki smogu i zanieczyszczeń z powietrza", icon: "shield-02" },
      { title: "Jonizator", desc: "Neutralizuje dodatkowe zanieczyszczenia poprawiając jakość powietrza", icon: "leaf-02" },
      { title: "WiFi", desc: "Zdalne sterowanie przez aplikację mobilną z dowolnego miejsca", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–38 dB (wew.) / 40 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Halo 2,75 kW", power: "2,75 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 4096, area: "20–30 m²" },
      { name: "Halo 3,6 kW", power: "3,6 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 4251, area: "30–40 m²" },
      { name: "Halo 5,5 kW", power: "5,5 kW", energyClass: "A++/A+", noise: "30 dB", phase: "230V", price: 5439, area: "40–60 m²" },
      { name: "Halo 7,3 kW", power: "7,3 kW", energyClass: "A++/A+", noise: "38 dB", phase: "230V", price: 6395, area: "70–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,75 – 7,3 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/aux-halo.png",
    imageAlt: "Klimatyzator ścienny AUX Halo",
    gallery: [],
  },
  {
    slug: "aux-halo-deluxe",
    name: "AUX Halo Deluxe",
    brand: "aux",
    category: "scienny",
    tagline: "Głęboka czerń ze srebrnymi profilami i technologią 4D nawiewu",
    origin: "AUX Group (Chiny)",
    description:
      "Klimatyzator AUX Halo Deluxe, wprowadzony na rynek w 2020 roku, reprezentuje połączenie innowacyjnych technologii i nowoczesnego designu. Jednostka wewnętrzna utrzymana w głębokiej czerni zyskuje elegancki wygląd dzięki srebrnym profilom, które dyskretnie ukrywają wyloty powietrza. Zaawansowana technologia nawiewu 4D zapewnia równomierny rozkład chłodnego powietrza, a filtry PM2.5 i jonizator dbają o czystość powietrza.",
    descriptionLong: [
      "Klimatyzator AUX Halo Deluxe, wprowadzony na rynek w 2020 roku, reprezentuje połączenie innowacyjnych technologii i nowoczesnego designu, przyciągając uwagę swoim wyglądem.",
      "Jednostka wewnętrzna utrzymana w głębokiej czerni zyskuje elegancki wygląd dzięki srebrnym profilom, które dyskretnie ukrywają wyloty powietrza.",
      "Zaawansowana technologia nawiewu 4D zapewnia równomierny rozkład chłodnego powietrza w pomieszczeniu. Filtry PM2.5 i jonizator dbają o czystość powietrza.",
      "Wysoka klasa energetyczna A++ w chłodzeniu i A+ w grzaniu dzięki sprężarce rotacyjnej inwerterowej. Moduł WiFi umożliwia wygodne sterowanie zdalne.",
    ],
    highlight: "Czarny design 4D",
    features: [
      "Gwarancja 5 lat",
      "Antykorozyjna obudowa jednostki zewnętrznej",
      "Autodiagnostyka",
      "Automatyczny restart",
      "Dwukierunkowy odpływ skroplin",
      "Filtr antybakteryjny",
      "Filtr o wysokiej gęstości",
      "Inteligentne odszranianie",
      "Technologia nawiewu 4D",
      "Filtry PM2.5",
      "Jonizator powietrza",
      "Hydrofobiczne lamele aluminiowe",
      "Super EMC",
      "Tryb czuwania 0,3W",
      "Tryb osuszania",
      "Tryb ekonomiczny",
      "Tryb nocny",
      "Tryb TURBO",
      "Tryb wentylacji",
      "Wyświetlacz LED",
      "Pozłacane lamele wymiennika ciepła",
    ],
    advantages: [
      { title: "Elegancka czerń", desc: "Głęboka czerń ze srebrnymi profilami — wyjątkowy wygląd", icon: "paint-board" },
      { title: "Nawiew 4D", desc: "Zaawansowana technologia rozprowadzania powietrza w czterech kierunkach", icon: "energy" },
      { title: "Cisza od 19 dB", desc: "Bardzo cicha praca — idealna do sypialni", icon: "volume-low" },
      { title: "PM2.5 + jonizator", desc: "Podwójna ochrona powietrza przed zanieczyszczeniami", icon: "shield-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–38 dB (wew.) / 40 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Halo Deluxe 2,75 kW", power: "2,75 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 4753, area: "20–30 m²" },
      { name: "Halo Deluxe 3,6 kW", power: "3,6 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 4405, area: "30–40 m²" },
      { name: "Halo Deluxe 5,5 kW", power: "5,5 kW", energyClass: "A++/A+", noise: "30 dB", phase: "230V", price: 5979, area: "40–60 m²" },
      { name: "Halo Deluxe 7,3 kW", power: "7,3 kW", energyClass: "A++/A+", noise: "38 dB", phase: "230V", price: 6549, area: "70–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,75 – 7,3 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/aux-halo-deluxe.png",
    imageAlt: "Klimatyzator ścienny AUX Halo Deluxe — czarny z srebrnymi profilami",
    gallery: [],
  },
  {
    slug: "aux-freedom-plus",
    name: "AUX Freedom Plus",
    brand: "aux",
    category: "scienny",
    tagline: "Innowacyjny klimatyzator z Cold Plasma i czynnikiem R32",
    origin: "AUX Group (Chiny)",
    description:
      "AUX Freedom Plus to innowacyjny klimatyzator ścienny, który pojawił się na rynku w 2022 roku. Posiada nowoczesny design jednostki wewnętrznej, wyjątkowe parametry pracy dzięki zaawansowanej technologii inwerterowej i ekologicznemu czynnikowi chłodniczemu R32. System kontroli temperatury I Feel, jonizator Cold Plasma i timer 24-godzinny zapewniają pełen komfort użytkowania.",
    descriptionLong: [
      "AUX Freedom Plus to innowacyjny klimatyzator ścienny, który pojawił się na rynku w 2022 roku. Posiada nowoczesny design jednostki wewnętrznej pasujący do różnych wnętrz.",
      "Zaawansowana technologia inwerterowa i ekologiczny czynnik chłodniczy R32 zapewniają klasę energetyczną A++ w chłodzeniu i A+ w grzaniu.",
      "System kontroli temperatury I Feel, jonizator Cold Plasma i timer 24-godzinny zapewniają pełen komfort użytkowania.",
    ],
    highlight: "Cold Plasma 2022",
    features: [
      "Gwarancja 5 lat",
      "Obudowa odpornej na korozję jednostki zewnętrznej",
      "Autodiagnostyka",
      "Automatyczny restart",
      "Dwukierunkowy odpływ skroplin",
      "Filtr antybakteryjny",
      "Filtr o wysokiej gęstości",
      "Inteligentne odszranianie",
      "Jonizator Cold Plasma",
      "Czujnik temperatury I Feel",
      "Timer 24-godzinny",
      "Hydrofobiczne lamele aluminiowe",
      "Super EMC",
      "Szybkie chłodzenie/grzanie",
      "Tryb czuwania 0,3W",
      "Tryb osuszania",
      "Tryb ekonomiczny",
      "Tryb nocny",
      "Tryb TURBO",
      "Tryb wentylacji",
      "Wyświetlacz LED",
    ],
    advantages: [
      { title: "Cold Plasma", desc: "Jonizator Cold Plasma eliminuje zanieczyszczenia i alergeny", icon: "leaf-02" },
      { title: "R32", desc: "Ekologiczny czynnik chłodniczy o niskim GWP", icon: "leaf-02" },
      { title: "I Feel", desc: "Czujnik mierzący temperaturę w miejscu przebywania użytkownika", icon: "thermometer-01" },
      { title: "Cisza od 20 dB", desc: "Bardzo cicha praca jednostki wewnętrznej", icon: "volume-low" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "20–32 dB (wew.) / 40 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalny", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Freedom Plus 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "20 dB", phase: "230V", price: 3711, area: "20–30 m²" },
      { name: "Freedom Plus 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 3788, area: "30–40 m²" },
      { name: "Freedom Plus 5,1 kW", power: "5,1 kW", energyClass: "A++/A+", noise: "28 dB", phase: "230V", price: 4744, area: "40–60 m²" },
      { name: "Freedom Plus 6,7 kW", power: "6,7 kW", energyClass: "A++/A+", noise: "32 dB", phase: "230V", price: 5701, area: "60–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 6,7 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/aux-freedom-plus.png",
    imageAlt: "Klimatyzator ścienny AUX Freedom Plus",
    gallery: [],
  },
  {
    slug: "aux-j-smart",
    name: "AUX J-Smart",
    brand: "aux",
    category: "scienny",
    tagline: "Minimalistyczny design z pionowymi lamelami i Cold Plasma",
    origin: "AUX Group (Chiny)",
    description:
      "Klimatyzator AUX J-Smart to połączenie nowoczesnych technologii i eleganckiego designu. Minimalistyczna obudowa jest odporna na uszkodzenia mechaniczne i łatwa w czyszczeniu. Technologia inwerterowa zapewnia wysoką wydajność przy jednoczesnym oszczędzaniu energii, z klasą A++ w chłodzeniu i A+ w grzaniu. Pracuje w ekstremalnie niskich temperaturach do -20°C. Innowacyjne pionowe lamele w kształcie rybiej płetwy zapewniają o 10% większy zasięg dystrybucji powietrza. Wyposażony w filtr PM2.5 i technologię jonizacji Cold Plasma.",
    descriptionLong: [
      "Klimatyzator AUX J-Smart to połączenie nowoczesnych technologii i eleganckiego designu. Minimalistyczna obudowa jest odporna na uszkodzenia mechaniczne i łatwa w czyszczeniu.",
      "Technologia inwerterowa zapewnia wysoką wydajność przy jednoczesnym oszczędzaniu energii, z klasą A++ w chłodzeniu i A+ w grzaniu.",
      "Pracuje w ekstremalnie niskich temperaturach do -20°C, co czyni go idealnym rozwiązaniem na cały rok.",
      "Innowacyjne pionowe lamele w kształcie rybiej płetwy zapewniają o 10% większy zasięg dystrybucji powietrza. Wyposażony w filtr PM2.5 i technologię jonizacji Cold Plasma eliminującą zanieczyszczenia.",
    ],
    highlight: "Praca do -20°C",
    features: [
      "Gwarancja 5 lat",
      "Antykorozyjna obudowa jednostki zewnętrznej",
      "Autodiagnostyka",
      "Automatyczny restart",
      "Dwukierunkowy odpływ skroplin",
      "Filtr antybakteryjny",
      "Filtr o wysokiej gęstości",
      "Filtr PM2.5",
      "Jonizacja Cold Plasma",
      "Inteligentne odszranianie",
      "Pionowe lamele rybie-płetwowe (+10% zasięgu)",
      "Praca do -20°C",
      "Łatwy i szybki montaż",
      "Hydrofobiczne lamele aluminiowe",
      "Timer 24-godzinny",
      "Super EMC",
      "Szybkie chłodzenie/grzanie",
      "Tryb czuwania 0,3W",
      "Tryb osuszania",
      "Tryb ekonomiczny",
      "Tryb nocny",
      "Tryb TURBO",
      "Tryb wentylacji",
      "Wyświetlacz LED",
      "Pozłacane lamele wymiennika ciepła",
    ],
    advantages: [
      { title: "Do -20°C", desc: "Efektywne grzanie nawet w ekstremalnych warunkach zimowych", icon: "thermometer-01" },
      { title: "Lamele rybie", desc: "Pionowe lamele zwiększające zasięg nawiewu o 10%", icon: "energy" },
      { title: "Cold Plasma", desc: "Technologia jonizacji eliminująca zanieczyszczenia z powietrza", icon: "leaf-02" },
      { title: "PM2.5", desc: "Filtr wychwytujący cząsteczki smogu i pyłu zawieszonego", icon: "shield-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–38 dB (wew.) / 40 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalny", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "J-Smart 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 4200, area: "20–30 m²" },
      { name: "J-Smart 3,6 kW", power: "3,6 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 4310, area: "30–40 m²" },
      { name: "J-Smart 5,4 kW", power: "5,4 kW", energyClass: "A++/A+", noise: "30 dB", phase: "230V", price: 5620, area: "40–60 m²" },
      { name: "J-Smart 7,2 kW", power: "7,2 kW", energyClass: "A++/A+", noise: "38 dB", phase: "230V", price: 6645, area: "70–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,2 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/aux-j-smart.png",
    imageAlt: "Klimatyzator ścienny AUX J-Smart",
    gallery: [],
  },
  {
    slug: "aux-j-smart-art",
    name: "AUX J-Smart ART",
    brand: "aux",
    category: "scienny",
    tagline: "Czarny design z opatentowanymi lamelami i Cold Plasma",
    origin: "AUX Group (Chiny)",
    description:
      "AUX J-Smart ART to nowoczesna propozycja marki z 2020 roku. Klimatyzator ścienny wyróżnia się unikatowym, nowoczesnym wzornictwem oraz innowacyjnymi rozwiązaniami konstrukcyjnymi. Smukła obudowa w eleganckim czarnym kolorze dodaje szyku każdej przestrzeni. Wysoka wydajność energetyczna z klasą A++ w chłodzeniu i A+ w grzaniu, praca do -20°C. Opatentowane lamele w kształcie rybiej płetwy zmniejszają opór powietrza i zwiększają zasięg dystrybucji o ok. 10%. Technologia jonizacji Cold Plasma i filtr PM2.5 oczyszczają powietrze.",
    descriptionLong: [
      "AUX J-Smart ART to nowoczesna propozycja marki, której premiera miała miejsce w 2020 roku. Klimatyzator ścienny wyróżnia się unikatowym, nowoczesnym wzornictwem oraz innowacyjnymi rozwiązaniami konstrukcyjnymi.",
      "Smukła obudowa w eleganckim czarnym kolorze dodaje szyku każdej przestrzeni, a wysoka wydajność energetyczna z klasą A++ w chłodzeniu i A+ w grzaniu obniża rachunki za prąd.",
      "Pracuje efektywnie w temperaturach do -20°C. Opatentowane lamele w kształcie rybiej płetwy zmniejszają opór powietrza i zwiększają zasięg dystrybucji o ok. 10%.",
      "Technologia jonizacji Cold Plasma i zintegrowany filtr PM2.5 neutralizują zanieczyszczenia, zapewniając czyste i zdrowe powietrze.",
    ],
    highlight: "Czarny art design",
    features: [
      "Gwarancja 5 lat",
      "Antykorozyjna obudowa jednostki zewnętrznej",
      "Autodiagnostyka",
      "Automatyczny restart",
      "Dwukierunkowy odpływ skroplin",
      "Filtr antybakteryjny",
      "Filtr o wysokiej gęstości",
      "Filtr PM2.5",
      "Jonizacja Cold Plasma",
      "Inteligentne odszranianie",
      "Opatentowane lamele rybie-płetwowe (+10% zasięgu)",
      "Praca do -20°C",
      "Elegancka czarna obudowa",
      "Łatwy i szybki montaż",
      "Hydrofobiczne lamele aluminiowe",
      "Timer 24-godzinny",
      "Super EMC",
      "Szybkie chłodzenie/grzanie",
      "Tryb czuwania 0,3W",
      "Tryb osuszania",
      "Tryb ekonomiczny",
      "Tryb nocny",
      "Tryb TURBO",
      "Tryb wentylacji",
      "Wyświetlacz LED",
      "Pozłacane lamele wymiennika ciepła",
    ],
    advantages: [
      { title: "Czarny ART design", desc: "Elegancka smukła obudowa w kolorze czarnym — wyjątkowy akcent wnętrza", icon: "paint-board" },
      { title: "Do -20°C", desc: "Efektywne grzanie nawet w ekstremalnych warunkach zimowych", icon: "thermometer-01" },
      { title: "Cold Plasma", desc: "Zaawansowana jonizacja eliminująca alergeny i zanieczyszczenia", icon: "leaf-02" },
      { title: "Lamele +10%", desc: "Opatentowane lamele rybie zwiększające zasięg nawiewu", icon: "energy" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–38 dB (wew.) / 40 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalny", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "J-Smart ART 2,7 kW", power: "2,7 kW", energyClass: "A++/A+", noise: "19 dB", phase: "230V", price: 4143, area: "20–30 m²" },
      { name: "J-Smart ART 3,6 kW", power: "3,6 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 4220, area: "30–40 m²" },
      { name: "J-Smart ART 5,4 kW", power: "5,4 kW", energyClass: "A++/A+", noise: "30 dB", phase: "230V", price: 5716, area: "40–60 m²" },
      { name: "J-Smart ART 7,2 kW", power: "7,2 kW", energyClass: "A++/A+", noise: "38 dB", phase: "230V", price: 6441, area: "70–90 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,7 – 7,2 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/aux-j-smart-art.png",
    imageAlt: "Klimatyzator ścienny AUX J-Smart ART — czarny",
    gallery: [],
  },

  // ═══════════════════════════════════════════════
  // KAISAI (4 products)
  // ═══════════════════════════════════════════════
  {
    slug: "kaisai-fly",
    name: "Kaisai Fly",
    brand: "kaisai",
    category: "scienny",
    tagline: "Filtr zimnokatalityczny i Bio HEPA — czyste powietrze w przystępnej cenie",
    origin: "Kaisai (Grupa Midea / dystrybucja Klima-Therm)",
    description:
      "Kaisai Fly to nowoczesny klimatyzator ścienny łączący funkcjonalność i najwyższą jakość technologii. Filtr zimnokatalityczny skutecznie neutralizuje tlenek węgla, siarkowodór i amoniak. Filtr Bio HEPA usuwa do 99% cząsteczek kurzu, bakterii i 95% cząsteczek 0,1–0,3 μm, w tym grzybów i wirusów. Grzanie do -25°C, wbudowany moduł WiFi z aplikacją mobilną, samooczyszczanie parownika, czujnik Follow Me i nawiew 3D.",
    descriptionLong: [
      "Kaisai Fly z grupy Klima-Therm to klimatyzator, który zaskakuje zakresem wyposażenia w swojej klasie cenowej. Przy współczynnikach SEER 7,0 i SCOP 4,1 (wariant 2,6 kW) osiąga solidne parametry energetyczne, ale jego prawdziwą siłą jest zaawansowany system filtracji powietrza — rzadko spotykany w modelach poniżej 4 500 zł.",
      "Filtr zimnokatalityczny skutecznie neutralizuje szkodliwe gazy: tlenek węgla, siarkowodór, amoniak, benzen i formaldehyd — substancje, które mogą uwalniać się z mebli, farb i materiałów wykończeniowych. Filtr Bio HEPA usuwa do 99% cząsteczek kurzu i bakterii o rozmiarze 0,3 μm oraz 95% cząsteczek 0,1–0,3 μm, w tym grzybów i wirusów. W połączeniu z opcjonalnymi filtrami 3M, srebrnymi jonowymi i witaminowymi C, Kaisai Fly tworzy wielowarstwowy system oczyszczania powietrza.",
      "Klimatyzator pracuje w szerokim zakresie temperatur: chłodzenie od -15°C do +50°C, grzanie od -25°C do +30°C. Funkcja stałego ogrzewania 8°C nie dopuszcza do wyziębienia pomieszczeń w nieużywanych domach czy apartamentach wakacyjnych. Czujnik Follow Me, umieszczony w pilocie, mierzy temperaturę w miejscu przebywania użytkownika — nie przy klimatyzatorze — co pozwala na precyzyjne utrzymanie komfortu termicznego.",
      "Wbudowany moduł Wi-Fi, samooczyszczanie parownika zapobiegające rozwojowi pleśni, nawiew 3D i tryb Turbo do szybkiego schładzania. Cztery warianty mocy od 2,6 do 7,0 kW. Kaisai Fly to idealna propozycja dla osób szukających zaawansowanej filtracji powietrza i niezawodności w przystępnej cenie — bez zbędnych kompromisów.",
    ],
    highlight: "Bio HEPA 99%",
    features: [
      "Autodiagnostyka",
      "Automatyczny restart",
      "Tryb awaryjny",
      "Czujnik temperatury w pilocie (Follow Me)",
      "Filtr zimnokatalityczny",
      "Filtr Bio HEPA",
      "Samooczyszczanie parownika",
      "Stałe ogrzewanie 8°C",
      "Nawiew 3D",
      "Grzanie do -25°C",
      "Wbudowany WiFi z aplikacją",
      "Tryb nocny (Sleep)",
      "Pamięć ustawień żaluzji",
      "Timer programowalny",
      "Tryb czuwania (Standby)",
      "Tryb Turbo",
      "Wielofunkcyjny pilot",
      "Systemy mono i multi",
      "Filtr 3M (opcja)",
      "Filtr srebrny jonowy (opcja)",
      "Filtr witaminowy C (opcja)",
    ],
    advantages: [
      { title: "Bio HEPA", desc: "Filtr usuwający 99% kurzu i bakterii oraz 95% wirusów i grzybów", icon: "shield-02" },
      { title: "Zimnokatalityczny", desc: "Neutralizuje tlenek węgla, siarkowodór, amoniak, benzen i formaldehyd", icon: "leaf-02" },
      { title: "Do -25°C", desc: "Efektywne grzanie nawet w ekstremalnych warunkach zimowych", icon: "thermometer-01" },
      { title: "Follow Me", desc: "Czujnik w pilocie mierzący temperaturę w miejscu przebywania", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "21–38 dB (wew.) / 55 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Tak (wbudowany)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata", icon: "shield-02" },
    ],
    models: [
      { name: "Fly 2,6 kW", power: "2,6 kW", energyClass: "A/A++", noise: "21 dB", phase: "230V", price: 3873, area: "20–30 m²" },
      { name: "Fly 3,5 kW", power: "3,5 kW", energyClass: "A/A++", noise: "24 dB", phase: "230V", price: 4027, area: "30–40 m²" },
      { name: "Fly 5,3 kW", power: "5,3 kW", energyClass: "A/A++", noise: "32 dB", phase: "230V", price: 5331, area: "40–60 m²" },
      { name: "Fly 7,0 kW", power: "7,0 kW", energyClass: "A/A++", noise: "38 dB", phase: "230V", price: 6326, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 7,0 kW",
    warranty: "3 lata gwarancji",
    imageUrl: "/images/products/kaisai-fly.png",
    imageAlt: "Klimatyzator ścienny Kaisai Fly",
    gallery: [
      { src: "/images/products/kaisai-fly-gallery-0.webp", alt: "Kaisai Fly — widok boczny" },
      { src: "/images/products/kaisai-fly-gallery-1.webp", alt: "Kaisai Fly — filtry" },
      { src: "/images/products/kaisai-fly-gallery-2.jpg", alt: "Kaisai Fly — jednostka wewnętrzna" },
      { src: "/images/products/kaisai-fly-gallery-3.jpg", alt: "Kaisai Fly — specyfikacja" },
      { src: "/images/products/kaisai-fly-gallery-4.webp", alt: "Kaisai Fly — nawiew 3D" },
    ],
  },
  {
    slug: "kaisai-ice-white",
    name: "Kaisai Ice White",
    brand: "kaisai",
    category: "scienny",
    tagline: "Klasa A+++ z jonizacją i trybami ECO i GEAR",
    origin: "Kaisai (Grupa Midea / dystrybucja Klima-Therm)",
    description:
      "Kaisai Ice White to klimatyzator ścienny o eleganckim, nowoczesnym designie w kolorze białym, gwarantujący najwyższą klasę energooszczędności A+++. Funkcja jonizacji powietrza eliminuje roztocza, pleśń, bakterie i wirusy, jednocześnie nawilżając powietrze. Opcjonalny filtr Bio HEPA usuwa zanieczyszczenia i mikroorganizmy. Standardowy moduł WiFi umożliwia zdalne sterowanie 24/7. Tryby ECO i GEAR oraz nawiew 3D optymalizują cyrkulację i rozkład temperatury.",
    descriptionLong: [
      "Kaisai Ice White to jeden z najpopularniejszych klimatyzatorów w Polsce — i nie bez powodu. Klasa energetyczna A+++ w chłodzeniu przy cenie poniżej 4 500 zł czyni go jedną z najbardziej opłacalnych propozycji na rynku. Dystrybuowany przez Klima-Therm (Grupa Midea), korzysta z globalnego know-how jednego z największych producentów urządzeń HVAC na świecie. Poziom hałasu od 19 dB(A) zapewnia komfort nawet w sypialniach.",
      "Funkcja jonizacji powietrza generuje jony ujemne, które przyczepiają się do roztoczy, pleśni, bakterii i wirusów, powodując ich opadanie na podłogę i skuteczne usunięcie z powietrza. Opcjonalny filtr Bio HEPA (dostępny jako akcesorium) wychwytuje 99% cząsteczek 0,3 μm i 95% cząsteczek 0,1–0,3 μm. System sygnalizacji wycieku czynnika chłodniczego zwiększa bezpieczeństwo eksploatacji.",
      "Tryb ECO automatycznie redukuje zużycie energii w momentach mniejszego obciążenia cieplnego, a tryb GEAR pozwala na ręczne ustawienie intensywności pracy wentylatora z płynną regulacją. Nawiew 3D (sterowanie żaluzją w pionie i poziomie) zapewnia równomierny rozkład temperatury w całym pomieszczeniu. Samooczyszczanie parownika zapobiega gromadzeniu się wilgoci i pleśni.",
      "Wbudowany moduł Wi-Fi umożliwia zdalne sterowanie 24/7 z poziomu aplikacji mobilnej. Cztery warianty mocy od 2,6 do 7,0 kW obsługują pomieszczenia od 20 do 70 m². Ice White to klimatyzator, który udowadnia, że wysoka klasa energetyczna i bogate wyposażenie nie muszą oznaczać wysokiej ceny.",
    ],
    highlight: "A+++ jonizacja",
    features: [
      "Jonizacja powietrza",
      "Autodiagnostyka i restart",
      "Tryb awaryjny",
      "Czujnik temperatury w pilocie",
      "Tryb ECO",
      "Tryb GEAR",
      "Tryb nocny (Sleep)",
      "Samooczyszczanie parownika",
      "Sygnalizacja wycieku czynnika",
      "Szeroki zakres temperatur pracy",
      "Tryb czuwania",
      "Tryb Turbo",
      "Wielofunkcyjny pilot",
      "Timer programowalny",
      "Praca w niskich temperaturach zewnętrznych",
      "Prosty montaż",
      "Pamięć ustawień żaluzji",
      "Płynna regulacja wentylatora",
      "Systemy mono i multi",
      "Filtr Bio HEPA (opcja)",
      "Nawiew 3D",
      "Wbudowany WiFi",
    ],
    advantages: [
      { title: "A+++", desc: "Najwyższa klasa energetyczna zapewniająca najniższe rachunki", icon: "tick-02" },
      { title: "Jonizacja", desc: "Eliminacja roztoczy, pleśni, bakterii i wirusów z powietrza", icon: "leaf-02" },
      { title: "ECO + GEAR", desc: "Ekonomiczne tryby pracy optymalizujące zużycie energii", icon: "energy" },
      { title: "WiFi standard", desc: "Zdalne sterowanie 24/7 z aplikacji mobilnej w standardzie", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–37 dB (wew.) / 54 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Tak (standardowy)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata", icon: "shield-02" },
    ],
    models: [
      { name: "Ice White 2,6 kW", power: "2,6 kW", energyClass: "A+++/A+", noise: "19 dB", phase: "230V", price: 4490, area: "20–30 m²" },
      { name: "Ice White 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+", noise: "22 dB", phase: "230V", price: 4644, area: "30–40 m²" },
      { name: "Ice White 5,3 kW", power: "5,3 kW", energyClass: "A+++/A+", noise: "30 dB", phase: "230V", price: 6102, area: "40–60 m²" },
      { name: "Ice White 7,0 kW", power: "7,0 kW", energyClass: "A+++/A+", noise: "37 dB", phase: "230V", price: 7444, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 7,0 kW",
    warranty: "3 lata gwarancji",
    imageUrl: "/images/products/kaisai-ice-white.png",
    imageAlt: "Klimatyzator ścienny Kaisai Ice White",
    gallery: [],
  },
  {
    slug: "kaisai-ice-black",
    name: "Kaisai Ice Black",
    brand: "kaisai",
    category: "scienny",
    tagline: "Elegancki czarny panel z klasą A+++ i jonizacją",
    origin: "Kaisai (Grupa Midea / dystrybucja Klima-Therm)",
    description:
      "Kaisai Ice Black to zaawansowany klimatyzator ścienny wyróżniający się eleganckim panelem w kolorze czarnym. Najwyższa klasa efektywności energetycznej A+++ w chłodzeniu i A++ w grzaniu. Funkcja jonizacji powietrza eliminuje roztocza, pleśń, bakterie i wirusy, jednocześnie nawilżając powietrze. Filtr Bio HEPA skutecznie wychwytuje cząsteczki zanieczyszczeń. Wbudowany WiFi, tryby ECO i GEAR, nawiew 3D.",
    descriptionLong: [
      "Czarna wersja Kaisai Ice podnosi poprzeczkę pod względem zarówno designu, jak i efektywności energetycznej. Elegancki czarny panel doskonale wpisuje się we wnętrza z ciemnymi akcentami — industrialne lofty, gabinety i nowoczesne salony. Klasa A+++ w chłodzeniu i A++ w grzaniu to krok wyżej niż biała wersja Ice, co przekłada się na jeszcze niższe rachunki za energię. Hałas od 19 dB(A) na najniższym biegu wentylatora.",
      "Technologia jest identyczna jak w wersji białej, ale Ice Black oferuje nieco wyższe parametry energetyczne. Jonizacja powietrza, opcjonalny filtr Bio HEPA, samooczyszczanie parownika i sygnalizacja wycieku czynnika — pełen pakiet funkcji dbających o bezpieczeństwo i jakość powietrza. Możliwość zamontowania dodatkowych filtrów: 3M, srebrnego jonowego, witaminowego C i modułu MFB pozwala dostosować urządzenie do indywidualnych potrzeb.",
      "Tryby ECO i GEAR umożliwiają optymalizację zużycia energii w zależności od sytuacji — od maksymalnej wydajności po maksymalną oszczędność. Nawiew 3D z pamięcią ustawień żaluzji i płynna regulacja wentylatora zapewniają precyzyjną kontrolę nad dystrybucją powietrza. Wbudowany Wi-Fi pozwala na zdalne sterowanie z aplikacji mobilnej, a timer programowalny automatyzuje harmonogram pracy.",
      "Ice Black jest dostępny w czterech wariantach mocy od 2,6 do 7,0 kW. W zestawieniu z konkurencyjnym Gree Clivia Silver oferuje niższą cenę przy porównywalnej klasie energetycznej, co czyni go jedną z najlepszych propozycji w segmencie czarnych klimatyzatorów premium w przystępnej cenie.",
    ],
    highlight: "Czarny A+++",
    features: [
      "Autodiagnostyka",
      "Automatyczny restart",
      "Tryb awaryjny",
      "Czujnik temperatury w pilocie",
      "Tryb ECO",
      "Tryb GEAR",
      "Jonizacja powietrza",
      "Filtr Bio HEPA (opcja)",
      "Filtr 3M (opcja)",
      "Filtr srebrny jonowy (opcja)",
      "Filtr witaminowy C (opcja)",
      "Moduł MFB (opcja)",
      "Tryb nocny (Sleep)",
      "Samooczyszczanie parownika",
      "Sygnalizacja wycieku czynnika",
      "Tryb czuwania",
      "Tryb Turbo",
      "Wielofunkcyjny pilot",
      "Timer programowalny",
      "Prosty montaż",
      "Pamięć ustawień żaluzji",
      "Płynna regulacja wentylatora",
      "Systemy mono i multi",
      "Nawiew 3D",
      "Wbudowany WiFi",
    ],
    advantages: [
      { title: "Czarny A+++", desc: "Elegancki czarny panel z najwyższą klasą energetyczną", icon: "paint-board" },
      { title: "Jonizacja", desc: "Eliminacja roztoczy, pleśni, bakterii i wirusów z powietrza", icon: "leaf-02" },
      { title: "A+++/A++", desc: "Najwyższa klasa w chłodzeniu i grzaniu", icon: "tick-02" },
      { title: "WiFi + 3D", desc: "Zdalne sterowanie i trójwymiarowy nawiew w standardzie", icon: "wifi-full-signal" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–37 dB (wew.) / 54 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Tak (wbudowany)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata", icon: "shield-02" },
    ],
    models: [
      { name: "Ice Black 2,6 kW", power: "2,6 kW", energyClass: "A+++/A++", noise: "19 dB", phase: "230V", price: 4682, area: "20–30 m²" },
      { name: "Ice Black 3,5 kW", power: "3,5 kW", energyClass: "A+++/A++", noise: "22 dB", phase: "230V", price: 4836, area: "30–40 m²" },
      { name: "Ice Black 5,3 kW", power: "5,3 kW", energyClass: "A+++/A++", noise: "30 dB", phase: "230V", price: 6333, area: "40–60 m²" },
      { name: "Ice Black 7,0 kW", power: "7,0 kW", energyClass: "A+++/A++", noise: "37 dB", phase: "230V", price: 7521, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 7,0 kW",
    warranty: "3 lata gwarancji",
    imageUrl: "/images/products/kaisai-ice-black.png",
    imageAlt: "Klimatyzator ścienny Kaisai Ice Black — czarny panel",
    gallery: [
      { src: "/images/products/kaisai-ice-black-gallery-0.webp", alt: "Kaisai Ice Black — widok szczegółowy" },
    ],
  },
  {
    slug: "kaisai-geo",
    name: "Kaisai Geo",
    brand: "kaisai",
    category: "scienny",
    tagline: "A+++ z filtrem zimnokatalitycznym, Bio HEPA i jonizacją",
    origin: "Kaisai (Grupa Midea / dystrybucja Klima-Therm)",
    description:
      "Kaisai Geo to klimatyzator ścienny łączący nowoczesną estetykę z wyjątkową efektywnością energetyczną — klasa A+++ w chłodzeniu i A++ w grzaniu. Filtr zimnokatalityczny usuwa substancje chemiczne, w tym tlenek węgla, siarkowodór, amoniak, benzen i formaldehyd. Filtr Bio HEPA wychwytuje 99% cząsteczek kurzu i bakterii (0,3 μm) oraz 95% cząsteczek 0,1–0,3 μm. Jonizacja powietrza, standardowy moduł WiFi i nawiew 3D.",
    descriptionLong: [
      "Kaisai Geo to klimatyzator ścienny łączący nowoczesną estetykę z wyjątkową efektywnością energetyczną — klasa A+++ w chłodzeniu i A++ w grzaniu.",
      "Filtr zimnokatalityczny usuwa substancje chemiczne, w tym tlenek węgla, siarkowodór, amoniak, benzen i formaldehyd. Filtr Bio HEPA wychwytuje 99% cząsteczek kurzu i bakterii (0,3 μm) oraz 95% cząsteczek 0,1–0,3 μm, w tym grzybów i wirusów.",
      "Funkcja jonizacji powietrza eliminuje roztocza, pleśń, bakterie i wirusy, jednocześnie nawilżając powietrze. Standardowy moduł WiFi umożliwia zdalne sterowanie 24/7.",
      "Nawiew 3D zwiększa efektywność dystrybucji powietrza, zapewniając optymalną cyrkulację i równomierny rozkład temperatury w pomieszczeniu.",
    ],
    highlight: "A+++ Bio HEPA",
    features: [
      "Autodiagnostyka",
      "Automatyczny restart",
      "Tryb awaryjny",
      "Czujnik temperatury w pilocie",
      "Tryb ECO",
      "Filtr zimnokatalityczny",
      "Filtr Bio HEPA",
      "Jonizacja powietrza",
      "Filtr 3M (opcja)",
      "Filtr srebrny jonowy (opcja)",
      "Filtr witaminowy C (opcja)",
      "Tryb nocny (Sleep)",
      "Samooczyszczanie parownika",
      "Sygnalizacja wycieku czynnika",
      "Tryb czuwania",
      "Tryb Turbo",
      "Wielofunkcyjny pilot",
      "Timer programowalny",
      "Pamięć ustawień żaluzji",
      "Płynna regulacja wentylatora",
      "Systemy mono i multi",
      "Nawiew 3D",
      "Wbudowany WiFi (standard)",
    ],
    advantages: [
      { title: "A+++/A++", desc: "Najwyższa klasa energetyczna w chłodzeniu i grzaniu", icon: "tick-02" },
      { title: "Zimnokatalityczny", desc: "Filtr eliminujący substancje chemiczne i formaldehyd", icon: "shield-02" },
      { title: "Bio HEPA 99%", desc: "Wychwytuje 99% kurzu i bakterii o rozmiarze 0,3 μm", icon: "leaf-02" },
      { title: "Jonizacja + 3D", desc: "Jonizacja powietrza z trójwymiarowym nawiewem", icon: "energy" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "21–39 dB (wew.) / 54 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Tak (standardowy)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata", icon: "shield-02" },
    ],
    models: [
      { name: "Geo 2,6 kW", power: "2,6 kW", energyClass: "A+++/A++", noise: "21 dB", phase: "230V", price: 4644, area: "20–30 m²" },
      { name: "Geo 3,5 kW", power: "3,5 kW", energyClass: "A+++/A++", noise: "24 dB", phase: "230V", price: 5801, area: "30–40 m²" },
      { name: "Geo 5,3 kW", power: "5,3 kW", energyClass: "A+++/A++", noise: "32 dB", phase: "230V", price: 5909, area: "40–60 m²" },
      { name: "Geo 7,0 kW", power: "7,0 kW", energyClass: "A+++/A++", noise: "39 dB", phase: "230V", price: 7066, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 7,0 kW",
    warranty: "3 lata gwarancji",
    imageUrl: "/images/products/kaisai-geo.png",
    imageAlt: "Klimatyzator ścienny Kaisai Geo",
    gallery: [],
  },

  // ═══════════════════════════════════════════════
  // DAIKIN (1 product)
  // ═══════════════════════════════════════════════
  {
    slug: "daikin-stylish-white",
    name: "Daikin Stylish White",
    brand: "daikin",
    category: "scienny",
    tagline: "Nagrodzony design z A+++ i technologią Coanda",
    origin: "Daikin (Japonia)",
    description:
      "Daikin Stylish White to klimatyzacja ścienna o unikalnym designie nagrodzonym Good Design Award 2017 oraz IF DESIGN AWARD. Białe matowe wykończenie, najwyższa klasa efektywności A+++ zarówno w chłodzeniu, jak i grzaniu, ekologiczny czynnik R32. Technologia Flash Streamer jonizuje powietrze i neutralizuje mikroorganizmy. Matrycowy czujnik ciepła dzieli pomieszczenie na 64 strefy dla precyzyjnej kontroli. Efekt Coanda zapewnia optymalny rozkład powietrza. Cisza od 19 dB.",
    descriptionLong: [
      "Daikin Stylish to jeden z najbardziej rozpoznawalnych klimatyzatorów na świecie — podwójnie nagrodzony za design (Good Design Award 2017, IF Design Award 2018) i ceniony przez architektów wnętrz za smukłą, niemal płaską obudowę o głębokości zaledwie 189 mm. Biała wersja z matowym wykończeniem stanowi subtelny, elegancki element wystroju, który nie przyciąga uwagi — w przeciwieństwie do masywnych, plastikowych jednostek konkurencji.",
      "Japońska precyzja inżynieryjna przekłada się na imponujące współczynniki: SEER 8,73–8,75 i SCOP do 5,1 w zależności od wariantu mocy, co zapewnia najwyższą klasę energetyczną A+++ zarówno w chłodzeniu, jak i grzaniu. Daikin jest jedynym producentem klimatyzatorów, który sam wytwarza sprężarki i czynnik chłodniczy — pełna kontrola nad łańcuchem produkcyjnym przekłada się na wyjątkową niezawodność i spójność parametrów.",
      "Matrycowy czujnik ciepła Intelligent Eye dzieli pomieszczenie na 64 strefy temperaturowe, wykrywając różnice cieplne i obecność osób z niespotykaną precyzją. Na tej podstawie system automatycznie zarządza wielokierunkowym nawiewem, wykorzystując efekt Coanda — strumień powietrza przylega do sufitu i delikatnie opada, eliminując uczucie przeciągu. Technologia Flash Streamer generuje elektrony o dużej energii, które neutralizują alergeny, pleśń, wirusy i zapachy w przepływającym powietrzu.",
      "Stylish White jest dostępny w wariantach 2,5 kW, 3,5 kW i 5,0 kW. Cisza od 19 dB(A) czyni go jednym z najcichszych klimatyzatorów premium na rynku. Programator tygodniowy pozwala zaplanować pracę na każdy dzień osobno. Moduł Wi-Fi dostępny jako opcja. To urządzenie klasy absolutnie premium — dla tych, którzy nie akceptują kompromisów między estetyką, efektywnością i jakością powietrza.",
    ],
    highlight: "Design Award A+++",
    features: [
      "Gwarancja 3 lata",
      "Autodiagnostyka",
      "Automatyczna prędkość wentylatora",
      "Automatyczny restart",
      "Automatyczne przełączanie chłodzenie/grzanie",
      "Cicha praca jednostki wewnętrznej",
      "Cicha praca jednostki zewnętrznej",
      "Nawiew 3D",
      "Tryb nocny (Sleep)",
      "Program osuszania",
      "Timer tygodniowy programowalny",
      "Sterowanie centralne",
      "Opcjonalny pilot przewodowy",
      "Regulacja prędkości wentylatora",
      "Systemy multi",
      "Tryb ekonomiczny",
      "Tryb komfort",
      "Tryb Power",
      "Tryb ustawień nocnych",
      "Tryb wentylacji",
      "Pilot bezprzewodowy",
      "Technologia Flash Streamer",
      "Matrycowy czujnik ciepła (64 strefy)",
      "Efekt Coanda",
    ],
    advantages: [
      { title: "Design Award", desc: "Good Design Award 2017 i IF DESIGN AWARD za wyjątkowe wzornictwo", icon: "paint-board" },
      { title: "A+++/A+++", desc: "Najwyższa klasa zarówno w chłodzeniu, jak i grzaniu", icon: "tick-02" },
      { title: "Flash Streamer", desc: "Jonizacja neutralizująca mikroorganizmy i alergeny", icon: "leaf-02" },
      { title: "64 strefy", desc: "Matrycowy czujnik ciepła dzielący pomieszczenie na 64 strefy", icon: "thermometer-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalny", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata", icon: "shield-02" },
    ],
    models: [
      { name: "Stylish White 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 10400, area: "20–30 m²" },
      { name: "Stylish White 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "21 dB", phase: "230V", price: 10700, area: "30–40 m²" },
      { name: "Stylish White 5,0 kW", power: "5,0 kW", energyClass: "A+++/A+++", noise: "25 dB", phase: "230V", price: 16200, area: "40–60 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 5,0 kW",
    warranty: "3 lata gwarancji",
    imageUrl: "/images/products/daikin-stylish-white.png",
    imageAlt: "Klimatyzator ścienny Daikin Stylish White — biały matowy",
    gallery: [
      { src: "/images/products/daikin-stylish-white-gallery-0.png", alt: "Daikin Stylish White — widok boczny" },
    ],
  },

  // ═══════════════════════════════════════════════
  // MITSUBISHI ELECTRIC (5 products)
  // ═══════════════════════════════════════════════
  {
    slug: "mitsubishi-premium-white",
    name: "Mitsubishi Premium White",
    brand: "mitsubishi-electric",
    category: "scienny",
    tagline: "Japońska precyzja z A+++ i ciszą od 21 dB",
    origin: "Mitsubishi Electric (Japonia)",
    description:
      "Klimatyzator Mitsubishi Premium White to wysokiej klasy urządzenie łączące nowoczesne technologie z eleganckim designem. Błyszcząca biel jednostki wewnętrznej dodaje elegancji każdemu wnętrzu. Innowacyjna sprężarka inwerterowa zapewnia zmienną prędkość obrotową, wysoką efektywność energetyczną klasy A+++ w chłodzeniu i A++ w grzaniu, obniżone koszty eksploatacji i niezawodną, długoterminową pracę. Cisza od 21 dB. Sterowanie przez aplikację mobilną.",
    descriptionLong: [
      "Klimatyzator Mitsubishi Premium White to wysokiej klasy urządzenie łączące nowoczesne technologie z eleganckim designem, idealne dla osób ceniących funkcjonalność i estetykę.",
      "Błyszcząca biel jednostki wewnętrznej dodaje elegancji każdemu wnętrzu, doskonale komponując się z różnorodnymi aranżacjami.",
      "Innowacyjna sprężarka inwerterowa zapewnia zmienną prędkość obrotową, wysoką efektywność energetyczną klasy A+++ w chłodzeniu i A++ w grzaniu, obniżone koszty eksploatacji i niezawodną, długoterminową pracę.",
      "Poziom hałasu od zaledwie 21 dB czyni go niezwykle cichym — idealnym do sypialni i biur. Zestaw filtrów skutecznie oczyszcza powietrze z zanieczyszczeń. Sterowanie pilotem i aplikacją mobilną zapewniają pełną kontrolę z dowolnego miejsca.",
    ],
    highlight: "Premium A+++",
    features: [
      "Gwarancja 5 lat",
      "Automatyczne sterowanie wentylatorem",
      "Certyfikowana jakość",
      "Econo Cool",
      "i-Save",
      "Opcja pilota przewodowego",
      "Vertical Swing",
      "Automatyczny restart po awarii",
      "Timer tygodniowy",
      "Timer włącz/wyłącz",
      "Regulator zimowy",
      "Reuse Piping",
      "Tryb pompy ciepła",
      "Sterowanie przez aplikację mobilną",
    ],
    advantages: [
      { title: "A+++/A++", desc: "Najwyższa klasa energetyczna — najniższe rachunki", icon: "tick-02" },
      { title: "Cisza 21 dB", desc: "Wyjątkowo cicha praca — idealna do sypialni", icon: "volume-low" },
      { title: "Sprężarka inwerterowa", desc: "Zmienna prędkość obrotowa dla optymalnej wydajności", icon: "energy" },
      { title: "Japońska jakość", desc: "Mitsubishi Electric — synonim niezawodności i trwałości", icon: "shield-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 21 dB (wew.) / 47 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Tak (aplikacja)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Premium White 2,5 kW", power: "2,5 kW", energyClass: "A+++/A++", noise: "21 dB", phase: "230V", price: 7058, area: "20–30 m²" },
      { name: "Premium White 3,5 kW", power: "3,5 kW", energyClass: "A+++/A++", noise: "22 dB", phase: "230V", price: 8038, area: "30–40 m²" },
      { name: "Premium White 4,2 kW", power: "4,2 kW", energyClass: "A+++/A++", noise: "24 dB", phase: "230V", price: 8966, area: "40–50 m²" },
      { name: "Premium White 5,0 kW", power: "5,0 kW", energyClass: "A+++/A++", noise: "27 dB", phase: "230V", price: 9821, area: "50–60 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 5,0 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/mitsubishi-premium-white.png",
    imageAlt: "Klimatyzator ścienny Mitsubishi Premium White",
    gallery: [
      { src: "/images/products/mitsubishi-premium-white-gallery-0.jpg", alt: "Mitsubishi Premium White — widok boczny" },
      { src: "/images/products/mitsubishi-premium-white-gallery-1.jpg", alt: "Mitsubishi Premium White — panel" },
      { src: "/images/products/mitsubishi-premium-white-gallery-2.jpg", alt: "Mitsubishi Premium White — wnętrze" },
      { src: "/images/products/mitsubishi-premium-white-gallery-3.jpg", alt: "Mitsubishi Premium White — montaż" },
      { src: "/images/products/mitsubishi-premium-white-gallery-4.jpg", alt: "Mitsubishi Premium White — specyfikacja" },
    ],
  },
  {
    slug: "mitsubishi-diamond-natural-white",
    name: "Mitsubishi DIAMOND Natural White",
    brand: "mitsubishi-electric",
    category: "scienny",
    tagline: "Klasa premium z A+++ i czujnikiem 3D i-see",
    origin: "Mitsubishi Electric (Japonia)",
    description:
      "Model Mitsubishi Diamond Natural White to kwintesencja połączenia elegancji z najnowszymi technologiami, stworzony z myślą o użytkownikach poszukujących klimatyzatora ściennego klasy premium. Najwyższa klasa efektywności energetycznej A+++ w chłodzeniu i grzaniu. Technologia inwerterowa zapewnia imponujące osiągi przy bardzo niskim poziomie hałasu od 19 dB. Innowacyjny czujnik 3D i-see z zaawansowanymi filtrami zapewnia bezpieczne i komfortowe warunki z czystym i odpowiednio nawilżonym powietrzem.",
    descriptionLong: [
      "Model Mitsubishi Diamond Natural White to kwintesencja połączenia elegancji z najnowszymi technologiami, stworzony z myślą o użytkownikach poszukujących klimatyzatora ściennego klasy premium.",
      "Najwyższa klasa efektywności energetycznej A+++ w trybie chłodzenia i grzania, co czyni go ekonomicznym i przyjaznym dla środowiska.",
      "Technologia inwerterowa zapewnia imponujące osiągi przy bardzo niskim poziomie hałasu od zaledwie 19 dB — jednym z najcichszych na rynku.",
      "Innowacyjny czujnik 3D i-see z zaawansowanymi filtrami technologicznymi zapewnia bezpieczne i komfortowe warunki panujące w pomieszczeniu z czystym i odpowiednio nawilżonym powietrzem.",
    ],
    highlight: "Diamond premium",
    features: [
      "Gwarancja 5 lat",
      "Automatyczne sterowanie wentylatorem",
      "Certyfikowana jakość",
      "Econo Cool",
      "Hyper Heating (opcja)",
      "i-Save",
      "Inwerter",
      "Opcja pilota przewodowego",
      "Vertical Swing",
      "Automatyczny restart po awarii sieci",
      "Horizontal Swing",
      "Timer tygodniowy",
      "Timer włącz/wyłącz",
      "Regulator zimowy",
      "Reuse Piping",
      "Tryb nocny",
      "Tryb pompy ciepła",
      "Czujnik 3D i-see",
    ],
    advantages: [
      { title: "A+++/A+++", desc: "Najwyższa klasa w obu trybach — minimalne rachunki", icon: "tick-02" },
      { title: "Cisza 19 dB", desc: "Jeden z najcichszych klimatyzatorów na rynku", icon: "volume-low" },
      { title: "3D i-see", desc: "Innowacyjny czujnik analizujący trójwymiarowo warunki w pomieszczeniu", icon: "thermometer-01" },
      { title: "Hyper Heating", desc: "Opcjonalne grzanie w ekstremalnie niskich temperaturach", icon: "energy" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalny", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Diamond Natural White 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 8822, area: "20–30 m²" },
      { name: "Diamond Natural White 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "21 dB", phase: "230V", price: 10515, area: "30–40 m²" },
      { name: "Diamond Natural White 5,0 kW", power: "5,0 kW", energyClass: "A+++/A+++", noise: "25 dB", phase: "230V", price: 12245, area: "40–60 m²" },
      { name: "Diamond Natural White 6,1 kW", power: "6,1 kW", energyClass: "A+++/A+++", noise: "30 dB", phase: "230V", price: 13725, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,1 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/mitsubishi-diamond-natural-white.png",
    imageAlt: "Klimatyzator ścienny Mitsubishi DIAMOND Natural White",
    gallery: [],
  },
  {
    slug: "mitsubishi-diamond-pearl-white",
    name: "Mitsubishi DIAMOND Onyx Black",
    brand: "mitsubishi-electric",
    category: "scienny",
    tagline: "Lakierowana struktura Hair-line w intensywnej czerni",
    origin: "Mitsubishi Electric (Japonia)",
    description:
      "Mitsubishi Diamond Onyx Black to jeden z wyróżniających się klimatyzatorów ściennych oferowanych przez cenionego producenta. Model premium przyciąga uwagę nie tylko dzięki wyjątkowej konstrukcji, ale także lakierowanej strukturze Hair-line oraz intensywnej, błyszczącej czarnej obudowie. Klasa efektywności A++/A+++ (chłodzenie/grzanie), cisza od 19 dB. Innowacyjny czujnik 3D i-see z zaawansowanymi filtrami.",
    descriptionLong: [
      "Mitsubishi Diamond Onyx Black to jeden z wyróżniających się klimatyzatorów ściennych klasy premium. Przyciąga uwagę lakierowaną strukturą Hair-line oraz intensywną, błyszczącą czarną obudową.",
      "Doskonale komponuje się zarówno w ekstrawaganckich, jak i minimalistycznych nowoczesnych wnętrzach.",
      "Klasa efektywności energetycznej A++ w chłodzeniu i A+++ w grzaniu. Technologia inwerterowa zapewnia imponujące osiągi przy bardzo niskim poziomie hałasu od 19 dB.",
      "Innowacyjny czujnik 3D i-see z zaawansowanymi filtrami zapewnia bezpieczne, komfortowe warunki z czystym i odpowiednio nawilżonym powietrzem.",
    ],
    highlight: "Onyx Hair-line",
    features: [
      "Gwarancja 5 lat",
      "Automatyczne sterowanie wentylatorem",
      "Certyfikowana jakość",
      "Econo Cool",
      "Hyper Heating (opcja)",
      "i-Save",
      "Inwerter",
      "Opcja pilota przewodowego",
      "Vertical Swing",
      "Automatyczny restart po awarii sieci",
      "Horizontal Swing",
      "Timer tygodniowy",
      "Timer włącz/wyłącz",
      "Regulator zimowy",
      "Reuse Piping",
      "Tryb nocny",
      "Tryb pompy ciepła",
      "Lakierowana struktura Hair-line",
      "Czujnik 3D i-see",
    ],
    advantages: [
      { title: "Onyx Black", desc: "Lakierowana struktura Hair-line w intensywnej błyszczącej czerni", icon: "paint-board" },
      { title: "A++/A+++", desc: "Najwyższa klasa energetyczna w trybie grzania", icon: "tick-02" },
      { title: "Cisza 19 dB", desc: "Jeden z najcichszych klimatyzatorów na rynku", icon: "volume-low" },
      { title: "3D i-see", desc: "Czujnik trójwymiarowy analizujący warunki w pomieszczeniu", icon: "thermometer-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–36 dB (wew.) / 46 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalny", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Diamond Onyx Black 2,5 kW", power: "2,5 kW", energyClass: "A++/A+++", noise: "19 dB", phase: "230V", price: 9268, area: "20–30 m²" },
      { name: "Diamond Onyx Black 3,5 kW", power: "3,5 kW", energyClass: "A++/A+++", noise: "21 dB", phase: "230V", price: 10907, area: "30–40 m²" },
      { name: "Diamond Onyx Black 5,0 kW", power: "5,0 kW", energyClass: "A++/A+++", noise: "28 dB", phase: "230V", price: 12904, area: "40–60 m²" },
      { name: "Diamond Onyx Black 6,1 kW", power: "6,1 kW", energyClass: "A++/A+++", noise: "36 dB", phase: "230V", price: 14170, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,1 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/mitsubishi-diamond-pearl-white.png",
    imageAlt: "Klimatyzator ścienny Mitsubishi DIAMOND Onyx Black",
    gallery: [],
  },
  {
    slug: "mitsubishi-diamond-pearl-white-2",
    name: "Mitsubishi DIAMOND Pearl White",
    brand: "mitsubishi-electric",
    category: "scienny",
    tagline: "Perłowa biel z A+++ i czujnikiem 3D i-see",
    origin: "Mitsubishi Electric (Japonia)",
    description:
      "Mitsubishi Diamond Pearl White to jeden z nowoczesnych klimatyzatorów ściennych oferowanych przez cenionego producenta. Model premium wyróżnia się eleganckim wzornictwem w perłowej bieli, doskonale dopasowując się do nowoczesnych aranżacji wnętrz. Najwyższa klasa efektywności A+++ w chłodzeniu i grzaniu. Cisza od 19 dB. Innowacyjny czujnik 3D i-see z zaawansowanymi filtrami.",
    descriptionLong: [
      "Mitsubishi Diamond Pearl White to jeden z nowoczesnych klimatyzatorów ściennych klasy premium, wyróżniający się eleganckim wzornictwem w perłowej bieli.",
      "Doskonale dopasowuje się do nowoczesnych i klasycznych aranżacji wnętrz.",
      "Najwyższa klasa efektywności energetycznej A+++ zarówno w chłodzeniu, jak i grzaniu. Technologia inwerterowa zapewnia imponujące osiągi przy bardzo niskim poziomie hałasu od 19 dB.",
      "Innowacyjny czujnik 3D i-see z zaawansowanymi filtrami technologicznymi zapewnia bezpieczne i komfortowe warunki z czystym i odpowiednio nawilżonym powietrzem.",
    ],
    highlight: "Pearl White A+++",
    features: [
      "Gwarancja 5 lat",
      "Automatyczne sterowanie wentylatorem",
      "Certyfikowana jakość",
      "Econo Cool",
      "Hyper Heating (opcja)",
      "i-Save",
      "Inwerter",
      "Opcja pilota przewodowego",
      "Vertical Swing",
      "Automatyczny restart po awarii sieci",
      "Horizontal Swing",
      "Timer tygodniowy",
      "Timer włącz/wyłącz",
      "Regulator zimowy",
      "Reuse Piping",
      "Tryb nocny",
      "Tryb pompy ciepła",
      "Czujnik 3D i-see",
    ],
    advantages: [
      { title: "Pearl White", desc: "Elegancka perłowa biel dopasowująca się do każdego wnętrza", icon: "paint-board" },
      { title: "A+++/A+++", desc: "Najwyższa klasa w obu trybach — minimalne rachunki", icon: "tick-02" },
      { title: "Cisza 19 dB", desc: "Jeden z najcichszych klimatyzatorów na rynku", icon: "volume-low" },
      { title: "3D i-see", desc: "Czujnik trójwymiarowy analizujący warunki w pomieszczeniu", icon: "thermometer-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–36 dB (wew.) / 46 dB (zew.)", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalny", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Diamond Pearl White 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 9500, area: "20–30 m²" },
      { name: "Diamond Pearl White 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "21 dB", phase: "230V", price: 11070, area: "30–40 m²" },
      { name: "Diamond Pearl White 5,0 kW", power: "5,0 kW", energyClass: "A+++/A+++", noise: "28 dB", phase: "230V", price: 13250, area: "40–60 m²" },
      { name: "Diamond Pearl White 6,1 kW", power: "6,1 kW", energyClass: "A+++/A+++", noise: "36 dB", phase: "230V", price: 14495, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,1 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/mitsubishi-diamond-pearl-white-2.png",
    imageAlt: "Klimatyzator ścienny Mitsubishi DIAMOND Pearl White",
    gallery: [
      { src: "/images/products/mitsubishi-diamond-pearl-white-2-gallery-0.jpg", alt: "Mitsubishi Diamond Pearl White — widok boczny" },
      { src: "/images/products/mitsubishi-diamond-pearl-white-2-gallery-1.jpg", alt: "Mitsubishi Diamond Pearl White — panel" },
      { src: "/images/products/mitsubishi-diamond-pearl-white-2-gallery-2.jpg", alt: "Mitsubishi Diamond Pearl White — specyfikacja" },
    ],
  },
  {
    slug: "mitsubishi-diamond-ruby-red",
    name: "Mitsubishi DIAMOND Ruby Red",
    brand: "mitsubishi-electric",
    category: "scienny",
    tagline: "Flagowy model w intensywnej czerwieni z Hair-line i A+++",
    origin: "Mitsubishi Electric (Japonia)",
    description:
      "Mitsubishi Diamond Ruby Red to jeden z flagowych klimatyzatorów ściennych oferowanych przez cenionego producenta. Lakierowana struktura Hair-line w intensywnej czerwieni przyciąga uwagę swoim wyjątkowym wyglądem, doskonale komponując się w nowoczesnych wnętrzach. Najwyższa klasa efektywności A+++ w chłodzeniu i grzaniu. Cisza od 19 dB. Innowacyjny czujnik 3D i-see z zaawansowanymi filtrami.",
    descriptionLong: [
      "Mitsubishi Diamond Ruby Red to jeden z flagowych klimatyzatorów ściennych klasy premium. Lakierowana struktura Hair-line w intensywnej czerwieni przyciąga uwagę swoim wyjątkowym wyglądem.",
      "Doskonale komponuje się w nowoczesnych wnętrzach jako elegancki akcent kolorystyczny.",
      "Najwyższa klasa efektywności energetycznej A+++ zarówno w chłodzeniu, jak i grzaniu. Technologia inwerterowa zapewnia cisza od zaledwie 19 dB.",
      "Innowacyjny czujnik 3D i-see z zaawansowanymi filtrami zapewnia bezpieczne i komfortowe warunki z czystym i odpowiednio nawilżonym powietrzem.",
    ],
    highlight: "Ruby Red Hair-line",
    features: [
      "Gwarancja 5 lat",
      "Automatyczne sterowanie wentylatorem",
      "Certyfikowana jakość",
      "Econo Cool",
      "Hyper Heating (opcja)",
      "i-Save",
      "Inwerter",
      "Opcja pilota przewodowego",
      "Vertical Swing",
      "Automatyczny restart po awarii sieci",
      "Horizontal Swing",
      "Timer tygodniowy",
      "Timer włącz/wyłącz",
      "Regulator zimowy",
      "Reuse Piping",
      "Tryb nocny",
      "Tryb pompy ciepła",
      "Lakierowana struktura Hair-line",
      "Czujnik 3D i-see",
    ],
    advantages: [
      { title: "Ruby Red", desc: "Lakierowana struktura Hair-line w intensywnej czerwieni — unikatowy akcent", icon: "paint-board" },
      { title: "A+++/A+++", desc: "Najwyższa klasa w obu trybach — minimalne rachunki", icon: "tick-02" },
      { title: "Cisza 19 dB", desc: "Jeden z najcichszych klimatyzatorów na rynku", icon: "volume-low" },
      { title: "3D i-see", desc: "Czujnik trójwymiarowy analizujący warunki w pomieszczeniu", icon: "thermometer-01" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Opcjonalny", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Diamond Ruby Red 2,5 kW", power: "2,5 kW", energyClass: "A+++/A+++", noise: "19 dB", phase: "230V", price: 9268, area: "20–30 m²" },
      { name: "Diamond Ruby Red 3,5 kW", power: "3,5 kW", energyClass: "A+++/A+++", noise: "21 dB", phase: "230V", price: 10907, area: "30–40 m²" },
      { name: "Diamond Ruby Red 5,0 kW", power: "5,0 kW", energyClass: "A+++/A+++", noise: "28 dB", phase: "230V", price: 12904, area: "40–60 m²" },
      { name: "Diamond Ruby Red 6,1 kW", power: "6,1 kW", energyClass: "A+++/A+++", noise: "36 dB", phase: "230V", price: 14170, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,1 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/mitsubishi-diamond-ruby-red.png",
    imageAlt: "Klimatyzator ścienny Mitsubishi DIAMOND Ruby Red",
    gallery: [],
  },

  // ═══════════════════════════════════════════════
  // MITSUBISHI HEAVY (2 products)
  // ═══════════════════════════════════════════════
  {
    slug: "mitsubishi-heavy-premium",
    name: "Mitsubishi Heavy Premium",
    brand: "mitsubishi-heavy",
    category: "scienny",
    tagline: "Mediolański design z A+++ i czynnikiem R32",
    origin: "Mitsubishi Heavy Industries (Japonia)",
    description:
      "Klimatyzatory ścienne serii Premium Mitsubishi Heavy Industries przeznaczone są do chłodzenia lub ogrzewania mieszkań, domów oraz pomieszczeń biurowych, oferując wydajność chłodniczą w zakresie od 1,50 do 5,00 kW. Design opracowany w Mediolanie łączy niezawodną technologię z eleganckim, uniwersalnym wzornictwem. Dostępne w trzech wariantach kolorystycznych: tytanowym, czarno-białym i białym. Klasa energetyczna A+++, czynnik R32, standardowy moduł WiFi.",
    descriptionLong: [
      "Klimatyzatory ścienne serii Premium Mitsubishi Heavy Industries przeznaczone są do chłodzenia lub ogrzewania mieszkań, domów oraz pomieszczeń biurowych, oferując wydajność chłodniczą w zakresie od 1,50 do 5,00 kW.",
      "Design opracowany w Mediolanie łączy niezawodną technologię z eleganckim, uniwersalnym wzornictwem. Dostępne w trzech wariantach kolorystycznych: tytanowym, czarno-białym i białym.",
      "Urządzenia zapewniają wysoki komfort chłodzenia i ogrzewania z klasą energetyczną A+++, gwarantując znaczne oszczędności energii.",
      "W standardowym wyposażeniu znajduje się interfejs WiFi z aplikacją M-Air umożliwiającą zdalne sterowanie smartfonem z dowolnego miejsca.",
    ],
    highlight: "Milan Design A+++",
    features: [
      "Automatyczne samooczyszczanie",
      "Automatyczny restart",
      "Automatyczne sterowanie wentylatorem",
      "Tryb ECO",
      "Econo Cool",
      "Szybkie chłodzenie (Fast Cooling)",
      "Filtr Easy Plus",
      "Inwerter",
      "Timer 24-godzinny i licznik czasu",
      "Opcja pilota przewodowego",
      "Osuszanie",
      "Vertical Swing",
      "Automatyczny restart po awarii sieci",
      "Horizontal Swing",
      "Harmonogram tygodniowy",
      "Timer włącz/wyłącz",
      "Regulator zimowy",
      "Reuse Piping",
      "Sterowanie sygnałem dźwiękowym",
      "Tryb cichy (Silent)",
      "Tryb nocny",
      "Tryb pompy ciepła",
      "WiFi z aplikacją M-Air (standard)",
    ],
    advantages: [
      { title: "Milan Design", desc: "Wzornictwo opracowane w Mediolanie — elegancja i uniwersalność", icon: "paint-board" },
      { title: "A+++/A++", desc: "Najwyższa klasa zapewniająca znaczne oszczędności energii", icon: "tick-02" },
      { title: "WiFi M-Air", desc: "Standardowy moduł WiFi z aplikacją do zdalnego sterowania", icon: "wifi-full-signal" },
      { title: "3 kolory", desc: "Dostępny w tytanie, czarno-białym i białym", icon: "paint-board" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A+++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 19 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (M-Air, standard)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata", icon: "shield-02" },
    ],
    models: [
      { name: "Heavy Premium 2,5 kW", power: "2,5 kW", energyClass: "A+++/A++", noise: "19 dB", phase: "230V", price: 6050, area: "25–35 m²" },
      { name: "Heavy Premium 3,5 kW", power: "3,5 kW", energyClass: "A+++/A++", noise: "22 dB", phase: "230V", price: 6800, area: "40–50 m²" },
      { name: "Heavy Premium 5,0 kW", power: "5,0 kW", energyClass: "A+++/A++", noise: "28 dB", phase: "230V", price: 9100, area: "50–60 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 5,0 kW",
    warranty: "3 lata gwarancji",
    imageUrl: "/images/products/mitsubishi-heavy-premium.png",
    imageAlt: "Klimatyzator ścienny Mitsubishi Heavy Premium",
    gallery: [],
  },
  {
    slug: "klimatyzato-mitsubishi-heavy-diamond-srk25zsx-wf",
    name: "Mitsubishi Heavy Diamond",
    brand: "mitsubishi-heavy",
    category: "scienny",
    tagline: "Seria Diamond z zasięgiem 17m, WiFi i czujnikiem ruchu",
    origin: "Mitsubishi Heavy Industries (Japonia)",
    description:
      "Typoszereg klimatyzatorów ściennych serii Diamond Mitsubishi Heavy Industries jest przeznaczony do chłodzenia lub ogrzewania mieszkań, domów oraz małych pomieszczeń biurowych, z wydajnością chłodniczą od 2,00 do 6,00 kW. Standardowy interfejs WiFi z aplikacją M-Air. Dostępne w trzech wariantach: Pure White, Black-White i Titanium. Praca w zakresie od -20°C (grzanie) do +46°C (chłodzenie). Cisza od 19 dB(A), zasięg strugi powietrza do 17 metrów, długość instalacji do 30 metrów (budynki 3-piętrowe). Technologia 3D Auto, czujnik ruchu, funkcja Hi-Power.",
    descriptionLong: [
      "Typoszereg klimatyzatorów ściennych serii Diamond Mitsubishi Heavy Industries jest przeznaczony do chłodzenia lub ogrzewania mieszkań, domów oraz małych pomieszczeń biurowych, z wydajnością chłodniczą od 2,00 do 6,00 kW.",
      "W standardowym wyposażeniu znajduje się interfejs WiFi z inteligentną aplikacją M-Air umożliwiającą zdalne sterowanie smartfonem z dowolnego miejsca na świecie. Dostępne w trzech wariantach kolorystycznych: Pure White, Black-White i Titanium.",
      "Urządzenia pracują w szerokim zakresie temperatur: od -20°C (grzanie) do +46°C (chłodzenie). Cisza od zaledwie 19 dB(A), zasięg strugi powietrza do 17 metrów.",
      "Długość instalacji czynnika chłodniczego do 30 metrów, umożliwiając montaż w budynkach 3-piętrowych. Technologia 3D Auto, czujnik ruchu i funkcja Hi-Power zapewniają optymalny komfort.",
    ],
    highlight: "Zasięg 17m Diamond",
    features: [
      "Automatyczne sterowanie wentylatorem",
      "Inwerter",
      "Certyfikowana jakość",
      "Econo Cool",
      "Technologia 3D Auto",
      "Czujnik ruchu (Motion Sensor)",
      "Funkcja Hi-Power",
      "Ustawienia predefiniowane",
      "Vertical Swing",
      "Horizontal Swing",
      "Timer tygodniowy",
      "Timer włącz/wyłącz",
      "Tryb nocny",
      "Opcja pilota przewodowego",
      "WiFi z aplikacją M-Air (standard)",
      "Zasięg nawiewu do 17 metrów",
      "Instalacja do 30 metrów",
      "Praca od -20°C do +46°C",
    ],
    advantages: [
      { title: "Zasięg 17m", desc: "Struga powietrza docierająca na odległość 17 metrów", icon: "energy" },
      { title: "3D Auto", desc: "Automatyczna regulacja trójwymiarowego nawiewu powietrza", icon: "thermometer-01" },
      { title: "Czujnik ruchu", desc: "Wykrywa obecność osób i optymalizuje kierunek nawiewu", icon: "wifi-full-signal" },
      { title: "Instalacja 30m", desc: "Długość instalacji do 30m — budynki 3-piętrowe", icon: "tick-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "19–40 dB(A)", icon: "volume-low" },
      { label: "WiFi", value: "Tak (M-Air, standard)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata", icon: "shield-02" },
    ],
    models: [
      { name: "Heavy Diamond 2,5 kW", power: "2,5 kW", energyClass: "A/A", noise: "19 dB", phase: "230V", price: 8800, area: "30–40 m²" },
      { name: "Heavy Diamond 3,5 kW", power: "3,5 kW", energyClass: "A/A", noise: "22 dB", phase: "230V", price: 10250, area: "40–50 m²" },
      { name: "Heavy Diamond 5,0 kW", power: "5,0 kW", energyClass: "A/A", noise: "28 dB", phase: "230V", price: 12270, area: "50–60 m²" },
      { name: "Heavy Diamond 6,1 kW", power: "6,1 kW", energyClass: "A/A", noise: "36 dB", phase: "230V", price: 13420, area: "60–70 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 6,1 kW",
    warranty: "3 lata gwarancji",
    imageUrl: "/images/products/klimatyzato-mitsubishi-heavy-diamond-srk25zsx-wf.png",
    imageAlt: "Klimatyzator ścienny Mitsubishi Heavy Diamond",
    gallery: [
      { src: "/images/products/klimatyzato-mitsubishi-heavy-diamond-srk25zsx-wf-gallery-0.png", alt: "Mitsubishi Heavy Diamond — Pure White" },
      { src: "/images/products/klimatyzato-mitsubishi-heavy-diamond-srk25zsx-wf-gallery-1.png", alt: "Mitsubishi Heavy Diamond — Black-White" },
      { src: "/images/products/klimatyzato-mitsubishi-heavy-diamond-srk25zsx-wf-gallery-2.png", alt: "Mitsubishi Heavy Diamond — Titanium" },
      { src: "/images/products/klimatyzato-mitsubishi-heavy-diamond-srk25zsx-wf-gallery-3.png", alt: "Mitsubishi Heavy Diamond — specyfikacja" },
    ],
  },

  // ═══════════════════════════════════════════════
  // GE (2 products)
  // ═══════════════════════════════════════════════
  {
    slug: "klimatyzator-scienny-ge-future-white",
    name: "GE Future White",
    brand: "ge",
    category: "scienny",
    tagline: "Lustrzany front, A+++ i jonizator w ponadczasowym designie",
    origin: "GE Appliances (USA)",
    description:
      "Klimatyzator GE Appliances Future został zaprojektowany dla osób ceniących wysoką jakość oraz ponadczasowy design. Lustrzany front jednostki wewnętrznej idealnie komponuje się z nowoczesnymi aranżacjami wnętrz. Future łączy wysoką energooszczędność A+++ z innowacyjnymi technologiami podwyższającymi komfort i zapewniającymi optymalne warunki przez cały rok. Zaawansowane oczyszczanie powietrza i wbudowany jonizator gwarantują lepszą jakość powietrza. Czynnik R32, technologia Blue Fin, WiFi w standardzie.",
    descriptionLong: [
      "Klimatyzator GE Appliances Future został zaprojektowany dla osób ceniących wysoką jakość oraz ponadczasowy design. Lustrzany front jednostki wewnętrznej w kolorze białym idealnie komponuje się z nowoczesnymi aranżacjami wnętrz.",
      "Future łączy wysoką energooszczędność klasy A+++ z innowacyjnymi technologiami podwyższającymi komfort i zapewniającymi optymalne warunki przez cały rok.",
      "Zaawansowane oczyszczanie powietrza i wbudowany jonizator gwarantują lepszą jakość powietrza w Twoim domu.",
      "Czynnik R32, technologia Blue Fin zapobiegająca rozwojowi pleśni i gromadzeniu kurzu, nawiew 3D i sterowanie WiFi w standardzie.",
    ],
    highlight: "Lustrzany A+++",
    features: [
      "Timer 24-godzinny",
      "Certyfikat PZH",
      "Autodiagnostyka",
      "Automatyczny restart",
      "Blokada pilota (LOCK)",
      "Chłodzenie w niskich temperaturach",
      "Cicha praca",
      "DC Inverter",
      "Opcjonalny filtr 3M",
      "Filtr antykurzowy",
      "Funkcja ciepłego startu (Warm Start)",
      "Funkcja SMART",
      "Funkcja zdrowego nawiewu",
      "Grzanie w niskich temperaturach",
      "Jonizator",
      "Klasa A+++",
      "Nawiew 3D",
      "Nowoczesny design",
      "Pamięć ustawień żaluzji",
      "Żaluzje poziome",
      "Timer tygodniowy",
      "Czynnik R32",
      "Silnik DC",
      "Technologia Blue Fin",
      "Tryb Power",
      "Tryb Sleep",
      "Vertical Swing",
      "WiFi Standard",
      "Przyciemnianie ekranu LED",
      "Wyświetlacz LED",
    ],
    advantages: [
      { title: "Lustrzany front", desc: "Elegancki biały lustrzany panel komponujący się z każdym wnętrzem", icon: "paint-board" },
      { title: "A+++", desc: "Najwyższa klasa energetyczna zapewniająca najniższe rachunki", icon: "tick-02" },
      { title: "Jonizator", desc: "Wbudowany jonizator poprawiający jakość powietrza", icon: "leaf-02" },
      { title: "Blue Fin", desc: "Technologia zapobiegająca pleśni i gromadzeniu kurzu", icon: "shield-02" },
    ],
    specs: [
      { label: "Klasa", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 20 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (standard)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata", icon: "shield-02" },
    ],
    models: [
      { name: "GE Future White 2,6 kW", power: "2,6 kW", energyClass: "A+++", noise: "20 dB", phase: "230V", price: 5250, area: "25–35 m²" },
      { name: "GE Future White 3,5 kW", power: "3,5 kW", energyClass: "A+++", noise: "22 dB", phase: "230V", price: 5490, area: "30–40 m²" },
      { name: "GE Future White 5,0 kW", power: "5,0 kW", energyClass: "A+++", noise: "28 dB", phase: "230V", price: 7490, area: "50–60 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 5,0 kW",
    warranty: "3 lata gwarancji",
    imageUrl: "/images/products/klimatyzator-scienny-ge-future-white.png",
    imageAlt: "Klimatyzator ścienny GE Future White — lustrzany front",
    gallery: [
      { src: "/images/products/klimatyzator-scienny-ge-future-white-gallery-0.png", alt: "GE Future White — widok boczny" },
      { src: "/images/products/klimatyzator-scienny-ge-future-white-gallery-1.png", alt: "GE Future White — specyfikacja" },
      { src: "/images/products/klimatyzator-scienny-ge-future-white-gallery-2.jpeg", alt: "GE Future White — instalacja" },
      { src: "/images/products/klimatyzator-scienny-ge-future-white-gallery-3.jpeg", alt: "GE Future White — technologie" },
    ],
  },
  {
    slug: "klimatyzator-ge-prime",
    name: "GE Prime+",
    brand: "ge",
    category: "scienny",
    tagline: "Przystępna cena z zaawansowaną technologią i Blue Fin",
    origin: "GE Appliances (USA)",
    description:
      "Klimatyzator GE Appliances Prime+ łączy przystępną cenę, zaawansowaną technologię i wyjątkową estetykę. Model charakteryzują dyskretne zaokrąglenia, wyświetlacz LED oraz błyszcząca powierzchnia. Unikalna technologia obrotowej sprężarki inwerterowej zapewnia pracę nawet w najtrudniejszych warunkach pogodowych. Wbudowany jonizator powietrza i specjalna powłoka Blue Fin zapobiegająca rozwojowi pleśni i gromadzeniu kurzu. Klasa A+++, czynnik R32, WiFi w standardzie.",
    descriptionLong: [
      "Klimatyzator GE Appliances Prime+ łączy przystępną cenę, zaawansowaną technologię i wyjątkową estetykę. Model charakteryzują dyskretne zaokrąglenia, wyświetlacz LED oraz błyszcząca powierzchnia.",
      "Unikalna technologia obrotowej sprężarki inwerterowej GE Appliances umożliwia pracę nawet w najtrudniejszych warunkach pogodowych.",
      "Seria Prime+ wyposażona jest w jonizator powietrza, a specjalna powłoka Blue Fin zapobiega rozwojowi pleśni i gromadzeniu kurzu na wymienniku ciepła.",
      "Klasa energetyczna A+++, ekologiczny czynnik R32, sterowanie WiFi w standardzie.",
    ],
    highlight: "Najlepsza cena GE",
    features: [
      "Timer 24-godzinny",
      "Certyfikat PZH",
      "Autodiagnostyka",
      "Automatyczny restart",
      "Blokada pilota (LOCK)",
      "Chłodzenie w niskich temperaturach",
      "Cicha praca",
      "DC Inverter",
      "Opcjonalny filtr 3M",
      "Filtr antykurzowy",
      "Funkcja ciepłego startu",
      "Funkcja SMART",
      "Funkcja zdrowego nawiewu",
      "Grzanie w niskich temperaturach",
      "Jonizator",
      "Klasa A+++",
      "Nawiew 3D",
      "Nowoczesny design",
      "Pamięć ustawień żaluzji",
      "Żaluzje poziome",
      "Timer tygodniowy",
      "Czynnik R32",
      "Silnik DC",
      "Technologia Blue Fin",
      "Tryb Power",
      "Tryb cichy Sleep",
      "Vertical Swing",
      "WiFi Standard",
      "Wyświetlacz LED",
    ],
    advantages: [
      { title: "Najlepsza cena", desc: "Zaawansowana technologia GE w najkorzystniejszej cenie", icon: "tick-02" },
      { title: "A+++", desc: "Najwyższa klasa energetyczna w przystępnym budżecie", icon: "tick-02" },
      { title: "Blue Fin", desc: "Powłoka zapobiegająca pleśni i gromadzeniu kurzu", icon: "shield-02" },
      { title: "Jonizator", desc: "Wbudowany jonizator poprawiający jakość powietrza", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa", value: "A+++", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 20 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak (standard)", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "3 lata", icon: "shield-02" },
    ],
    models: [
      { name: "GE Prime+ 2,5 kW", power: "2,5 kW", energyClass: "A+++", noise: "20 dB", phase: "230V", price: 3950, area: "25–35 m²" },
      { name: "GE Prime+ 3,5 kW", power: "3,5 kW", energyClass: "A+++", noise: "22 dB", phase: "230V", price: 4270, area: "30–40 m²" },
      { name: "GE Prime+ 5,0 kW", power: "5,0 kW", energyClass: "A+++", noise: "28 dB", phase: "230V", price: 6150, area: "40–60 m²" },
      { name: "GE Prime+ 7,0 kW", power: "7,0 kW", energyClass: "A+++", noise: "34 dB", phase: "230V", price: 7760, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,5 – 7,0 kW",
    warranty: "3 lata gwarancji",
    imageUrl: "/images/products/klimatyzator-ge-prime.png",
    imageAlt: "Klimatyzator ścienny GE Prime+",
    gallery: [
      { src: "/images/products/klimatyzator-ge-prime-gallery-0.png", alt: "GE Prime+ — widok boczny" },
      { src: "/images/products/klimatyzator-ge-prime-gallery-1.png", alt: "GE Prime+ — specyfikacja" },
      { src: "/images/products/klimatyzator-ge-prime-gallery-2.jpeg", alt: "GE Prime+ — technologie" },
      { src: "/images/products/klimatyzator-ge-prime-gallery-3.jpeg", alt: "GE Prime+ — instalacja" },
    ],
  },

  // ═══════════════════════════════════════════════
  // ROTENSO (1 product, brand: "aux")
  // ═══════════════════════════════════════════════
  {
    slug: "rotenso-imoto-x",
    name: "Rotenso Imoto X",
    brand: "aux",
    category: "scienny",
    tagline: "Klasyczny design ze szkłem akrylowym i szerokim kątem nawiewu",
    origin: "Rotenso (marka AUX Group)",
    description:
      "Rotenso Imoto X to klimatyzator o wyjątkowym, klasycznym wyglądzie, przez co będzie wyglądać perfekcyjnie w niemal każdej aranżacji. Na szczególną uwagę zasługuje wykończenie krawędzi panelu transparentnym szkłem akrylowym. Szeroki kąt nawiewu zapewnia stabilne warunki termiczne w większych pomieszczeniach. Technologia inwerterowa, czynnik R32, klasa energetyczna A++.",
    descriptionLong: [
      "Rotenso Imoto X to klimatyzator o wyjątkowym, klasycznym wyglądzie, przez co będzie wyglądać perfekcyjnie w niemal każdej aranżacji.",
      "Na szczególną uwagę zasługuje wykończenie krawędzi panelu transparentnym szkłem akrylowym, które nadaje urządzeniu elegancki i nowoczesny charakter.",
      "Szeroki kąt nawiewu zapewnia stabilne warunki termiczne nawet w większych pomieszczeniach. Technologia inwerterowa i czynnik R32 zapewniają wysoką efektywność energetyczną klasy A++.",
    ],
    highlight: "Szkło akrylowe",
    features: [
      "Klasyczny design z akcentem akrylowym",
      "Transparentne szkło akrylowe na krawędziach panelu",
      "Szeroki kąt nawiewu",
      "Technologia inwerterowa",
      "Czynnik R32",
      "Tryb chłodzenia i grzania",
      "Sterowanie pilotem",
      "Filtracja powietrza",
      "Cicha praca",
      "Timer",
    ],
    advantages: [
      { title: "Szkło akrylowe", desc: "Transparentne wykończenie krawędzi nadające elegancki charakter", icon: "paint-board" },
      { title: "Szeroki nawiew", desc: "Szeroki kąt nawiewu zapewniający stabilne warunki w dużych pomieszczeniach", icon: "energy" },
      { title: "Klasyczny design", desc: "Wyjątkowy wygląd pasujący do każdej aranżacji", icon: "paint-board" },
      { title: "R32 Inwerter", desc: "Ekologiczny czynnik z technologią inwerterową", icon: "leaf-02" },
    ],
    specs: [
      { label: "Klasa chłodzenie", value: "A++", icon: "tick-02" },
      { label: "Klasa grzanie", value: "A+", icon: "tick-02" },
      { label: "Czynnik", value: "R32", icon: "leaf-02" },
      { label: "Hałas", value: "od 22 dB", icon: "volume-low" },
      { label: "WiFi", value: "Tak", icon: "wifi-full-signal" },
      { label: "Gwarancja", value: "5 lat", icon: "shield-02" },
    ],
    models: [
      { name: "Rotenso Imoto X 2,6 kW", power: "2,6 kW", energyClass: "A++/A+", noise: "22 dB", phase: "230V", price: 3500, area: "20–30 m²" },
      { name: "Rotenso Imoto X 3,5 kW", power: "3,5 kW", energyClass: "A++/A+", noise: "24 dB", phase: "230V", price: 3800, area: "30–40 m²" },
      { name: "Rotenso Imoto X 5,3 kW", power: "5,3 kW", energyClass: "A++/A+", noise: "30 dB", phase: "230V", price: 5100, area: "40–60 m²" },
      { name: "Rotenso Imoto X 7,0 kW", power: "7,0 kW", energyClass: "A++/A+", noise: "36 dB", phase: "230V", price: 6200, area: "60–80 m²" },
    ],
    refrigerant: "R32",
    refrigerantNote: "GWP = 675 · ekologiczny czynnik nowej generacji",
    powerRange: "2,6 – 7,0 kW",
    warranty: "5 lat gwarancji",
    imageUrl: "/images/products/rotenso-imoto-x.webp",
    imageAlt: "Klimatyzator ścienny Rotenso Imoto X ze szkłem akrylowym",
    gallery: [],
  },
];
