import type { Testimonial } from "@/types";

export const testimonials: Testimonial[] = [
  {
    name: "Marcin Kowalski",
    body: "Profesjonalny montaż klimatyzacji Samsung Wind-Free w mieszkaniu na Mokotowie. Ekipa punktualna, czysto po sobie posprzątali. Klimatyzator działa cicho, polecam PBAC.",
    rating: 5,
    location: "Warszawa",
    service: "montaz",
  },
  {
    name: "Anna Wiśniewska",
    body: "Zamontowali mi dwa klimatyzatory LG ArtCool w domu jednorodzinnym. Fachowe doradztwo przy doborze mocy, szybki termin realizacji. Cena zgodna z wyceną, bez niespodzianek.",
    rating: 5,
    location: "Piaseczno",
    service: "montaz",
  },
  {
    name: "Tomasz Nowak",
    body: "Serwis klimatyzacji po sezonie — przyjechali na czas, wyczyścili oba urządzenia, sprawdzili poziom czynnika. Profesjonalne podejście i uczciwa cena za przegląd.",
    rating: 5,
    location: "Warszawa",
    service: "serwis",
  },
  {
    name: "Katarzyna Lewandowska",
    body: "Montaż Toshiba Haori w sypialni. Bardzo cicha praca, nowoczesny wygląd pasuje do wnętrza. Instalatorzy doradzili optymalną lokalizację jednostki wewnętrznej.",
    rating: 5,
    location: "Legionowo",
    service: "montaz",
  },
  {
    name: "Piotr Zieliński",
    body: "Klimatyzacja w biurze — 3 jednostki Gree Clivia. Montaż sprawnie w weekend, żeby nie zakłócać pracy firmy. Od dwóch lat bez problemów, regularny serwis w PBAC.",
    rating: 5,
    location: "Warszawa",
    service: "montaz",
  },
  {
    name: "Magdalena Kamińska",
    body: "Wynajęłam klimatyzator przenośny na czas remontu i byłam pozytywnie zaskoczona obsługą. Szybka dostawa, jasne warunki wynajmu. Na pewno skorzystam ponownie.",
    rating: 4,
    location: "Otwock",
    service: "wynajem",
  },
  {
    name: "Robert Jabłoński",
    body: "Montaż pompy ciepła i klimatyzacji w nowym domu. PBAC ogarnęli wszystko kompleksowo — dobór urządzeń, instalacja hydrauliczna i elektryczna, uruchomienie. Gorąco polecam!",
    rating: 5,
    location: "Grodzisk Mazowiecki",
    service: "montaz",
  },
  {
    name: "Ewa Szymańska",
    body: "Po 3 latach użytkowania klimatyzacja zaczęła dziwnie pachnieć. Serwis PBAC przyjechał następnego dnia, wymienił filtry i wykonał dezynfekcję. Problem zniknął od razu.",
    rating: 5,
    location: "Pruszków",
    service: "serwis",
  },
  {
    name: "Jakub Wójcik",
    body: "Daikin Stylish w salonie — montaż trwał kilka godzin, efekt końcowy rewelacyjny. Klimatyzator wygląda jak element wystroju, a nie urządzenie techniczne. Cena wyższa, ale warto.",
    rating: 5,
    location: "Warszawa",
    service: "montaz",
  },
  {
    name: "Monika Dąbrowska",
    body: "Zamontowali klimatyzację w bloku na Ursynowie. Pomogli z formalnościami w spółdzielni, co bardzo ułatwiło cały proces. Polecam szczególnie mieszkańcom bloków.",
    rating: 5,
    location: "Warszawa",
    service: "montaz",
  },
  {
    name: "Andrzej Mazur",
    body: "Coroczny przegląd trzech klimatyzatorów Samsung w domu. Technik przyjechał punktualnie, wyczyścił wszystkie jednostki, sprawdził czynnik i zostawił raport. Różnica w działaniu po serwisie jest odczuwalna — chłodzi wyraźnie lepiej.",
    rating: 5,
    location: "Piaseczno",
    service: "serwis",
  },
  {
    name: "Joanna Krawczyk",
    body: "Klimatyzator zaczął kapać wodą z jednostki wewnętrznej. Zadzwoniłam do PBAC i następnego dnia przyjechał serwisant. Okazało się, że zatkany odpływ skroplin — naprawa zajęła 30 minut. Szybko i profesjonalnie.",
    rating: 5,
    location: "Legionowo",
    service: "serwis",
  },
  {
    name: "Krzysztof Borkowski",
    body: "Mam umowę serwisową na 4 klimatyzatory w biurze. Dwa przeglądy rocznie, zero problemów od trzech lat. Cena uczciwa, terminy zawsze dotrzymane. Polecam firmom.",
    rating: 5,
    location: "Warszawa",
    service: "serwis",
  },
  {
    name: "Agnieszka Pawlak",
    body: "Serwis Toshiba Haori po dwóch sezonach. Technik wymienił filtr katalityczny, wyczyścił parownik i zrobił dezynfekcję. Klimatyzator znowu pachnie świeżością, a nie stęchlizną. Warto robić przegląd co roku.",
    rating: 5,
    location: "Łomianki",
    service: "serwis",
  },
  {
    name: "Marek Olszewski",
    body: "Serwis awaryjny w sobotę — klimatyzator przestał chłodzić w środku upału. Technik PBAC przyjechał tego samego dnia, uzupełnił czynnik i wykrył drobną nieszczelność. Naprawa na miejscu, bez konieczności demontażu. Ratunek w upał!",
    rating: 5,
    location: "Otwock",
    service: "serwis",
  },
];
